// Code generated by pdlgen. DO NOT EDIT.

// Package fetch provides the Chrome DevTools Protocol
// commands, types, and events for the Fetch domain.
//
// A domain for letting clients substitute browser's network layer with
// client code.
//
// Generated by the pdlgen command.
package fetch

import (
	"encoding/base64"
	jsonv2 "encoding/json/v2"
	"fmt"

	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/io"
	"github.com/chromedp/cdproto/network"
)

// Disable disables the fetch domain.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Fetch#method-disable
var Disable = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandDisable}

// EnableParams are the parameters of the command Fetch.enable.
type EnableParams struct {
	Patterns           []*RequestPattern `json:"patterns,omitempty,omitzero"`           // If specified, only requests matching any of these patterns will produce fetchRequested event and will be paused until clients response. If not set, all requests will be affected.
	HandleAuthRequests *bool             `json:"handleAuthRequests,omitempty,omitzero"` // If true, authRequired events will be issued and requests will be paused expecting a call to continueWithAuth.
}

// Enable enables issuing of requestPaused events. A request will be paused
// until client calls one of failRequest, fulfillRequest or
// continueRequest/continueWithAuth.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Fetch#method-enable
var Enable = cdp.Command[EnableParams, cdp.Empty]{Method: CommandEnable}

// FailRequestParams are the parameters of the command Fetch.failRequest.
type FailRequestParams struct {
	RequestID   RequestID           `json:"requestId"`   // An id the client received in requestPaused event.
	ErrorReason network.ErrorReason `json:"errorReason"` // Causes the request to fail with the given reason.
}

// FailRequest causes the request to fail with specified reason.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Fetch#method-failRequest
var FailRequest = cdp.Command[FailRequestParams, cdp.Empty]{Method: CommandFailRequest}

// FulfillRequestParams are the parameters of the command
// Fetch.fulfillRequest.
type FulfillRequestParams struct {
	RequestID             RequestID      `json:"requestId"`                                // An id the client received in requestPaused event.
	ResponseCode          int64          `json:"responseCode"`                             // An HTTP response code.
	ResponseHeaders       []*HeaderEntry `json:"responseHeaders,omitempty,omitzero"`       // Response headers.
	BinaryResponseHeaders []byte         `json:"binaryResponseHeaders,omitempty,omitzero"` // Alternative way of specifying response headers as a \0-separated series of name: value pairs. Prefer the above method unless you need to represent some non-UTF8 values that can't be transmitted over the protocol as text.
	Body                  []byte         `json:"body,omitempty,omitzero"`                  // A response body. If absent, original response body will be used if the request is intercepted at the response stage and empty body will be used if the request is intercepted at the request stage.
	ResponsePhrase        string         `json:"responsePhrase,omitempty,omitzero"`        // A textual representation of responseCode. If absent, a standard phrase matching responseCode is used.
}

// FulfillRequest provides response to the request.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Fetch#method-fulfillRequest
var FulfillRequest = cdp.Command[FulfillRequestParams, cdp.Empty]{Method: CommandFulfillRequest}

// ContinueRequestParams are the parameters of the command
// Fetch.continueRequest.
type ContinueRequestParams struct {
	RequestID         RequestID      `json:"requestId"`                            // An id the client received in requestPaused event.
	URL               string         `json:"url,omitempty,omitzero"`               // If set, the request url will be modified in a way that's not observable by page.
	Method            string         `json:"method,omitempty,omitzero"`            // If set, the request method is overridden.
	PostData          []byte         `json:"postData,omitempty,omitzero"`          // If set, overrides the post data in the request.
	Headers           []*HeaderEntry `json:"headers,omitempty,omitzero"`           // If set, overrides the request headers. Note that the overrides do not extend to subsequent redirect hops, if a redirect happens. Another override may be applied to a different request produced by a redirect.
	InterceptResponse *bool          `json:"interceptResponse,omitempty,omitzero"` // If set, overrides response interception behavior for this request.
}

// ContinueRequest continues the request, optionally modifying some of its
// parameters.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Fetch#method-continueRequest
var ContinueRequest = cdp.Command[ContinueRequestParams, cdp.Empty]{Method: CommandContinueRequest}

// ContinueWithAuthParams are the parameters of the command
// Fetch.continueWithAuth.
type ContinueWithAuthParams struct {
	RequestID             RequestID              `json:"requestId"`             // An id the client received in authRequired event.
	AuthChallengeResponse *AuthChallengeResponse `json:"authChallengeResponse"` // Response to  with an authChallenge.
}

// ContinueWithAuth continues a request supplying authChallengeResponse
// following authRequired event.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Fetch#method-continueWithAuth
var ContinueWithAuth = cdp.Command[ContinueWithAuthParams, cdp.Empty]{Method: CommandContinueWithAuth}

// ContinueResponseParams are the parameters of the command
// Fetch.continueResponse.
type ContinueResponseParams struct {
	RequestID             RequestID      `json:"requestId"`                                // An id the client received in requestPaused event.
	ResponseCode          int64          `json:"responseCode,omitempty,omitzero"`          // An HTTP response code. If absent, original response code will be used.
	ResponsePhrase        string         `json:"responsePhrase,omitempty,omitzero"`        // A textual representation of responseCode. If absent, a standard phrase matching responseCode is used.
	ResponseHeaders       []*HeaderEntry `json:"responseHeaders,omitempty,omitzero"`       // Response headers. If absent, original response headers will be used.
	BinaryResponseHeaders []byte         `json:"binaryResponseHeaders,omitempty,omitzero"` // Alternative way of specifying response headers as a \0-separated series of name: value pairs. Prefer the above method unless you need to represent some non-UTF8 values that can't be transmitted over the protocol as text.
}

// ContinueResponse continues loading of the paused response, optionally
// modifying the response headers. If either responseCode or headers are
// modified, all of them must be present.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Fetch#method-continueResponse
var ContinueResponse = cdp.Command[ContinueResponseParams, cdp.Empty]{Method: CommandContinueResponse}

// GetResponseBodyParams are the parameters of the command
// Fetch.getResponseBody.
type GetResponseBodyParams struct {
	RequestID RequestID `json:"requestId"` // Identifier for the intercepted request to get body for.
}

// GetResponseBodyResult is the result of the command Fetch.getResponseBody.
type GetResponseBodyResult struct {
	Body          []byte `json:"body,omitempty,omitzero"` // Response body.
	Base64encoded bool   `json:"base64Encoded"`           // True, if content was sent as base64.
}

// UnmarshalJSON decodes the value. The browser sends body as text, or as
// base64 when r.Base64encoded, and Body holds the decoded bytes.
func (r *GetResponseBodyResult) UnmarshalJSON(buf []byte) error {
	type plain GetResponseBodyResult
	aux := struct {
		*plain
		Body string `json:"body"`
	}{plain: (*plain)(r)}
	if err := jsonv2.Unmarshal(buf, &aux); err != nil {
		return err
	}
	if r.Base64encoded {
		b, err := base64.StdEncoding.DecodeString(aux.Body)
		if err != nil {
			return fmt.Errorf("decoding body: %w", err)
		}
		r.Body = b
		return nil
	}
	r.Body = []byte(aux.Body)
	return nil
}

// GetResponseBody causes the body of the response to be received from the
// server and returned as a single string. May only be issued for a request that
// is paused in the Response stage and is mutually exclusive with
// takeResponseBodyForInterceptionAsStream. Calling other methods that affect
// the request or disabling fetch domain before body is received results in an
// undefined behavior. Note that the response body is not available for
// redirects. Requests paused in the _redirect received_ state may be
// differentiated by responseCode and presence of location response header, see
// comments to requestPaused for details.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Fetch#method-getResponseBody
var GetResponseBody = cdp.Command[GetResponseBodyParams, GetResponseBodyResult]{Method: CommandGetResponseBody}

// TakeResponseBodyAsStreamParams are the parameters of the command
// Fetch.takeResponseBodyAsStream.
type TakeResponseBodyAsStreamParams struct {
	RequestID RequestID `json:"requestId"`
}

// TakeResponseBodyAsStreamResult is the result of the command
// Fetch.takeResponseBodyAsStream.
type TakeResponseBodyAsStreamResult struct {
	Stream io.StreamHandle `json:"stream,omitempty,omitzero"`
}

// TakeResponseBodyAsStream returns a handle to the stream representing the
// response body. The request must be paused in the HeadersReceived stage. Note
// that after this command the request can't be continued as is -- client either
// needs to cancel it or to provide the response body. The stream only supports
// sequential read, IO.read will fail if the position is specified. This method
// is mutually exclusive with getResponseBody. Calling other methods that affect
// the request or disabling fetch domain before body is received results in an
// undefined behavior.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Fetch#method-takeResponseBodyAsStream
var TakeResponseBodyAsStream = cdp.Command[TakeResponseBodyAsStreamParams, TakeResponseBodyAsStreamResult]{Method: CommandTakeResponseBodyAsStream}

// RequestPaused issued when the domain is enabled and the request URL
// matches the specified filter. The request is paused until the client responds
// with one of continueRequest, failRequest or fulfillRequest. The stage of the
// request can be determined by presence of responseErrorReason and
// responseStatusCode -- the request is at the response stage if either of these
// fields is present and in the request stage otherwise. Redirect responses and
// subsequent requests are reported similarly to regular responses and requests.
// Redirect responses may be distinguished by the value of responseStatusCode
// (which is one of 301, 302, 303, 307, 308) along with presence of the location
// header. Requests resulting from a redirect will have redirectedRequestId
// field set.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Fetch#event-requestPaused
var RequestPaused = cdp.Event[EventRequestPaused]{Method: "Fetch.requestPaused"}

// AuthRequired issued when the domain is enabled with handleAuthRequests set
// to true. The request is paused until client responds with continueWithAuth.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Fetch#event-authRequired
var AuthRequired = cdp.Event[EventAuthRequired]{Method: "Fetch.authRequired"}

// Command names.
const (
	CommandDisable                  = "Fetch.disable"
	CommandEnable                   = "Fetch.enable"
	CommandFailRequest              = "Fetch.failRequest"
	CommandFulfillRequest           = "Fetch.fulfillRequest"
	CommandContinueRequest          = "Fetch.continueRequest"
	CommandContinueWithAuth         = "Fetch.continueWithAuth"
	CommandContinueResponse         = "Fetch.continueResponse"
	CommandGetResponseBody          = "Fetch.getResponseBody"
	CommandTakeResponseBodyAsStream = "Fetch.takeResponseBodyAsStream"
)
