// Code generated by pdlgen. DO NOT EDIT.

// Package input provides the Chrome DevTools Protocol
// commands, types, and events for the Input domain.
//
// Generated by the pdlgen command.
package input

import (
	"github.com/chromedp/cdproto/cdp"
)

// DispatchDragEventParams are the parameters of the command
// Input.dispatchDragEvent.
type DispatchDragEventParams struct {
	Type      DispatchDragEventType `json:"type"` // Type of the drag event.
	X         float64               `json:"x"`    // X coordinate of the event relative to the main frame's viewport in CSS pixels.
	Y         float64               `json:"y"`    // Y coordinate of the event relative to the main frame's viewport in CSS pixels. 0 refers to the top of the viewport and Y increases as it proceeds towards the bottom of the viewport.
	Data      *DragData             `json:"data"`
	Modifiers int64                 `json:"modifiers,omitempty,omitzero"` // Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8 (default: 0).
}

// DispatchDragEvent dispatches a drag event into the page.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Input#method-dispatchDragEvent
var DispatchDragEvent = cdp.Command[DispatchDragEventParams, cdp.Empty]{Method: CommandDispatchDragEvent}

// DispatchKeyEventParams are the parameters of the command
// Input.dispatchKeyEvent.
type DispatchKeyEventParams struct {
	Type                  DispatchKeyEventType `json:"type"`                                     // Type of the key event.
	Modifiers             int64                `json:"modifiers,omitempty,omitzero"`             // Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8 (default: 0).
	Timestamp             TimeSinceEpoch       `json:"timestamp,omitempty,omitzero"`             // Time at which the event occurred.
	Text                  string               `json:"text,omitempty,omitzero"`                  // Text as generated by processing a virtual key code with a keyboard layout. Not needed for for keyUp and rawKeyDown events (default: "")
	UnmodifiedText        string               `json:"unmodifiedText,omitempty,omitzero"`        // Text that would have been generated by the keyboard if no modifiers were pressed (except for shift). Useful for shortcut (accelerator) key handling (default: "").
	KeyIdentifier         string               `json:"keyIdentifier,omitempty,omitzero"`         // Unique key identifier (e.g., 'U+0041') (default: "").
	Code                  string               `json:"code,omitempty,omitzero"`                  // Unique DOM defined string value for each physical key (e.g., 'KeyA') (default: "").
	Key                   string               `json:"key,omitempty,omitzero"`                   // Unique DOM defined string value describing the meaning of the key in the context of active modifiers, keyboard layout, etc (e.g., 'AltGr') (default: "").
	WindowsVirtualKeyCode int64                `json:"windowsVirtualKeyCode,omitempty,omitzero"` // Windows virtual key code (default: 0).
	NativeVirtualKeyCode  int64                `json:"nativeVirtualKeyCode,omitempty,omitzero"`  // Native virtual key code (default: 0).
	AutoRepeat            *bool                `json:"autoRepeat,omitempty,omitzero"`            // Whether the event was generated from auto repeat (default: false).
	IsKeypad              *bool                `json:"isKeypad,omitempty,omitzero"`              // Whether the event was generated from the keypad (default: false).
	IsSystemKey           *bool                `json:"isSystemKey,omitempty,omitzero"`           // Whether the event was a system key event (default: false).
	Location              int64                `json:"location,omitempty,omitzero"`              // Whether the event was from the left or right side of the keyboard. 1=Left, 2=Right (default: 0).
	Commands              []string             `json:"commands,omitempty,omitzero"`              // Editing commands to send with the key event (e.g., 'selectAll') (default: []). These are related to but not equal the command names used in document.execCommand and NSStandardKeyBindingResponding. See https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/editing/commands/editor_command_names.h for valid command names.
}

// DispatchKeyEvent dispatches a key event to the page.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Input#method-dispatchKeyEvent
var DispatchKeyEvent = cdp.Command[DispatchKeyEventParams, cdp.Empty]{Method: CommandDispatchKeyEvent}

// InsertTextParams are the parameters of the command Input.insertText.
type InsertTextParams struct {
	Text string `json:"text"` // The text to insert.
}

// InsertText this method emulates inserting text that doesn't come from a
// key press, for example an emoji keyboard or an IME.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Input#method-insertText
var InsertText = cdp.Command[InsertTextParams, cdp.Empty]{Method: CommandInsertText}

// ImeSetCompositionParams are the parameters of the command
// Input.imeSetComposition.
type ImeSetCompositionParams struct {
	Text             string `json:"text"`                                // The text to insert
	SelectionStart   int64  `json:"selectionStart"`                      // selection start
	SelectionEnd     int64  `json:"selectionEnd"`                        // selection end
	ReplacementStart *int64 `json:"replacementStart,omitempty,omitzero"` // replacement start
	ReplacementEnd   *int64 `json:"replacementEnd,omitempty,omitzero"`   // replacement end
}

// ImeSetComposition this method sets the current candidate text for IME. Use
// imeCommitComposition to commit the final text. Use imeSetComposition with
// empty string as text to cancel composition.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Input#method-imeSetComposition
var ImeSetComposition = cdp.Command[ImeSetCompositionParams, cdp.Empty]{Method: CommandImeSetComposition}

// DispatchMouseEventParams are the parameters of the command
// Input.dispatchMouseEvent.
type DispatchMouseEventParams struct {
	Type               DispatchMouseEventType        `json:"type"`                                  // Type of the mouse event.
	X                  float64                       `json:"x"`                                     // X coordinate of the event relative to the main frame's viewport in CSS pixels.
	Y                  float64                       `json:"y"`                                     // Y coordinate of the event relative to the main frame's viewport in CSS pixels. 0 refers to the top of the viewport and Y increases as it proceeds towards the bottom of the viewport.
	Modifiers          int64                         `json:"modifiers,omitempty,omitzero"`          // Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8 (default: 0).
	Timestamp          TimeSinceEpoch                `json:"timestamp,omitempty,omitzero"`          // Time at which the event occurred.
	Button             MouseButton                   `json:"button,omitempty,omitzero"`             // Mouse button (default: "none").
	Buttons            int64                         `json:"buttons,omitempty,omitzero"`            // A number indicating which buttons are pressed on the mouse when a mouse event is triggered. Left=1, Right=2, Middle=4, Back=8, Forward=16, None=0.
	ClickCount         int64                         `json:"clickCount,omitempty,omitzero"`         // Number of times the mouse button was clicked (default: 0).
	Force              float64                       `json:"force,omitempty,omitzero"`              // The normalized pressure, which has a range of [0,1] (default: 0).
	TangentialPressure float64                       `json:"tangentialPressure,omitempty,omitzero"` // The normalized tangential pressure, which has a range of [-1,1] (default: 0).
	TiltX              float64                       `json:"tiltX,omitempty,omitzero"`              // The plane angle between the Y-Z plane and the plane containing both the stylus axis and the Y axis, in degrees of the range [-90,90], a positive tiltX is to the right (default: 0).
	TiltY              float64                       `json:"tiltY,omitempty,omitzero"`              // The plane angle between the X-Z plane and the plane containing both the stylus axis and the X axis, in degrees of the range [-90,90], a positive tiltY is towards the user (default: 0).
	Twist              int64                         `json:"twist,omitempty,omitzero"`              // The clockwise rotation of a pen stylus around its own major axis, in degrees in the range [0,359] (default: 0).
	DeltaX             float64                       `json:"deltaX,omitempty,omitzero"`             // X delta in CSS pixels for mouse wheel event (default: 0).
	DeltaY             float64                       `json:"deltaY,omitempty,omitzero"`             // Y delta in CSS pixels for mouse wheel event (default: 0).
	PointerType        DispatchMouseEventPointerType `json:"pointerType,omitempty,omitzero"`        // Pointer type (default: "mouse").
}

// DispatchMouseEvent dispatches a mouse event to the page.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Input#method-dispatchMouseEvent
var DispatchMouseEvent = cdp.Command[DispatchMouseEventParams, cdp.Empty]{Method: CommandDispatchMouseEvent}

// DispatchTouchEventParams are the parameters of the command
// Input.dispatchTouchEvent.
type DispatchTouchEventParams struct {
	Type        DispatchTouchEventType `json:"type"`                         // Type of the touch event. TouchEnd and TouchCancel must not contain any touch points, while TouchStart and TouchMove must contains at least one.
	TouchPoints []*TouchPoint          `json:"touchPoints"`                  // Active touch points on the touch device. One event per any changed point (compared to previous touch event in a sequence) is generated, emulating pressing/moving/releasing points one by one.
	Modifiers   int64                  `json:"modifiers,omitempty,omitzero"` // Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8 (default: 0).
	Timestamp   TimeSinceEpoch         `json:"timestamp,omitempty,omitzero"` // Time at which the event occurred.
}

// DispatchTouchEvent dispatches a touch event to the page.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Input#method-dispatchTouchEvent
var DispatchTouchEvent = cdp.Command[DispatchTouchEventParams, cdp.Empty]{Method: CommandDispatchTouchEvent}

// CancelDragging cancels any active dragging in the page.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Input#method-cancelDragging
var CancelDragging = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandCancelDragging}

// EmulateTouchFromMouseEventParams are the parameters of the command
// Input.emulateTouchFromMouseEvent.
type EmulateTouchFromMouseEventParams struct {
	Type       EmulateTouchFromMouseEventType `json:"type"`                          // Type of the mouse event.
	X          int64                          `json:"x"`                             // X coordinate of the mouse pointer in DIP.
	Y          int64                          `json:"y"`                             // Y coordinate of the mouse pointer in DIP.
	Button     MouseButton                    `json:"button"`                        // Mouse button. Only "none", "left", "right" are supported.
	Timestamp  TimeSinceEpoch                 `json:"timestamp,omitempty,omitzero"`  // Time at which the event occurred (default: current time).
	DeltaX     float64                        `json:"deltaX,omitempty,omitzero"`     // X delta in DIP for mouse wheel event (default: 0).
	DeltaY     float64                        `json:"deltaY,omitempty,omitzero"`     // Y delta in DIP for mouse wheel event (default: 0).
	Modifiers  int64                          `json:"modifiers,omitempty,omitzero"`  // Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8 (default: 0).
	ClickCount int64                          `json:"clickCount,omitempty,omitzero"` // Number of times the mouse button was clicked (default: 0).
}

// EmulateTouchFromMouseEvent emulates touch event from the mouse event
// parameters.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Input#method-emulateTouchFromMouseEvent
var EmulateTouchFromMouseEvent = cdp.Command[EmulateTouchFromMouseEventParams, cdp.Empty]{Method: CommandEmulateTouchFromMouseEvent}

// SetIgnoreInputEventsParams are the parameters of the command
// Input.setIgnoreInputEvents.
type SetIgnoreInputEventsParams struct {
	Ignore bool `json:"ignore"` // Ignores input events processing when set to true.
}

// SetIgnoreInputEvents ignores input events (useful while auditing page).
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Input#method-setIgnoreInputEvents
var SetIgnoreInputEvents = cdp.Command[SetIgnoreInputEventsParams, cdp.Empty]{Method: CommandSetIgnoreInputEvents}

// SetInterceptDragsParams are the parameters of the command
// Input.setInterceptDrags.
type SetInterceptDragsParams struct {
	Enabled bool `json:"enabled"`
}

// SetInterceptDrags prevents default drag and drop behavior and instead
// emits Input.dragIntercepted events. Drag and drop behavior can be directly
// controlled via Input.dispatchDragEvent.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Input#method-setInterceptDrags
var SetInterceptDrags = cdp.Command[SetInterceptDragsParams, cdp.Empty]{Method: CommandSetInterceptDrags}

// SynthesizePinchGestureParams are the parameters of the command
// Input.synthesizePinchGesture.
type SynthesizePinchGestureParams struct {
	X                 float64           `json:"x"`                                    // X coordinate of the start of the gesture in CSS pixels.
	Y                 float64           `json:"y"`                                    // Y coordinate of the start of the gesture in CSS pixels.
	ScaleFactor       float64           `json:"scaleFactor"`                          // Relative scale factor after zooming (>1.0 zooms in, <1.0 zooms out).
	RelativeSpeed     int64             `json:"relativeSpeed,omitempty,omitzero"`     // Relative pointer speed in pixels per second (default: 800).
	GestureSourceType GestureSourceType `json:"gestureSourceType,omitempty,omitzero"` // Which type of input events to be generated (default: 'default', which queries the platform for the preferred input type).
}

// SynthesizePinchGesture synthesizes a pinch gesture over a time period by
// issuing appropriate touch events.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Input#method-synthesizePinchGesture
var SynthesizePinchGesture = cdp.Command[SynthesizePinchGestureParams, cdp.Empty]{Method: CommandSynthesizePinchGesture}

// SynthesizeScrollGestureParams are the parameters of the command
// Input.synthesizeScrollGesture.
type SynthesizeScrollGestureParams struct {
	X                     float64           `json:"x"`                                        // X coordinate of the start of the gesture in CSS pixels.
	Y                     float64           `json:"y"`                                        // Y coordinate of the start of the gesture in CSS pixels.
	XDistance             float64           `json:"xDistance,omitempty,omitzero"`             // The distance to scroll along the X axis (positive to scroll left).
	YDistance             float64           `json:"yDistance,omitempty,omitzero"`             // The distance to scroll along the Y axis (positive to scroll up).
	XOverscroll           float64           `json:"xOverscroll,omitempty,omitzero"`           // The number of additional pixels to scroll back along the X axis, in addition to the given distance.
	YOverscroll           float64           `json:"yOverscroll,omitempty,omitzero"`           // The number of additional pixels to scroll back along the Y axis, in addition to the given distance.
	PreventFling          *bool             `json:"preventFling,omitempty,omitzero"`          // Prevent fling (default: true).
	Speed                 int64             `json:"speed,omitempty,omitzero"`                 // Swipe speed in pixels per second (default: 800).
	GestureSourceType     GestureSourceType `json:"gestureSourceType,omitempty,omitzero"`     // Which type of input events to be generated (default: 'default', which queries the platform for the preferred input type).
	RepeatCount           int64             `json:"repeatCount,omitempty,omitzero"`           // The number of times to repeat the gesture (default: 0).
	RepeatDelayMs         *int64            `json:"repeatDelayMs,omitempty,omitzero"`         // The number of milliseconds delay between each repeat. (default: 250).
	InteractionMarkerName string            `json:"interactionMarkerName,omitempty,omitzero"` // The name of the interaction markers to generate, if not empty (default: "").
}

// SynthesizeScrollGesture synthesizes a scroll gesture over a time period by
// issuing appropriate touch events.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Input#method-synthesizeScrollGesture
var SynthesizeScrollGesture = cdp.Command[SynthesizeScrollGestureParams, cdp.Empty]{Method: CommandSynthesizeScrollGesture}

// SynthesizeTapGestureParams are the parameters of the command
// Input.synthesizeTapGesture.
type SynthesizeTapGestureParams struct {
	X                 float64           `json:"x"`                                    // X coordinate of the start of the gesture in CSS pixels.
	Y                 float64           `json:"y"`                                    // Y coordinate of the start of the gesture in CSS pixels.
	Duration          *int64            `json:"duration,omitempty,omitzero"`          // Duration between touchdown and touchup events in ms (default: 50).
	TapCount          int64             `json:"tapCount,omitempty,omitzero"`          // Number of times to perform the tap (e.g. 2 for double tap, default: 1).
	GestureSourceType GestureSourceType `json:"gestureSourceType,omitempty,omitzero"` // Which type of input events to be generated (default: 'default', which queries the platform for the preferred input type).
}

// SynthesizeTapGesture synthesizes a tap gesture over a time period by
// issuing appropriate touch events.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Input#method-synthesizeTapGesture
var SynthesizeTapGesture = cdp.Command[SynthesizeTapGestureParams, cdp.Empty]{Method: CommandSynthesizeTapGesture}

// DragIntercepted emitted only when Input.setInterceptDrags is enabled. Use
// this data with Input.dispatchDragEvent to restore normal drag and drop
// behavior.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Input#event-dragIntercepted
var DragIntercepted = cdp.Event[EventDragIntercepted]{Method: "Input.dragIntercepted"}

// Command names.
const (
	CommandDispatchDragEvent          = "Input.dispatchDragEvent"
	CommandDispatchKeyEvent           = "Input.dispatchKeyEvent"
	CommandInsertText                 = "Input.insertText"
	CommandImeSetComposition          = "Input.imeSetComposition"
	CommandDispatchMouseEvent         = "Input.dispatchMouseEvent"
	CommandDispatchTouchEvent         = "Input.dispatchTouchEvent"
	CommandCancelDragging             = "Input.cancelDragging"
	CommandEmulateTouchFromMouseEvent = "Input.emulateTouchFromMouseEvent"
	CommandSetIgnoreInputEvents       = "Input.setIgnoreInputEvents"
	CommandSetInterceptDrags          = "Input.setInterceptDrags"
	CommandSynthesizePinchGesture     = "Input.synthesizePinchGesture"
	CommandSynthesizeScrollGesture    = "Input.synthesizeScrollGesture"
	CommandSynthesizeTapGesture       = "Input.synthesizeTapGesture"
)
