package input

import (
	"fmt"
	"strings"
)

// Code generated by cdproto-gen. DO NOT EDIT.

// TouchPoint [no description].
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Input#type-TouchPoint
type TouchPoint struct {
	X                  float64 `json:"x"`                                     // X coordinate of the event relative to the main frame's viewport in CSS pixels.
	Y                  float64 `json:"y"`                                     // Y coordinate of the event relative to the main frame's viewport in CSS pixels. 0 refers to the top of the viewport and Y increases as it proceeds towards the bottom of the viewport.
	RadiusX            float64 `json:"radiusX,omitempty,omitzero"`            // X radius of the touch area (default: 1.0).
	RadiusY            float64 `json:"radiusY,omitempty,omitzero"`            // Y radius of the touch area (default: 1.0).
	RotationAngle      float64 `json:"rotationAngle,omitempty,omitzero"`      // Rotation angle (default: 0.0).
	Force              float64 `json:"force,omitempty,omitzero"`              // Force (default: 1.0).
	TangentialPressure float64 `json:"tangentialPressure,omitempty,omitzero"` // The normalized tangential pressure, which has a range of [-1,1] (default: 0).
	TiltX              float64 `json:"tiltX,omitempty,omitzero"`              // The plane angle between the Y-Z plane and the plane containing both the stylus axis and the Y axis, in degrees of the range [-90,90], a positive tiltX is to the right (default: 0)
	TiltY              float64 `json:"tiltY,omitempty,omitzero"`              // The plane angle between the X-Z plane and the plane containing both the stylus axis and the X axis, in degrees of the range [-90,90], a positive tiltY is towards the user (default: 0).
	Twist              int64   `json:"twist,omitempty,omitzero"`              // The clockwise rotation of a pen stylus around its own major axis, in degrees in the range [0,359] (default: 0).
	ID                 float64 `json:"id,omitempty,omitzero"`                 // Identifier used to track touch sources between events, must be unique within an event.
}

// GestureSourceType [no description].
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Input#type-GestureSourceType
type GestureSourceType string

// String returns the GestureSourceType as string value.
func (t GestureSourceType) String() string {
	return string(t)
}

// GestureSourceType values.
const (
	GestureSourceTypeDefault GestureSourceType = "default"
	GestureSourceTypeTouch   GestureSourceType = "touch"
	GestureSourceTypeMouse   GestureSourceType = "mouse"
)

// UnmarshalJSON satisfies [json.Unmarshaler].
func (t *GestureSourceType) UnmarshalJSON(buf []byte) error {
	s := string(buf)
	s = strings.TrimSuffix(strings.TrimPrefix(s, `"`), `"`)

	switch GestureSourceType(s) {
	case GestureSourceTypeDefault:
		*t = GestureSourceTypeDefault
	case GestureSourceTypeTouch:
		*t = GestureSourceTypeTouch
	case GestureSourceTypeMouse:
		*t = GestureSourceTypeMouse
	default:
		return fmt.Errorf("unknown GestureSourceType value: %v", s)
	}
	return nil
}

// MouseButton [no description].
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Input#type-MouseButton
type MouseButton string

// String returns the MouseButton as string value.
func (t MouseButton) String() string {
	return string(t)
}

// MouseButton values.
const (
	MouseButtonNone    MouseButton = "none"
	MouseButtonLeft    MouseButton = "left"
	MouseButtonMiddle  MouseButton = "middle"
	MouseButtonRight   MouseButton = "right"
	MouseButtonBack    MouseButton = "back"
	MouseButtonForward MouseButton = "forward"
)

// UnmarshalJSON satisfies [json.Unmarshaler].
func (t *MouseButton) UnmarshalJSON(buf []byte) error {
	s := string(buf)
	s = strings.TrimSuffix(strings.TrimPrefix(s, `"`), `"`)

	switch MouseButton(s) {
	case MouseButtonNone:
		*t = MouseButtonNone
	case MouseButtonLeft:
		*t = MouseButtonLeft
	case MouseButtonMiddle:
		*t = MouseButtonMiddle
	case MouseButtonRight:
		*t = MouseButtonRight
	case MouseButtonBack:
		*t = MouseButtonBack
	case MouseButtonForward:
		*t = MouseButtonForward
	default:
		return fmt.Errorf("unknown MouseButton value: %v", s)
	}
	return nil
}

// TimeSinceEpoch UTC time in seconds, counted from January 1, 1970.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Input#type-TimeSinceEpoch
type TimeSinceEpoch float64

// Float64 returns the TimeSinceEpoch as float64 value.
func (t TimeSinceEpoch) Float64() float64 {
	return float64(t)
}

// DragDataItem [no description].
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Input#type-DragDataItem
type DragDataItem struct {
	MimeType string `json:"mimeType"`                   // Mime type of the dragged data.
	Data     string `json:"data"`                       // Depending of the value of mimeType, it contains the dragged link, text, HTML markup or any other data.
	Title    string `json:"title,omitempty,omitzero"`   // Title associated with a link. Only valid when mimeType == "text/uri-list".
	BaseURL  string `json:"baseURL,omitempty,omitzero"` // Stores the base URL for the contained markup. Only valid when mimeType == "text/html".
}

// DragData [no description].
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Input#type-DragData
type DragData struct {
	Items              []*DragDataItem `json:"items"`
	Files              []string        `json:"files,omitempty,omitzero"` // List of filenames that should be included when dropping
	DragOperationsMask int64           `json:"dragOperationsMask"`       // Bit field representing allowed drag operations. Copy = 1, Link = 2, Move = 16
}
