// Code generated by pdlgen. DO NOT EDIT.

//go:build !(go1.27 || goexperiment.jsonv2) || cdproto_jsoncompat

package jsonv2

import (
	v2 "github.com/go-json-experiment/json"
	"github.com/go-json-experiment/json/jsontext"
)

// This file defines the JSON layer with the module
// github.com/go-json-experiment/json. The file json_std.go defines the same
// names with the packages of the standard library.

// Value is a raw JSON value.
type Value = jsontext.Value

// Options is a set of options for the JSON encoder and decoder.
type Options = v2.Options

// Decoder reads a stream of JSON values.
type Decoder = jsontext.Decoder

// Encoder writes a stream of JSON values.
type Encoder = jsontext.Encoder

// SyntacticError is the error for JSON text that is not valid.
type SyntacticError = jsontext.SyntacticError

// Marshal encodes in as JSON with the options.
func Marshal(in any, opts ...Options) ([]byte, error) {
	return v2.Marshal(in, opts...)
}

// Unmarshal decodes the JSON text in into out with the options.
func Unmarshal(in []byte, out any, opts ...Options) error {
	return v2.Unmarshal(in, out, opts...)
}

// MarshalEncode encodes in as JSON to the encoder with the options.
func MarshalEncode(out *Encoder, in any, opts ...Options) error {
	return v2.MarshalEncode(out, in, opts...)
}

// UnmarshalDecode decodes the next JSON value of the decoder into out with the
// options.
func UnmarshalDecode(in *Decoder, out any, opts ...Options) error {
	return v2.UnmarshalDecode(in, out, opts...)
}

// JoinOptions combines the options into one set. An option that comes later
// replaces an option that comes earlier.
func JoinOptions(srcs ...Options) Options {
	return v2.JoinOptions(srcs...)
}

// DefaultOptionsV2 returns the options that define the behavior of version 2 of
// the JSON package.
func DefaultOptionsV2() Options {
	return v2.DefaultOptionsV2()
}

// AllowInvalidUTF8 returns the option that lets the encoder and the decoder
// accept text that is not valid UTF-8.
func AllowInvalidUTF8(v bool) Options {
	return jsontext.AllowInvalidUTF8(v)
}
