// Code generated by pdlgen. DO NOT EDIT.

// Package tethering provides the Chrome DevTools Protocol
// commands, types, and events for the Tethering domain.
//
// The Tethering domain defines methods and events for browser port binding.
//
// Generated by the pdlgen command.
package tethering

import (
	"github.com/chromedp/cdproto/cdp"
)

// BindParams are the parameters of the command Tethering.bind.
type BindParams struct {
	Port int64 `json:"port"` // Port number to bind.
}

// Bind request browser port binding.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Tethering#method-bind
var Bind = cdp.Command[BindParams, cdp.Empty]{Method: CommandBind}

// UnbindParams are the parameters of the command Tethering.unbind.
type UnbindParams struct {
	Port int64 `json:"port"` // Port number to unbind.
}

// Unbind request browser port unbinding.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Tethering#method-unbind
var Unbind = cdp.Command[UnbindParams, cdp.Empty]{Method: CommandUnbind}

// Accepted informs that port was successfully bound and got a specified
// connection id.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Tethering#event-accepted
var Accepted = cdp.Event[EventAccepted]{Method: "Tethering.accepted"}

// Command names.
const (
	CommandBind   = "Tethering.bind"
	CommandUnbind = "Tethering.unbind"
)
