// Code generated by pdlgen. DO NOT EDIT.

// Package profiler provides the Chrome DevTools Protocol
// commands, types, and events for the Profiler domain.
//
// Generated by the pdlgen command.
package profiler

import (
	"github.com/chromedp/cdproto/cdp"
)

// Disable [no description].
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Profiler#method-disable
var Disable = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandDisable}

// Enable [no description].
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Profiler#method-enable
var Enable = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandEnable}

// GetBestEffortCoverageResult is the result of the command
// Profiler.getBestEffortCoverage.
type GetBestEffortCoverageResult struct {
	Result []*ScriptCoverage `json:"result,omitempty,omitzero"` // Coverage data for the current isolate.
}

// GetBestEffortCoverage collect coverage data for the current isolate. The
// coverage data may be incomplete due to garbage collection.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Profiler#method-getBestEffortCoverage
var GetBestEffortCoverage = cdp.Command[cdp.Empty, GetBestEffortCoverageResult]{Method: CommandGetBestEffortCoverage}

// SetSamplingIntervalParams are the parameters of the command
// Profiler.setSamplingInterval.
type SetSamplingIntervalParams struct {
	Interval int64 `json:"interval"` // New sampling interval in microseconds.
}

// SetSamplingInterval changes CPU profiler sampling interval. Must be called
// before CPU profiles recording started.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Profiler#method-setSamplingInterval
var SetSamplingInterval = cdp.Command[SetSamplingIntervalParams, cdp.Empty]{Method: CommandSetSamplingInterval}

// Start [no description].
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Profiler#method-start
var Start = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandStart}

// StartPreciseCoverageParams are the parameters of the command
// Profiler.startPreciseCoverage.
type StartPreciseCoverageParams struct {
	CallCount             *bool `json:"callCount,omitempty,omitzero"`             // Collect accurate call counts beyond simple 'covered' or 'not covered'.
	Detailed              *bool `json:"detailed,omitempty,omitzero"`              // Collect block-based coverage.
	AllowTriggeredUpdates *bool `json:"allowTriggeredUpdates,omitempty,omitzero"` // Allow the backend to send updates on its own initiative
}

// StartPreciseCoverageResult is the result of the command
// Profiler.startPreciseCoverage.
type StartPreciseCoverageResult struct {
	Timestamp float64 `json:"timestamp,omitempty,omitzero"` // Monotonically increasing time (in seconds) when the coverage update was taken in the backend.
}

// StartPreciseCoverage enable precise code coverage. Coverage data for
// JavaScript executed before enabling precise code coverage may be incomplete.
// Enabling prevents running optimized code and resets execution counters.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Profiler#method-startPreciseCoverage
var StartPreciseCoverage = cdp.Command[StartPreciseCoverageParams, StartPreciseCoverageResult]{Method: CommandStartPreciseCoverage}

// StopResult is the result of the command Profiler.stop.
type StopResult struct {
	Profile *Profile `json:"profile,omitempty,omitzero"` // Recorded profile.
}

// Stop [no description].
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Profiler#method-stop
var Stop = cdp.Command[cdp.Empty, StopResult]{Method: CommandStop}

// StopPreciseCoverage disable precise code coverage. Disabling releases
// unnecessary execution count records and allows executing optimized code.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Profiler#method-stopPreciseCoverage
var StopPreciseCoverage = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandStopPreciseCoverage}

// TakePreciseCoverageResult is the result of the command
// Profiler.takePreciseCoverage.
type TakePreciseCoverageResult struct {
	Result    []*ScriptCoverage `json:"result,omitempty,omitzero"`    // Coverage data for the current isolate.
	Timestamp float64           `json:"timestamp,omitempty,omitzero"` // Monotonically increasing time (in seconds) when the coverage update was taken in the backend.
}

// TakePreciseCoverage collect coverage data for the current isolate, and
// resets execution counters. Precise code coverage needs to have started.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Profiler#method-takePreciseCoverage
var TakePreciseCoverage = cdp.Command[cdp.Empty, TakePreciseCoverageResult]{Method: CommandTakePreciseCoverage}

// ConsoleProfileFinished [no description].
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Profiler#event-consoleProfileFinished
var ConsoleProfileFinished = cdp.Event[EventConsoleProfileFinished]{Method: "Profiler.consoleProfileFinished"}

// ConsoleProfileStarted sent when new profile recording is started using
// console.profile() call.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Profiler#event-consoleProfileStarted
var ConsoleProfileStarted = cdp.Event[EventConsoleProfileStarted]{Method: "Profiler.consoleProfileStarted"}

// PreciseCoverageDeltaUpdate reports coverage delta since the last poll
// (either from an event like this, or from takePreciseCoverage for the current
// isolate. May only be sent if precise code coverage has been started. This
// event can be trigged by the embedder to, for example, trigger collection of
// coverage data immediately at a certain point in time.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Profiler#event-preciseCoverageDeltaUpdate
var PreciseCoverageDeltaUpdate = cdp.Event[EventPreciseCoverageDeltaUpdate]{Method: "Profiler.preciseCoverageDeltaUpdate"}

// Command names.
const (
	CommandDisable               = "Profiler.disable"
	CommandEnable                = "Profiler.enable"
	CommandGetBestEffortCoverage = "Profiler.getBestEffortCoverage"
	CommandSetSamplingInterval   = "Profiler.setSamplingInterval"
	CommandStart                 = "Profiler.start"
	CommandStartPreciseCoverage  = "Profiler.startPreciseCoverage"
	CommandStop                  = "Profiler.stop"
	CommandStopPreciseCoverage   = "Profiler.stopPreciseCoverage"
	CommandTakePreciseCoverage   = "Profiler.takePreciseCoverage"
)
