package systeminfo

// Code generated by cdproto-gen. DO NOT EDIT.

import (
	"errors"

	"github.com/mailru/easyjson"
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

// GPUDevice describes a single graphics processor (GPU).
type GPUDevice struct {
	VendorID     float64 `json:"vendorId"`     // PCI ID of the GPU vendor, if available; 0 otherwise.
	DeviceID     float64 `json:"deviceId"`     // PCI ID of the GPU device, if available; 0 otherwise.
	VendorString string  `json:"vendorString"` // String description of the GPU vendor, if the PCI ID is not available.
	DeviceString string  `json:"deviceString"` // String description of the GPU device, if the PCI ID is not available.
}

// GPUInfo provides information about the GPU(s) on the system.
type GPUInfo struct {
	Devices              []*GPUDevice        `json:"devices"` // The graphics devices on the system. Element 0 is the primary GPU.
	AuxAttributes        easyjson.RawMessage `json:"auxAttributes,omitempty"`
	FeatureStatus        easyjson.RawMessage `json:"featureStatus,omitempty"`
	DriverBugWorkarounds []string            `json:"driverBugWorkarounds"` // An optional array of GPU driver bug workarounds.
}

// ProcessType specifies process type.
type ProcessType string

// String returns the ProcessType as string value.
func (t ProcessType) String() string {
	return string(t)
}

// ProcessType values.
const (
	ProcessTypeBrowser  ProcessType = "browser"
	ProcessTypeRenderer ProcessType = "renderer"
)

// MarshalEasyJSON satisfies easyjson.Marshaler.
func (t ProcessType) MarshalEasyJSON(out *jwriter.Writer) {
	out.String(string(t))
}

// MarshalJSON satisfies json.Marshaler.
func (t ProcessType) MarshalJSON() ([]byte, error) {
	return easyjson.Marshal(t)
}

// UnmarshalEasyJSON satisfies easyjson.Unmarshaler.
func (t *ProcessType) UnmarshalEasyJSON(in *jlexer.Lexer) {
	switch ProcessType(in.String()) {
	case ProcessTypeBrowser:
		*t = ProcessTypeBrowser
	case ProcessTypeRenderer:
		*t = ProcessTypeRenderer

	default:
		in.AddError(errors.New("unknown ProcessType value"))
	}
}

// UnmarshalJSON satisfies json.Unmarshaler.
func (t *ProcessType) UnmarshalJSON(buf []byte) error {
	return easyjson.Unmarshal(buf, t)
}

// ProcessInfo represents process info.
type ProcessInfo struct {
	Type    ProcessType `json:"type"`    // Specifies process type.
	ID      int64       `json:"id"`      // Specifies process id.
	CPUTime float64     `json:"cpuTime"` // Specifies cumulative CPU usage in seconds across all threads of the process since the process start.
}
