// Code generated by pdlgen. DO NOT EDIT.

// Package headlessexperimental provides the Chrome DevTools Protocol
// commands, types, and events for the HeadlessExperimental domain.
//
// This domain provides experimental commands only supported in headless
// mode.
//
// Generated by the pdlgen command.
package headlessexperimental

import (
	"github.com/chromedp/cdproto/cdp"
)

// BeginFrameParams are the parameters of the command
// HeadlessExperimental.beginFrame.
type BeginFrameParams struct {
	FrameTimeTicks   float64           `json:"frameTimeTicks,omitempty,omitzero"`   // Timestamp of this BeginFrame in Renderer TimeTicks (milliseconds of uptime). If not set, the current time will be used.
	Interval         float64           `json:"interval,omitempty,omitzero"`         // The interval between BeginFrames that is reported to the compositor, in milliseconds. Defaults to a 60 frames/second interval, i.e. about 16.666 milliseconds.
	NoDisplayUpdates *bool             `json:"noDisplayUpdates,omitempty,omitzero"` // Whether updates should not be committed and drawn onto the display. False by default. If true, only side effects of the BeginFrame will be run, such as layout and animations, but any visual updates may not be visible on the display or in screenshots.
	Screenshot       *ScreenshotParams `json:"screenshot,omitempty,omitzero"`       // If set, a screenshot of the frame will be captured and returned in the response. Otherwise, no screenshot will be captured. Note that capturing a screenshot can fail, for example, during renderer initialization. In such a case, no screenshot data will be returned.
}

// BeginFrameResult is the result of the command
// HeadlessExperimental.beginFrame.
type BeginFrameResult struct {
	HasDamage      bool   `json:"hasDamage"`                         // Whether the BeginFrame resulted in damage and, thus, a new frame was committed to the display. Reported for diagnostic uses, may be removed in the future.
	ScreenshotData []byte `json:"screenshotData,omitempty,omitzero"` // Base64-encoded image data of the screenshot, if one was requested and successfully taken.
}

// BeginFrame sends a BeginFrame to the target and returns when the frame was
// completed. Optionally captures a screenshot from the resulting frame.
// Requires that the target was created with enabled BeginFrameControl. Designed
// for use with --run-all-compositor-stages-before-draw, see also
// https://goo.gle/chrome-headless-rendering for more background.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/HeadlessExperimental#method-beginFrame
var BeginFrame = cdp.Command[BeginFrameParams, BeginFrameResult]{Method: CommandBeginFrame}

// Command names.
const (
	CommandBeginFrame = "HeadlessExperimental.beginFrame"
)
