package headlessexperimental

// Code generated by cdproto-gen. DO NOT EDIT.

// ScreenshotParams encoding options for a screenshot.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/HeadlessExperimental#type-ScreenshotParams
type ScreenshotParams struct {
	Format           string `json:"format,omitempty,omitzero"`  // Image compression format (defaults to png).
	Quality          int64  `json:"quality,omitempty,omitzero"` // Compression quality from range [0..100] (jpeg and webp only).
	OptimizeForSpeed bool   `json:"optimizeForSpeed"`           // Optimize image encoding for speed, not for resulting size (defaults to false)
}
