// Code generated by pdlgen. DO NOT EDIT.

// Package smartcardemulation provides the Chrome DevTools Protocol
// commands, types, and events for the SmartCardEmulation domain.
//
// Generated by the pdlgen command.
package smartcardemulation

import (
	"github.com/chromedp/cdproto/cdp"
)

// Enable enables the |SmartCardEmulation| domain.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SmartCardEmulation#method-enable
var Enable = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandEnable}

// Disable disables the |SmartCardEmulation| domain.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SmartCardEmulation#method-disable
var Disable = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandDisable}

// ReportEstablishContextResultParams are the parameters of the command
// SmartCardEmulation.reportEstablishContextResult.
type ReportEstablishContextResultParams struct {
	RequestID string `json:"requestId"`
	ContextID int64  `json:"contextId"`
}

// ReportEstablishContextResult reports the successful result of a
// |SCardEstablishContext| call. This maps to: PC/SC Lite:
// https://pcsclite.apdu.fr/api/group__API.html#gaa1b8970169fd4883a6dc4a8f43f19b67
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardestablishcontext.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SmartCardEmulation#method-reportEstablishContextResult
var ReportEstablishContextResult = cdp.Command[ReportEstablishContextResultParams, cdp.Empty]{Method: CommandReportEstablishContextResult}

// ReportReleaseContextResultParams are the parameters of the command
// SmartCardEmulation.reportReleaseContextResult.
type ReportReleaseContextResultParams struct {
	RequestID string `json:"requestId"`
}

// ReportReleaseContextResult reports the successful result of a
// |SCardReleaseContext| call. This maps to: PC/SC Lite:
// https://pcsclite.apdu.fr/api/group__API.html#ga6aabcba7744c5c9419fdd6404f73a934
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardreleasecontext.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SmartCardEmulation#method-reportReleaseContextResult
var ReportReleaseContextResult = cdp.Command[ReportReleaseContextResultParams, cdp.Empty]{Method: CommandReportReleaseContextResult}

// ReportListReadersResultParams are the parameters of the command
// SmartCardEmulation.reportListReadersResult.
type ReportListReadersResultParams struct {
	RequestID string   `json:"requestId"`
	Readers   []string `json:"readers"`
}

// ReportListReadersResult reports the successful result of a
// |SCardListReaders| call. This maps to: PC/SC Lite:
// https://pcsclite.apdu.fr/api/group__API.html#ga93b07815789b3cf2629d439ecf20f0d9
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardlistreadersa.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SmartCardEmulation#method-reportListReadersResult
var ReportListReadersResult = cdp.Command[ReportListReadersResultParams, cdp.Empty]{Method: CommandReportListReadersResult}

// ReportGetStatusChangeResultParams are the parameters of the command
// SmartCardEmulation.reportGetStatusChangeResult.
type ReportGetStatusChangeResultParams struct {
	RequestID    string            `json:"requestId"`
	ReaderStates []*ReaderStateOut `json:"readerStates"`
}

// ReportGetStatusChangeResult reports the successful result of a
// |SCardGetStatusChange| call. This maps to: PC/SC Lite:
// https://pcsclite.apdu.fr/api/group__API.html#ga33247d5d1257d59e55647c3bb717db24
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardgetstatuschangea.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SmartCardEmulation#method-reportGetStatusChangeResult
var ReportGetStatusChangeResult = cdp.Command[ReportGetStatusChangeResultParams, cdp.Empty]{Method: CommandReportGetStatusChangeResult}

// ReportBeginTransactionResultParams are the parameters of the command
// SmartCardEmulation.reportBeginTransactionResult.
type ReportBeginTransactionResultParams struct {
	RequestID string `json:"requestId"`
	Handle    int64  `json:"handle"`
}

// ReportBeginTransactionResult reports the result of a
// |SCardBeginTransaction| call. On success, this creates a new transaction
// object. This maps to: PC/SC Lite:
// https://pcsclite.apdu.fr/api/group__API.html#gaddb835dce01a0da1d6ca02d33ee7d861
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardbegintransaction.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SmartCardEmulation#method-reportBeginTransactionResult
var ReportBeginTransactionResult = cdp.Command[ReportBeginTransactionResultParams, cdp.Empty]{Method: CommandReportBeginTransactionResult}

// ReportPlainResultParams are the parameters of the command
// SmartCardEmulation.reportPlainResult.
type ReportPlainResultParams struct {
	RequestID string `json:"requestId"`
}

// ReportPlainResult reports the successful result of a call that returns
// only a result code. Used for: |SCardCancel|, |SCardDisconnect|,
// |SCardSetAttrib|, |SCardEndTransaction|. This maps to: 1. SCardCancel PC/SC
// Lite:
// https://pcsclite.apdu.fr/api/group__API.html#gaacbbc0c6d6c0cbbeb4f4debf6fbeeee6
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardcancel
// 2. SCardDisconnect PC/SC Lite:
// https://pcsclite.apdu.fr/api/group__API.html#ga4be198045c73ec0deb79e66c0ca1738a
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scarddisconnect
// 3. SCardSetAttrib PC/SC Lite:
// https://pcsclite.apdu.fr/api/group__API.html#ga060f0038a4ddfd5dd2b8fadf3c3a2e4f
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardsetattrib
// 4. SCardEndTransaction PC/SC Lite:
// https://pcsclite.apdu.fr/api/group__API.html#gae8742473b404363e5c587f570d7e2f3b
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardendtransaction.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SmartCardEmulation#method-reportPlainResult
var ReportPlainResult = cdp.Command[ReportPlainResultParams, cdp.Empty]{Method: CommandReportPlainResult}

// ReportConnectResultParams are the parameters of the command
// SmartCardEmulation.reportConnectResult.
type ReportConnectResultParams struct {
	RequestID      string   `json:"requestId"`
	Handle         int64    `json:"handle"`
	ActiveProtocol Protocol `json:"activeProtocol,omitempty,omitzero"`
}

// ReportConnectResult reports the successful result of a |SCardConnect|
// call. This maps to: PC/SC Lite:
// https://pcsclite.apdu.fr/api/group__API.html#ga4e515829752e0a8dbc4d630696a8d6a5
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardconnecta.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SmartCardEmulation#method-reportConnectResult
var ReportConnectResult = cdp.Command[ReportConnectResultParams, cdp.Empty]{Method: CommandReportConnectResult}

// ReportDataResultParams are the parameters of the command
// SmartCardEmulation.reportDataResult.
type ReportDataResultParams struct {
	RequestID string `json:"requestId"`
	Data      []byte `json:"data"`
}

// ReportDataResult reports the successful result of a call that sends back
// data on success. Used for |SCardTransmit|, |SCardControl|, and
// |SCardGetAttrib|. This maps to: 1. SCardTransmit PC/SC Lite:
// https://pcsclite.apdu.fr/api/group__API.html#ga9a2d77242a271310269065e64633ab99
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardtransmit
// 2. SCardControl PC/SC Lite:
// https://pcsclite.apdu.fr/api/group__API.html#gac3454d4657110fd7f753b2d3d8f4e32f
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardcontrol
// 3. SCardGetAttrib PC/SC Lite:
// https://pcsclite.apdu.fr/api/group__API.html#gaacfec51917255b7a25b94c5104961602
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardgetattrib.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SmartCardEmulation#method-reportDataResult
var ReportDataResult = cdp.Command[ReportDataResultParams, cdp.Empty]{Method: CommandReportDataResult}

// ReportStatusResultParams are the parameters of the command
// SmartCardEmulation.reportStatusResult.
type ReportStatusResultParams struct {
	RequestID  string          `json:"requestId"`
	ReaderName string          `json:"readerName"`
	State      ConnectionState `json:"state"`
	Atr        []byte          `json:"atr"`
	Protocol   Protocol        `json:"protocol,omitempty,omitzero"`
}

// ReportStatusResult reports the successful result of a |SCardStatus| call.
// This maps to: PC/SC Lite:
// https://pcsclite.apdu.fr/api/group__API.html#gae49c3c894ad7ac12a5b896bde70d0382
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardstatusa.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SmartCardEmulation#method-reportStatusResult
var ReportStatusResult = cdp.Command[ReportStatusResultParams, cdp.Empty]{Method: CommandReportStatusResult}

// ReportErrorParams are the parameters of the command
// SmartCardEmulation.reportError.
type ReportErrorParams struct {
	RequestID  string     `json:"requestId"`
	ResultCode ResultCode `json:"resultCode"`
}

// ReportError reports an error result for the given request.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SmartCardEmulation#method-reportError
var ReportError = cdp.Command[ReportErrorParams, cdp.Empty]{Method: CommandReportError}

// EstablishContextRequested fired when |SCardEstablishContext| is called.
// This maps to: PC/SC Lite:
// https://pcsclite.apdu.fr/api/group__API.html#gaa1b8970169fd4883a6dc4a8f43f19b67
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardestablishcontext.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SmartCardEmulation#event-establishContextRequested
var EstablishContextRequested = cdp.Event[EventEstablishContextRequested]{Method: "SmartCardEmulation.establishContextRequested"}

// ReleaseContextRequested fired when |SCardReleaseContext| is called. This
// maps to: PC/SC Lite:
// https://pcsclite.apdu.fr/api/group__API.html#ga6aabcba7744c5c9419fdd6404f73a934
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardreleasecontext.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SmartCardEmulation#event-releaseContextRequested
var ReleaseContextRequested = cdp.Event[EventReleaseContextRequested]{Method: "SmartCardEmulation.releaseContextRequested"}

// ListReadersRequested fired when |SCardListReaders| is called. This maps
// to: PC/SC Lite:
// https://pcsclite.apdu.fr/api/group__API.html#ga93b07815789b3cf2629d439ecf20f0d9
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardlistreadersa.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SmartCardEmulation#event-listReadersRequested
var ListReadersRequested = cdp.Event[EventListReadersRequested]{Method: "SmartCardEmulation.listReadersRequested"}

// GetStatusChangeRequested fired when |SCardGetStatusChange| is called.
// Timeout is specified in milliseconds. This maps to: PC/SC Lite:
// https://pcsclite.apdu.fr/api/group__API.html#ga33247d5d1257d59e55647c3bb717db24
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardgetstatuschangea.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SmartCardEmulation#event-getStatusChangeRequested
var GetStatusChangeRequested = cdp.Event[EventGetStatusChangeRequested]{Method: "SmartCardEmulation.getStatusChangeRequested"}

// CancelRequested fired when |SCardCancel| is called. This maps to: PC/SC
// Lite:
// https://pcsclite.apdu.fr/api/group__API.html#gaacbbc0c6d6c0cbbeb4f4debf6fbeeee6
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardcancel.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SmartCardEmulation#event-cancelRequested
var CancelRequested = cdp.Event[EventCancelRequested]{Method: "SmartCardEmulation.cancelRequested"}

// ConnectRequested fired when |SCardConnect| is called. This maps to: PC/SC
// Lite:
// https://pcsclite.apdu.fr/api/group__API.html#ga4e515829752e0a8dbc4d630696a8d6a5
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardconnecta.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SmartCardEmulation#event-connectRequested
var ConnectRequested = cdp.Event[EventConnectRequested]{Method: "SmartCardEmulation.connectRequested"}

// DisconnectRequested fired when |SCardDisconnect| is called. This maps to:
// PC/SC Lite:
// https://pcsclite.apdu.fr/api/group__API.html#ga4be198045c73ec0deb79e66c0ca1738a
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scarddisconnect.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SmartCardEmulation#event-disconnectRequested
var DisconnectRequested = cdp.Event[EventDisconnectRequested]{Method: "SmartCardEmulation.disconnectRequested"}

// TransmitRequested fired when |SCardTransmit| is called. This maps to:
// PC/SC Lite:
// https://pcsclite.apdu.fr/api/group__API.html#ga9a2d77242a271310269065e64633ab99
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardtransmit.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SmartCardEmulation#event-transmitRequested
var TransmitRequested = cdp.Event[EventTransmitRequested]{Method: "SmartCardEmulation.transmitRequested"}

// ControlRequested fired when |SCardControl| is called. This maps to: PC/SC
// Lite:
// https://pcsclite.apdu.fr/api/group__API.html#gac3454d4657110fd7f753b2d3d8f4e32f
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardcontrol.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SmartCardEmulation#event-controlRequested
var ControlRequested = cdp.Event[EventControlRequested]{Method: "SmartCardEmulation.controlRequested"}

// GetAttribRequested fired when |SCardGetAttrib| is called. This maps to:
// PC/SC Lite:
// https://pcsclite.apdu.fr/api/group__API.html#gaacfec51917255b7a25b94c5104961602
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardgetattrib.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SmartCardEmulation#event-getAttribRequested
var GetAttribRequested = cdp.Event[EventGetAttribRequested]{Method: "SmartCardEmulation.getAttribRequested"}

// SetAttribRequested fired when |SCardSetAttrib| is called. This maps to:
// PC/SC Lite:
// https://pcsclite.apdu.fr/api/group__API.html#ga060f0038a4ddfd5dd2b8fadf3c3a2e4f
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardsetattrib.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SmartCardEmulation#event-setAttribRequested
var SetAttribRequested = cdp.Event[EventSetAttribRequested]{Method: "SmartCardEmulation.setAttribRequested"}

// StatusRequested fired when |SCardStatus| is called. This maps to: PC/SC
// Lite:
// https://pcsclite.apdu.fr/api/group__API.html#gae49c3c894ad7ac12a5b896bde70d0382
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardstatusa.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SmartCardEmulation#event-statusRequested
var StatusRequested = cdp.Event[EventStatusRequested]{Method: "SmartCardEmulation.statusRequested"}

// BeginTransactionRequested fired when |SCardBeginTransaction| is called.
// This maps to: PC/SC Lite:
// https://pcsclite.apdu.fr/api/group__API.html#gaddb835dce01a0da1d6ca02d33ee7d861
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardbegintransaction.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SmartCardEmulation#event-beginTransactionRequested
var BeginTransactionRequested = cdp.Event[EventBeginTransactionRequested]{Method: "SmartCardEmulation.beginTransactionRequested"}

// EndTransactionRequested fired when |SCardEndTransaction| is called. This
// maps to: PC/SC Lite:
// https://pcsclite.apdu.fr/api/group__API.html#gae8742473b404363e5c587f570d7e2f3b
// Microsoft:
// https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardendtransaction.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/SmartCardEmulation#event-endTransactionRequested
var EndTransactionRequested = cdp.Event[EventEndTransactionRequested]{Method: "SmartCardEmulation.endTransactionRequested"}

// Command names.
const (
	CommandEnable                       = "SmartCardEmulation.enable"
	CommandDisable                      = "SmartCardEmulation.disable"
	CommandReportEstablishContextResult = "SmartCardEmulation.reportEstablishContextResult"
	CommandReportReleaseContextResult   = "SmartCardEmulation.reportReleaseContextResult"
	CommandReportListReadersResult      = "SmartCardEmulation.reportListReadersResult"
	CommandReportGetStatusChangeResult  = "SmartCardEmulation.reportGetStatusChangeResult"
	CommandReportBeginTransactionResult = "SmartCardEmulation.reportBeginTransactionResult"
	CommandReportPlainResult            = "SmartCardEmulation.reportPlainResult"
	CommandReportConnectResult          = "SmartCardEmulation.reportConnectResult"
	CommandReportDataResult             = "SmartCardEmulation.reportDataResult"
	CommandReportStatusResult           = "SmartCardEmulation.reportStatusResult"
	CommandReportError                  = "SmartCardEmulation.reportError"
)
