// Code generated by pdlgen. DO NOT EDIT.

// Package extensions provides the Chrome DevTools Protocol
// commands, types, and events for the Extensions domain.
//
// Defines commands and events for browser extensions.
//
// Generated by the pdlgen command.
package extensions

import (
	"github.com/chromedp/cdproto/cdp"
	jsonv2 "github.com/chromedp/cdproto/cdp/jsonv2"
)

// TriggerActionParams are the parameters of the command
// Extensions.triggerAction.
type TriggerActionParams struct {
	ID       string `json:"id"`       // Extension id.
	TargetID string `json:"targetId"` // A tab target ID to trigger the default extension action on.
}

// TriggerAction runs an extension default action.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Extensions#method-triggerAction
var TriggerAction = cdp.Command[TriggerActionParams, cdp.Empty]{Method: CommandTriggerAction}

// LoadUnpackedParams are the parameters of the command
// Extensions.loadUnpacked.
type LoadUnpackedParams struct {
	Path              string `json:"path"`                                 // Absolute file path.
	EnableInIncognito *bool  `json:"enableInIncognito,omitempty,omitzero"` // Enable the extension in incognito
}

// LoadUnpackedResult is the result of the command Extensions.loadUnpacked.
type LoadUnpackedResult struct {
	ID string `json:"id,omitempty,omitzero"` // Extension id.
}

// LoadUnpacked installs an unpacked extension from the filesystem similar to
// --load-extension CLI flags. Returns extension ID once the extension has been
// installed.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Extensions#method-loadUnpacked
var LoadUnpacked = cdp.Command[LoadUnpackedParams, LoadUnpackedResult]{Method: CommandLoadUnpacked}

// GetExtensionsResult is the result of the command Extensions.getExtensions.
type GetExtensionsResult struct {
	Extensions []*ExtensionInfo `json:"extensions,omitempty,omitzero"`
}

// GetExtensions gets a list of all unpacked extensions.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Extensions#method-getExtensions
var GetExtensions = cdp.Command[cdp.Empty, GetExtensionsResult]{Method: CommandGetExtensions}

// UninstallParams are the parameters of the command Extensions.uninstall.
type UninstallParams struct {
	ID string `json:"id"` // Extension id.
}

// Uninstall uninstalls an unpacked extension (others not supported) from the
// profile.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Extensions#method-uninstall
var Uninstall = cdp.Command[UninstallParams, cdp.Empty]{Method: CommandUninstall}

// GetStorageItemsParams are the parameters of the command
// Extensions.getStorageItems.
type GetStorageItemsParams struct {
	ID          string      `json:"id"`                      // ID of extension.
	StorageArea StorageArea `json:"storageArea"`             // StorageArea to retrieve data from.
	Keys        []string    `json:"keys,omitempty,omitzero"` // Keys to retrieve.
}

// GetStorageItemsResult is the result of the command
// Extensions.getStorageItems.
type GetStorageItemsResult struct {
	Data jsonv2.Value `json:"data,omitempty,omitzero"`
}

// GetStorageItems gets data from extension storage in the given storageArea.
// If keys is specified, these are used to filter the result.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Extensions#method-getStorageItems
var GetStorageItems = cdp.Command[GetStorageItemsParams, GetStorageItemsResult]{Method: CommandGetStorageItems}

// RemoveStorageItemsParams are the parameters of the command
// Extensions.removeStorageItems.
type RemoveStorageItemsParams struct {
	ID          string      `json:"id"`          // ID of extension.
	StorageArea StorageArea `json:"storageArea"` // StorageArea to remove data from.
	Keys        []string    `json:"keys"`        // Keys to remove.
}

// RemoveStorageItems removes keys from extension storage in the given
// storageArea.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Extensions#method-removeStorageItems
var RemoveStorageItems = cdp.Command[RemoveStorageItemsParams, cdp.Empty]{Method: CommandRemoveStorageItems}

// ClearStorageItemsParams are the parameters of the command
// Extensions.clearStorageItems.
type ClearStorageItemsParams struct {
	ID          string      `json:"id"`          // ID of extension.
	StorageArea StorageArea `json:"storageArea"` // StorageArea to remove data from.
}

// ClearStorageItems clears extension storage in the given storageArea.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Extensions#method-clearStorageItems
var ClearStorageItems = cdp.Command[ClearStorageItemsParams, cdp.Empty]{Method: CommandClearStorageItems}

// SetStorageItemsParams are the parameters of the command
// Extensions.setStorageItems.
type SetStorageItemsParams struct {
	ID          string       `json:"id"`          // ID of extension.
	StorageArea StorageArea  `json:"storageArea"` // StorageArea to set data in.
	Values      jsonv2.Value `json:"values"`
}

// SetStorageItems sets values in extension storage in the given storageArea.
// The provided values will be merged with existing values in the storage area.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Extensions#method-setStorageItems
var SetStorageItems = cdp.Command[SetStorageItemsParams, cdp.Empty]{Method: CommandSetStorageItems}

// Command names.
const (
	CommandTriggerAction      = "Extensions.triggerAction"
	CommandLoadUnpacked       = "Extensions.loadUnpacked"
	CommandGetExtensions      = "Extensions.getExtensions"
	CommandUninstall          = "Extensions.uninstall"
	CommandGetStorageItems    = "Extensions.getStorageItems"
	CommandRemoveStorageItems = "Extensions.removeStorageItems"
	CommandClearStorageItems  = "Extensions.clearStorageItems"
	CommandSetStorageItems    = "Extensions.setStorageItems"
)
