// Code generated by pdlgen. DO NOT EDIT.

package domdebugger

import (
	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/runtime"
)

// DOMBreakpointType DOM breakpoint type.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOMDebugger#type-DOMBreakpointType
type DOMBreakpointType string

// String returns the DOMBreakpointType as string value.
func (t DOMBreakpointType) String() string {
	return string(t)
}

// DOMBreakpointType values.
const (
	DOMBreakpointTypeSubtreeModified   DOMBreakpointType = "subtree-modified"
	DOMBreakpointTypeAttributeModified DOMBreakpointType = "attribute-modified"
	DOMBreakpointTypeNodeRemoved       DOMBreakpointType = "node-removed"
)

// CSPViolationType cSP Violation type.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOMDebugger#type-CSPViolationType
type CSPViolationType string

// String returns the CSPViolationType as string value.
func (t CSPViolationType) String() string {
	return string(t)
}

// CSPViolationType values.
const (
	CSPViolationTypeTrustedtypeSinkViolation   CSPViolationType = "trustedtype-sink-violation"
	CSPViolationTypeTrustedtypePolicyViolation CSPViolationType = "trustedtype-policy-violation"
)

// EventListener object event listener.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOMDebugger#type-EventListener
type EventListener struct {
	Type            string                `json:"type"`                               // EventListener's type.
	UseCapture      bool                  `json:"useCapture"`                         // EventListener's useCapture.
	Passive         bool                  `json:"passive"`                            // EventListener's passive flag.
	Once            bool                  `json:"once"`                               // EventListener's once flag.
	ScriptID        cdp.ScriptID          `json:"scriptId"`                           // Script id of the handler code.
	LineNumber      int64                 `json:"lineNumber"`                         // Line number in the script (0-based).
	ColumnNumber    int64                 `json:"columnNumber"`                       // Column number in the script (0-based).
	Handler         *runtime.RemoteObject `json:"handler,omitempty,omitzero"`         // Event handler function value.
	OriginalHandler *runtime.RemoteObject `json:"originalHandler,omitempty,omitzero"` // Event original handler function value.
	BackendNodeID   cdp.BackendNodeID     `json:"backendNodeId,omitempty,omitzero"`   // Node the listener is added to (if any).
}
