// Code generated by pdlgen. DO NOT EDIT.

// Package webmcp provides the Chrome DevTools Protocol
// commands, types, and events for the WebMCP domain.
//
// Generated by the pdlgen command.
package webmcp

import (
	"encoding/json/jsontext"

	"github.com/chromedp/cdproto/cdp"
)

// Enable enables the WebMCP domain, allowing events to be sent. Enabling the
// domain will trigger a toolsAdded event for all currently registered tools.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/WebMCP#method-enable
var Enable = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandEnable}

// Disable disables the WebMCP domain.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/WebMCP#method-disable
var Disable = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandDisable}

// InvokeToolParams are the parameters of the command WebMCP.invokeTool.
type InvokeToolParams struct {
	FrameID  cdp.FrameID    `json:"frameId"`  // Frame in which to invoke the tool.
	ToolName string         `json:"toolName"` // Name of the tool to invoke.
	Input    jsontext.Value `json:"input"`
}

// InvokeToolResult is the result of the command WebMCP.invokeTool.
type InvokeToolResult struct {
	InvocationID string `json:"invocationId,omitempty,omitzero"` // Unique identifier for this invocation. Response is sent before tool events.
}

// InvokeTool invokes a registered tool.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/WebMCP#method-invokeTool
var InvokeTool = cdp.Command[InvokeToolParams, InvokeToolResult]{Method: CommandInvokeTool}

// CancelInvocationParams are the parameters of the command
// WebMCP.cancelInvocation.
type CancelInvocationParams struct {
	InvocationID string `json:"invocationId"` // Invocation identifier to cancel.
}

// CancelInvocation cancels a pending tool invocation.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/WebMCP#method-cancelInvocation
var CancelInvocation = cdp.Command[CancelInvocationParams, cdp.Empty]{Method: CommandCancelInvocation}

// ToolsAdded event fired when new tools are added.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/WebMCP#event-toolsAdded
var ToolsAdded = cdp.Event[EventToolsAdded]{Method: "WebMCP.toolsAdded"}

// ToolsRemoved event fired when tools are removed.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/WebMCP#event-toolsRemoved
var ToolsRemoved = cdp.Event[EventToolsRemoved]{Method: "WebMCP.toolsRemoved"}

// ToolInvoked event fired when a tool invocation starts.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/WebMCP#event-toolInvoked
var ToolInvoked = cdp.Event[EventToolInvoked]{Method: "WebMCP.toolInvoked"}

// ToolResponded event fired when a tool invocation completes or fails.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/WebMCP#event-toolResponded
var ToolResponded = cdp.Event[EventToolResponded]{Method: "WebMCP.toolResponded"}

// Command names.
const (
	CommandEnable           = "WebMCP.enable"
	CommandDisable          = "WebMCP.disable"
	CommandInvokeTool       = "WebMCP.invokeTool"
	CommandCancelInvocation = "WebMCP.cancelInvocation"
)
