// Code generated by pdlgen. DO NOT EDIT.

// Package performancetimeline provides the Chrome DevTools Protocol
// commands, types, and events for the PerformanceTimeline domain.
//
// Reporting of performance timeline events, as specified in
// https://w3c.github.io/performance-timeline/#dom-performanceobserver.
//
// Generated by the pdlgen command.
package performancetimeline

import (
	"github.com/chromedp/cdproto/cdp"
)

// EnableParams are the parameters of the command PerformanceTimeline.enable.
type EnableParams struct {
	EventTypes []string `json:"eventTypes"` // The types of event to report, as specified in https://w3c.github.io/performance-timeline/#dom-performanceentry-entrytype The specified filter overrides any previous filters, passing empty filter disables recording. Note that not all types exposed to the web platform are currently supported.
}

// Enable previously buffered events would be reported before method returns.
// See also: timelineEventAdded.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/PerformanceTimeline#method-enable
var Enable = cdp.Command[EnableParams, cdp.Empty]{Method: CommandEnable}

// TimelineEventAdded sent when a performance timeline event is added. See
// reportPerformanceTimeline method.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/PerformanceTimeline#event-timelineEventAdded
var TimelineEventAdded = cdp.Event[EventTimelineEventAdded]{Method: "PerformanceTimeline.timelineEventAdded"}

// Command names.
const (
	CommandEnable = "PerformanceTimeline.enable"
)
