// Code generated by pdlgen. DO NOT EDIT.

// Package animation provides the Chrome DevTools Protocol
// commands, types, and events for the Animation domain.
//
// Generated by the pdlgen command.
package animation

import (
	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/runtime"
)

// Disable disables animation domain notifications.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Animation#method-disable
var Disable = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandDisable}

// Enable enables animation domain notifications.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Animation#method-enable
var Enable = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandEnable}

// GetCurrentTimeParams are the parameters of the command
// Animation.getCurrentTime.
type GetCurrentTimeParams struct {
	ID string `json:"id"` // Id of animation.
}

// GetCurrentTimeResult is the result of the command
// Animation.getCurrentTime.
type GetCurrentTimeResult struct {
	CurrentTime float64 `json:"currentTime,omitempty,omitzero"` // Current time of the page.
}

// GetCurrentTime returns the current time of the an animation.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Animation#method-getCurrentTime
var GetCurrentTime = cdp.Command[GetCurrentTimeParams, GetCurrentTimeResult]{Method: CommandGetCurrentTime}

// GetPlaybackRateResult is the result of the command
// Animation.getPlaybackRate.
type GetPlaybackRateResult struct {
	PlaybackRate float64 `json:"playbackRate,omitempty,omitzero"` // Playback rate for animations on page.
}

// GetPlaybackRate gets the playback rate of the document timeline.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Animation#method-getPlaybackRate
var GetPlaybackRate = cdp.Command[cdp.Empty, GetPlaybackRateResult]{Method: CommandGetPlaybackRate}

// ReleaseAnimationsParams are the parameters of the command
// Animation.releaseAnimations.
type ReleaseAnimationsParams struct {
	Animations []string `json:"animations"` // List of animation ids to seek.
}

// ReleaseAnimations releases a set of animations to no longer be
// manipulated.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Animation#method-releaseAnimations
var ReleaseAnimations = cdp.Command[ReleaseAnimationsParams, cdp.Empty]{Method: CommandReleaseAnimations}

// ResolveAnimationParams are the parameters of the command
// Animation.resolveAnimation.
type ResolveAnimationParams struct {
	AnimationID string `json:"animationId"` // Animation id.
}

// ResolveAnimationResult is the result of the command
// Animation.resolveAnimation.
type ResolveAnimationResult struct {
	RemoteObject *runtime.RemoteObject `json:"remoteObject,omitempty,omitzero"` // Corresponding remote object.
}

// ResolveAnimation gets the remote object of the Animation.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Animation#method-resolveAnimation
var ResolveAnimation = cdp.Command[ResolveAnimationParams, ResolveAnimationResult]{Method: CommandResolveAnimation}

// SeekAnimationsParams are the parameters of the command
// Animation.seekAnimations.
type SeekAnimationsParams struct {
	Animations   []string  `json:"animations"`                      // List of animation ids to seek.
	CurrentTime  *float64  `json:"currentTime,omitempty,omitzero"`  // Set each animation to the same time.
	CurrentTimes []float64 `json:"currentTimes,omitempty,omitzero"` // Set each animation to a different time. If set, should have the same length as animations. Exactly one of currentTime or currentTimes should be set.
}

// SeekAnimations seek a set of animations to a particular time within each
// animation.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Animation#method-seekAnimations
var SeekAnimations = cdp.Command[SeekAnimationsParams, cdp.Empty]{Method: CommandSeekAnimations}

// SetPausedParams are the parameters of the command Animation.setPaused.
type SetPausedParams struct {
	Animations []string `json:"animations"` // Animations to set the pause state of.
	Paused     bool     `json:"paused"`     // Paused state to set to.
}

// SetPaused sets the paused state of a set of animations.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Animation#method-setPaused
var SetPaused = cdp.Command[SetPausedParams, cdp.Empty]{Method: CommandSetPaused}

// SetPlaybackRateParams are the parameters of the command
// Animation.setPlaybackRate.
type SetPlaybackRateParams struct {
	PlaybackRate float64 `json:"playbackRate"` // Playback rate for animations on page
}

// SetPlaybackRate sets the playback rate of the document timeline.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Animation#method-setPlaybackRate
var SetPlaybackRate = cdp.Command[SetPlaybackRateParams, cdp.Empty]{Method: CommandSetPlaybackRate}

// SetTimingParams are the parameters of the command Animation.setTiming.
type SetTimingParams struct {
	AnimationID string  `json:"animationId"` // Animation id.
	Duration    float64 `json:"duration"`    // Duration of the animation.
	Delay       float64 `json:"delay"`       // Delay of the animation.
}

// SetTiming sets the timing of an animation node.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Animation#method-setTiming
var SetTiming = cdp.Command[SetTimingParams, cdp.Empty]{Method: CommandSetTiming}

// AnimationCanceled event for when an animation has been cancelled.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Animation#event-animationCanceled
var AnimationCanceled = cdp.Event[EventAnimationCanceled]{Method: "Animation.animationCanceled"}

// AnimationCreated event for each animation that has been created.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Animation#event-animationCreated
var AnimationCreated = cdp.Event[EventAnimationCreated]{Method: "Animation.animationCreated"}

// AnimationStarted event for animation that has been started.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Animation#event-animationStarted
var AnimationStarted = cdp.Event[EventAnimationStarted]{Method: "Animation.animationStarted"}

// AnimationUpdated event for animation that has been updated.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Animation#event-animationUpdated
var AnimationUpdated = cdp.Event[EventAnimationUpdated]{Method: "Animation.animationUpdated"}

// Command names.
const (
	CommandDisable           = "Animation.disable"
	CommandEnable            = "Animation.enable"
	CommandGetCurrentTime    = "Animation.getCurrentTime"
	CommandGetPlaybackRate   = "Animation.getPlaybackRate"
	CommandReleaseAnimations = "Animation.releaseAnimations"
	CommandResolveAnimation  = "Animation.resolveAnimation"
	CommandSeekAnimations    = "Animation.seekAnimations"
	CommandSetPaused         = "Animation.setPaused"
	CommandSetPlaybackRate   = "Animation.setPlaybackRate"
	CommandSetTiming         = "Animation.setTiming"
)
