// Code generated by pdlgen. DO NOT EDIT.

// Package dom provides the Chrome DevTools Protocol
// commands, types, and events for the DOM domain.
//
// This domain exposes DOM read/write operations. Each DOM Node is
// represented with its mirror object that has an id. This id can be used to get
// additional information on the Node, resolve it into the JavaScript object
// wrapper, etc. It is important that client receives DOM events only for the
// nodes that are known to the client. Backend keeps track of the nodes that
// were sent to the client and never sends the same node twice. It is client's
// responsibility to collect information about the nodes that were sent to the
// client. Note that iframe owner elements will return corresponding document
// elements as their child nodes.
//
// Generated by the pdlgen command.
package dom

import (
	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/runtime"
)

// CollectClassNamesFromSubtreeParams are the parameters of the command
// DOM.collectClassNamesFromSubtree.
type CollectClassNamesFromSubtreeParams struct {
	NodeID cdp.NodeID `json:"nodeId"` // Id of the node to collect class names.
}

// CollectClassNamesFromSubtreeResult is the result of the command
// DOM.collectClassNamesFromSubtree.
type CollectClassNamesFromSubtreeResult struct {
	ClassNames []string `json:"classNames,omitempty,omitzero"` // Class name list.
}

// CollectClassNamesFromSubtree collects class names for the node with given
// id and all of it's child nodes.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-collectClassNamesFromSubtree
var CollectClassNamesFromSubtree = cdp.Command[CollectClassNamesFromSubtreeParams, CollectClassNamesFromSubtreeResult]{Method: CommandCollectClassNamesFromSubtree}

// CopyToParams are the parameters of the command DOM.copyTo.
type CopyToParams struct {
	NodeID             cdp.NodeID `json:"nodeId"`                                // Id of the node to copy.
	TargetNodeID       cdp.NodeID `json:"targetNodeId"`                          // Id of the element to drop the copy into.
	InsertBeforeNodeID cdp.NodeID `json:"insertBeforeNodeId,omitempty,omitzero"` // Drop the copy before this node (if absent, the copy becomes the last child of targetNodeId).
}

// CopyToResult is the result of the command DOM.copyTo.
type CopyToResult struct {
	NodeID cdp.NodeID `json:"nodeId,omitempty,omitzero"` // Id of the node clone.
}

// CopyTo creates a deep copy of the specified node and places it into the
// target container before the given anchor.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-copyTo
var CopyTo = cdp.Command[CopyToParams, CopyToResult]{Method: CommandCopyTo}

// DescribeNodeParams are the parameters of the command DOM.describeNode.
type DescribeNodeParams struct {
	NodeID        cdp.NodeID             `json:"nodeId,omitempty,omitzero"`        // Identifier of the node.
	BackendNodeID cdp.BackendNodeID      `json:"backendNodeId,omitempty,omitzero"` // Identifier of the backend node.
	ObjectID      runtime.RemoteObjectID `json:"objectId,omitempty,omitzero"`      // JavaScript object id of the node wrapper.
	Depth         int64                  `json:"depth,omitempty,omitzero"`         // The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the entire subtree or provide an integer larger than 0.
	Pierce        *bool                  `json:"pierce,omitempty,omitzero"`        // Whether or not iframes and shadow roots should be traversed when returning the subtree (default is false).
}

// DescribeNodeResult is the result of the command DOM.describeNode.
type DescribeNodeResult struct {
	Node *cdp.Node `json:"node,omitempty,omitzero"` // Node description.
}

// DescribeNode describes node given its id, does not require domain to be
// enabled. Does not start tracking any objects, can be used for automation.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-describeNode
var DescribeNode = cdp.Command[DescribeNodeParams, DescribeNodeResult]{Method: CommandDescribeNode}

// ScrollIntoViewIfNeededParams are the parameters of the command
// DOM.scrollIntoViewIfNeeded.
type ScrollIntoViewIfNeededParams struct {
	NodeID        cdp.NodeID             `json:"nodeId,omitempty,omitzero"`        // Identifier of the node.
	BackendNodeID cdp.BackendNodeID      `json:"backendNodeId,omitempty,omitzero"` // Identifier of the backend node.
	ObjectID      runtime.RemoteObjectID `json:"objectId,omitempty,omitzero"`      // JavaScript object id of the node wrapper.
	Rect          *Rect                  `json:"rect,omitempty,omitzero"`          // The rect to be scrolled into view, relative to the node's border box, in CSS pixels. When omitted, center of the node will be used, similar to Element.scrollIntoView.
}

// ScrollIntoViewIfNeeded scrolls the specified rect of the given node into
// view if not already visible. Note: exactly one between nodeId, backendNodeId
// and objectId should be passed to identify the node.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-scrollIntoViewIfNeeded
var ScrollIntoViewIfNeeded = cdp.Command[ScrollIntoViewIfNeededParams, cdp.Empty]{Method: CommandScrollIntoViewIfNeeded}

// Disable disables DOM agent for the given page.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-disable
var Disable = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandDisable}

// DiscardSearchResultsParams are the parameters of the command
// DOM.discardSearchResults.
type DiscardSearchResultsParams struct {
	SearchID string `json:"searchId"` // Unique search session identifier.
}

// DiscardSearchResults discards search results from the session with the
// given id. getSearchResults should no longer be called for that search.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-discardSearchResults
var DiscardSearchResults = cdp.Command[DiscardSearchResultsParams, cdp.Empty]{Method: CommandDiscardSearchResults}

// EnableParams are the parameters of the command DOM.enable.
type EnableParams struct {
	IncludeWhitespace EnableIncludeWhitespace `json:"includeWhitespace,omitempty,omitzero"` // Whether to include whitespaces in the children array of returned Nodes.
}

// Enable enables DOM agent for the given page.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-enable
var Enable = cdp.Command[EnableParams, cdp.Empty]{Method: CommandEnable}

// FocusParams are the parameters of the command DOM.focus.
type FocusParams struct {
	NodeID        cdp.NodeID             `json:"nodeId,omitempty,omitzero"`        // Identifier of the node.
	BackendNodeID cdp.BackendNodeID      `json:"backendNodeId,omitempty,omitzero"` // Identifier of the backend node.
	ObjectID      runtime.RemoteObjectID `json:"objectId,omitempty,omitzero"`      // JavaScript object id of the node wrapper.
}

// Focus focuses the given element.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-focus
var Focus = cdp.Command[FocusParams, cdp.Empty]{Method: CommandFocus}

// GetAttributesParams are the parameters of the command DOM.getAttributes.
type GetAttributesParams struct {
	NodeID cdp.NodeID `json:"nodeId"` // Id of the node to retrieve attributes for.
}

// GetAttributesResult is the result of the command DOM.getAttributes.
type GetAttributesResult struct {
	Attributes []string `json:"attributes,omitempty,omitzero"` // An interleaved array of node attribute names and values.
}

// GetAttributes returns attributes for the specified node.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-getAttributes
var GetAttributes = cdp.Command[GetAttributesParams, GetAttributesResult]{Method: CommandGetAttributes}

// GetBoxModelParams are the parameters of the command DOM.getBoxModel.
type GetBoxModelParams struct {
	NodeID        cdp.NodeID             `json:"nodeId,omitempty,omitzero"`        // Identifier of the node.
	BackendNodeID cdp.BackendNodeID      `json:"backendNodeId,omitempty,omitzero"` // Identifier of the backend node.
	ObjectID      runtime.RemoteObjectID `json:"objectId,omitempty,omitzero"`      // JavaScript object id of the node wrapper.
}

// GetBoxModelResult is the result of the command DOM.getBoxModel.
type GetBoxModelResult struct {
	Model *BoxModel `json:"model,omitempty,omitzero"` // Box model for the node.
}

// GetBoxModel returns boxes for the given node.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-getBoxModel
var GetBoxModel = cdp.Command[GetBoxModelParams, GetBoxModelResult]{Method: CommandGetBoxModel}

// GetContentQuadsParams are the parameters of the command
// DOM.getContentQuads.
type GetContentQuadsParams struct {
	NodeID        cdp.NodeID             `json:"nodeId,omitempty,omitzero"`        // Identifier of the node.
	BackendNodeID cdp.BackendNodeID      `json:"backendNodeId,omitempty,omitzero"` // Identifier of the backend node.
	ObjectID      runtime.RemoteObjectID `json:"objectId,omitempty,omitzero"`      // JavaScript object id of the node wrapper.
}

// GetContentQuadsResult is the result of the command DOM.getContentQuads.
type GetContentQuadsResult struct {
	Quads []Quad `json:"quads,omitempty,omitzero"` // Quads that describe node layout relative to viewport.
}

// GetContentQuads returns quads that describe node position on the page.
// This method might return multiple quads for inline nodes.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-getContentQuads
var GetContentQuads = cdp.Command[GetContentQuadsParams, GetContentQuadsResult]{Method: CommandGetContentQuads}

// GetDocumentParams are the parameters of the command DOM.getDocument.
type GetDocumentParams struct {
	Depth  int64 `json:"depth,omitempty,omitzero"`  // The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the entire subtree or provide an integer larger than 0.
	Pierce *bool `json:"pierce,omitempty,omitzero"` // Whether or not iframes and shadow roots should be traversed when returning the subtree (default is false).
}

// GetDocumentResult is the result of the command DOM.getDocument.
type GetDocumentResult struct {
	Root *cdp.Node `json:"root,omitempty,omitzero"` // Resulting node.
}

// GetDocument returns the root DOM node (and optionally the subtree) to the
// caller. Implicitly enables the DOM domain events for the current target.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-getDocument
var GetDocument = cdp.Command[GetDocumentParams, GetDocumentResult]{Method: CommandGetDocument}

// GetNodesForSubtreeByStyleParams are the parameters of the command
// DOM.getNodesForSubtreeByStyle.
type GetNodesForSubtreeByStyleParams struct {
	NodeID         cdp.NodeID                  `json:"nodeId"`                    // Node ID pointing to the root of a subtree.
	ComputedStyles []*CSSComputedStyleProperty `json:"computedStyles"`            // The style to filter nodes by (includes nodes if any of properties matches).
	Pierce         *bool                       `json:"pierce,omitempty,omitzero"` // Whether or not iframes and shadow roots in the same target should be traversed when returning the results (default is false).
}

// GetNodesForSubtreeByStyleResult is the result of the command
// DOM.getNodesForSubtreeByStyle.
type GetNodesForSubtreeByStyleResult struct {
	NodeIDs []cdp.NodeID `json:"nodeIds,omitempty,omitzero"` // Resulting nodes.
}

// GetNodesForSubtreeByStyle finds nodes with a given computed style in a
// subtree.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-getNodesForSubtreeByStyle
var GetNodesForSubtreeByStyle = cdp.Command[GetNodesForSubtreeByStyleParams, GetNodesForSubtreeByStyleResult]{Method: CommandGetNodesForSubtreeByStyle}

// GetNodeForLocationParams are the parameters of the command
// DOM.getNodeForLocation.
type GetNodeForLocationParams struct {
	X                         int64 `json:"x"`                                            // X coordinate.
	Y                         int64 `json:"y"`                                            // Y coordinate.
	IncludeUserAgentShadowDOM *bool `json:"includeUserAgentShadowDOM,omitempty,omitzero"` // False to skip to the nearest non-UA shadow root ancestor (default: false).
	IgnorePointerEventsNone   *bool `json:"ignorePointerEventsNone,omitempty,omitzero"`   // Whether to ignore pointer-events: none on elements and hit test them.
}

// GetNodeForLocationResult is the result of the command
// DOM.getNodeForLocation.
type GetNodeForLocationResult struct {
	BackendNodeID cdp.BackendNodeID `json:"backendNodeId,omitempty,omitzero"` // Resulting node.
	FrameID       cdp.FrameID       `json:"frameId,omitempty,omitzero"`       // Frame this node belongs to.
	NodeID        cdp.NodeID        `json:"nodeId,omitempty,omitzero"`        // Id of the node at given coordinates, only when enabled and requested document.
}

// GetNodeForLocation returns node id at given location. Depending on whether
// DOM domain is enabled, nodeId is either returned or not.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-getNodeForLocation
var GetNodeForLocation = cdp.Command[GetNodeForLocationParams, GetNodeForLocationResult]{Method: CommandGetNodeForLocation}

// GetOuterHTMLParams are the parameters of the command DOM.getOuterHTML.
type GetOuterHTMLParams struct {
	NodeID           cdp.NodeID             `json:"nodeId,omitempty,omitzero"`           // Identifier of the node.
	BackendNodeID    cdp.BackendNodeID      `json:"backendNodeId,omitempty,omitzero"`    // Identifier of the backend node.
	ObjectID         runtime.RemoteObjectID `json:"objectId,omitempty,omitzero"`         // JavaScript object id of the node wrapper.
	IncludeShadowDOM *bool                  `json:"includeShadowDOM,omitempty,omitzero"` // Include all shadow roots. Equals to false if not specified.
}

// GetOuterHTMLResult is the result of the command DOM.getOuterHTML.
type GetOuterHTMLResult struct {
	OuterHTML string `json:"outerHTML,omitempty,omitzero"` // Outer HTML markup.
}

// GetOuterHTML returns node's HTML markup.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-getOuterHTML
var GetOuterHTML = cdp.Command[GetOuterHTMLParams, GetOuterHTMLResult]{Method: CommandGetOuterHTML}

// GetRelayoutBoundaryParams are the parameters of the command
// DOM.getRelayoutBoundary.
type GetRelayoutBoundaryParams struct {
	NodeID cdp.NodeID `json:"nodeId"` // Id of the node.
}

// GetRelayoutBoundaryResult is the result of the command
// DOM.getRelayoutBoundary.
type GetRelayoutBoundaryResult struct {
	NodeID cdp.NodeID `json:"nodeId,omitempty,omitzero"` // Relayout boundary node id for the given node.
}

// GetRelayoutBoundary returns the id of the nearest ancestor that is a
// relayout boundary.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-getRelayoutBoundary
var GetRelayoutBoundary = cdp.Command[GetRelayoutBoundaryParams, GetRelayoutBoundaryResult]{Method: CommandGetRelayoutBoundary}

// GetSearchResultsParams are the parameters of the command
// DOM.getSearchResults.
type GetSearchResultsParams struct {
	SearchID  string `json:"searchId"`  // Unique search session identifier.
	FromIndex int64  `json:"fromIndex"` // Start index of the search result to be returned.
	ToIndex   int64  `json:"toIndex"`   // End index of the search result to be returned.
}

// GetSearchResultsResult is the result of the command DOM.getSearchResults.
type GetSearchResultsResult struct {
	NodeIDs []cdp.NodeID `json:"nodeIds,omitempty,omitzero"` // Ids of the search result nodes.
}

// GetSearchResults returns search results from given fromIndex to given
// toIndex from the search with the given identifier.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-getSearchResults
var GetSearchResults = cdp.Command[GetSearchResultsParams, GetSearchResultsResult]{Method: CommandGetSearchResults}

// MarkUndoableState marks last undoable state.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-markUndoableState
var MarkUndoableState = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandMarkUndoableState}

// MoveToParams are the parameters of the command DOM.moveTo.
type MoveToParams struct {
	NodeID             cdp.NodeID `json:"nodeId"`                                // Id of the node to move.
	TargetNodeID       cdp.NodeID `json:"targetNodeId"`                          // Id of the element to drop the moved node into.
	InsertBeforeNodeID cdp.NodeID `json:"insertBeforeNodeId,omitempty,omitzero"` // Drop node before this one (if absent, the moved node becomes the last child of targetNodeId).
}

// MoveToResult is the result of the command DOM.moveTo.
type MoveToResult struct {
	NodeID cdp.NodeID `json:"nodeId,omitempty,omitzero"` // New id of the moved node.
}

// MoveTo moves node into the new container, places it before the given
// anchor.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-moveTo
var MoveTo = cdp.Command[MoveToParams, MoveToResult]{Method: CommandMoveTo}

// PerformSearchParams are the parameters of the command DOM.performSearch.
type PerformSearchParams struct {
	Query                     string `json:"query"`                                        // Plain text or query selector or XPath search query.
	IncludeUserAgentShadowDOM *bool  `json:"includeUserAgentShadowDOM,omitempty,omitzero"` // True to search in user agent shadow DOM.
}

// PerformSearchResult is the result of the command DOM.performSearch.
type PerformSearchResult struct {
	SearchID    string `json:"searchId,omitempty,omitzero"`    // Unique search session identifier.
	ResultCount int64  `json:"resultCount,omitempty,omitzero"` // Number of search results.
}

// PerformSearch searches for a given string in the DOM tree. Use
// getSearchResults to access search results or cancelSearch to end this search
// session.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-performSearch
var PerformSearch = cdp.Command[PerformSearchParams, PerformSearchResult]{Method: CommandPerformSearch}

// PushNodeByPathToFrontendParams are the parameters of the command
// DOM.pushNodeByPathToFrontend.
type PushNodeByPathToFrontendParams struct {
	Path string `json:"path"` // Path to node in the proprietary format.
}

// PushNodeByPathToFrontendResult is the result of the command
// DOM.pushNodeByPathToFrontend.
type PushNodeByPathToFrontendResult struct {
	NodeID cdp.NodeID `json:"nodeId,omitempty,omitzero"` // Id of the node for given path.
}

// PushNodeByPathToFrontend requests that the node is sent to the caller
// given its path. // FIXME, use XPath.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-pushNodeByPathToFrontend
var PushNodeByPathToFrontend = cdp.Command[PushNodeByPathToFrontendParams, PushNodeByPathToFrontendResult]{Method: CommandPushNodeByPathToFrontend}

// PushNodesByBackendIDsToFrontendParams are the parameters of the command
// DOM.pushNodesByBackendIdsToFrontend.
type PushNodesByBackendIDsToFrontendParams struct {
	BackendNodeIDs []cdp.BackendNodeID `json:"backendNodeIds"` // The array of backend node ids.
}

// PushNodesByBackendIDsToFrontendResult is the result of the command
// DOM.pushNodesByBackendIdsToFrontend.
type PushNodesByBackendIDsToFrontendResult struct {
	NodeIDs []cdp.NodeID `json:"nodeIds,omitempty,omitzero"` // The array of ids of pushed nodes that correspond to the backend ids specified in backendNodeIds.
}

// PushNodesByBackendIDsToFrontend requests that a batch of nodes is sent to
// the caller given their backend node ids.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-pushNodesByBackendIdsToFrontend
var PushNodesByBackendIDsToFrontend = cdp.Command[PushNodesByBackendIDsToFrontendParams, PushNodesByBackendIDsToFrontendResult]{Method: CommandPushNodesByBackendIDsToFrontend}

// QuerySelectorParams are the parameters of the command DOM.querySelector.
type QuerySelectorParams struct {
	NodeID   cdp.NodeID `json:"nodeId"`   // Id of the node to query upon.
	Selector string     `json:"selector"` // Selector string.
}

// QuerySelectorResult is the result of the command DOM.querySelector.
type QuerySelectorResult struct {
	NodeID cdp.NodeID `json:"nodeId,omitempty,omitzero"` // Query selector result.
}

// QuerySelector executes querySelector on a given node.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-querySelector
var QuerySelector = cdp.Command[QuerySelectorParams, QuerySelectorResult]{Method: CommandQuerySelector}

// QuerySelectorAllParams are the parameters of the command
// DOM.querySelectorAll.
type QuerySelectorAllParams struct {
	NodeID   cdp.NodeID `json:"nodeId"`   // Id of the node to query upon.
	Selector string     `json:"selector"` // Selector string.
}

// QuerySelectorAllResult is the result of the command DOM.querySelectorAll.
type QuerySelectorAllResult struct {
	NodeIDs []cdp.NodeID `json:"nodeIds,omitempty,omitzero"` // Query selector result.
}

// QuerySelectorAll executes querySelectorAll on a given node.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-querySelectorAll
var QuerySelectorAll = cdp.Command[QuerySelectorAllParams, QuerySelectorAllResult]{Method: CommandQuerySelectorAll}

// GetTopLayerElementsResult is the result of the command
// DOM.getTopLayerElements.
type GetTopLayerElementsResult struct {
	NodeIDs []cdp.NodeID `json:"nodeIds,omitempty,omitzero"` // NodeIds of top layer elements
}

// GetTopLayerElements returns NodeIds of current top layer elements. Top
// layer is rendered closest to the user within a viewport, therefore its
// elements always appear on top of all other content.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-getTopLayerElements
var GetTopLayerElements = cdp.Command[cdp.Empty, GetTopLayerElementsResult]{Method: CommandGetTopLayerElements}

// GetElementByRelationParams are the parameters of the command
// DOM.getElementByRelation.
type GetElementByRelationParams struct {
	NodeID   cdp.NodeID                   `json:"nodeId"`   // Id of the node from which to query the relation.
	Relation GetElementByRelationRelation `json:"relation"` // Type of relation to get.
}

// GetElementByRelationResult is the result of the command
// DOM.getElementByRelation.
type GetElementByRelationResult struct {
	NodeID cdp.NodeID `json:"nodeId,omitempty,omitzero"` // NodeId of the element matching the queried relation.
}

// GetElementByRelation returns the NodeId of the matched element according
// to certain relations.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-getElementByRelation
var GetElementByRelation = cdp.Command[GetElementByRelationParams, GetElementByRelationResult]{Method: CommandGetElementByRelation}

// Redo re-does the last undone action.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-redo
var Redo = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandRedo}

// RemoveAttributeParams are the parameters of the command
// DOM.removeAttribute.
type RemoveAttributeParams struct {
	NodeID cdp.NodeID `json:"nodeId"` // Id of the element to remove attribute from.
	Name   string     `json:"name"`   // Name of the attribute to remove.
}

// RemoveAttribute removes attribute with given name from an element with
// given id.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-removeAttribute
var RemoveAttribute = cdp.Command[RemoveAttributeParams, cdp.Empty]{Method: CommandRemoveAttribute}

// RemoveNodeParams are the parameters of the command DOM.removeNode.
type RemoveNodeParams struct {
	NodeID cdp.NodeID `json:"nodeId"` // Id of the node to remove.
}

// RemoveNode removes node with given id.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-removeNode
var RemoveNode = cdp.Command[RemoveNodeParams, cdp.Empty]{Method: CommandRemoveNode}

// RequestChildNodesParams are the parameters of the command
// DOM.requestChildNodes.
type RequestChildNodesParams struct {
	NodeID cdp.NodeID `json:"nodeId"`                    // Id of the node to get children for.
	Depth  int64      `json:"depth,omitempty,omitzero"`  // The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the entire subtree or provide an integer larger than 0.
	Pierce *bool      `json:"pierce,omitempty,omitzero"` // Whether or not iframes and shadow roots should be traversed when returning the sub-tree (default is false).
}

// RequestChildNodes requests that children of the node with given id are
// returned to the caller in form of setChildNodes events where not only
// immediate children are retrieved, but all children down to the specified
// depth.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-requestChildNodes
var RequestChildNodes = cdp.Command[RequestChildNodesParams, cdp.Empty]{Method: CommandRequestChildNodes}

// RequestNodeParams are the parameters of the command DOM.requestNode.
type RequestNodeParams struct {
	ObjectID runtime.RemoteObjectID `json:"objectId"` // JavaScript object id to convert into node.
}

// RequestNodeResult is the result of the command DOM.requestNode.
type RequestNodeResult struct {
	NodeID cdp.NodeID `json:"nodeId,omitempty,omitzero"` // Node id for given object.
}

// RequestNode requests that the node is sent to the caller given the
// JavaScript node object reference. All nodes that form the path from the node
// to the root are also sent to the client as a series of setChildNodes
// notifications.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-requestNode
var RequestNode = cdp.Command[RequestNodeParams, RequestNodeResult]{Method: CommandRequestNode}

// ResolveNodeParams are the parameters of the command DOM.resolveNode.
type ResolveNodeParams struct {
	NodeID             cdp.NodeID                 `json:"nodeId,omitempty,omitzero"`             // Id of the node to resolve.
	BackendNodeID      cdp.BackendNodeID          `json:"backendNodeId,omitempty,omitzero"`      // Backend identifier of the node to resolve.
	ObjectGroup        string                     `json:"objectGroup,omitempty,omitzero"`        // Symbolic group name that can be used to release multiple objects.
	ExecutionContextID runtime.ExecutionContextID `json:"executionContextId,omitempty,omitzero"` // Execution context in which to resolve the node.
}

// ResolveNodeResult is the result of the command DOM.resolveNode.
type ResolveNodeResult struct {
	Object *runtime.RemoteObject `json:"object,omitempty,omitzero"` // JavaScript object wrapper for given node.
}

// ResolveNode resolves the JavaScript node object for a given NodeId or
// BackendNodeId.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-resolveNode
var ResolveNode = cdp.Command[ResolveNodeParams, ResolveNodeResult]{Method: CommandResolveNode}

// SetAttributeValueParams are the parameters of the command
// DOM.setAttributeValue.
type SetAttributeValueParams struct {
	NodeID cdp.NodeID `json:"nodeId"` // Id of the element to set attribute for.
	Name   string     `json:"name"`   // Attribute name.
	Value  string     `json:"value"`  // Attribute value.
}

// SetAttributeValue sets attribute for an element with given id.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-setAttributeValue
var SetAttributeValue = cdp.Command[SetAttributeValueParams, cdp.Empty]{Method: CommandSetAttributeValue}

// SetAttributesAsTextParams are the parameters of the command
// DOM.setAttributesAsText.
type SetAttributesAsTextParams struct {
	NodeID cdp.NodeID `json:"nodeId"`                  // Id of the element to set attributes for.
	Text   string     `json:"text"`                    // Text with a number of attributes. Will parse this text using HTML parser.
	Name   string     `json:"name,omitempty,omitzero"` // Attribute name to replace with new attributes derived from text in case text parsed successfully.
}

// SetAttributesAsText sets attributes on element with given id. This method
// is useful when user edits some existing attribute value and types in several
// attribute name/value pairs.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-setAttributesAsText
var SetAttributesAsText = cdp.Command[SetAttributesAsTextParams, cdp.Empty]{Method: CommandSetAttributesAsText}

// SetFileInputFilesParams are the parameters of the command
// DOM.setFileInputFiles.
type SetFileInputFilesParams struct {
	Files         []string               `json:"files"`                            // Array of file paths to set.
	NodeID        cdp.NodeID             `json:"nodeId,omitempty,omitzero"`        // Identifier of the node.
	BackendNodeID cdp.BackendNodeID      `json:"backendNodeId,omitempty,omitzero"` // Identifier of the backend node.
	ObjectID      runtime.RemoteObjectID `json:"objectId,omitempty,omitzero"`      // JavaScript object id of the node wrapper.
}

// SetFileInputFiles sets files for the given file input element.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-setFileInputFiles
var SetFileInputFiles = cdp.Command[SetFileInputFilesParams, cdp.Empty]{Method: CommandSetFileInputFiles}

// SetNodeStackTracesEnabledParams are the parameters of the command
// DOM.setNodeStackTracesEnabled.
type SetNodeStackTracesEnabledParams struct {
	Enable bool `json:"enable"` // Enable or disable.
}

// SetNodeStackTracesEnabled sets if stack traces should be captured for
// Nodes. See Node.getNodeStackTraces. Default is disabled.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-setNodeStackTracesEnabled
var SetNodeStackTracesEnabled = cdp.Command[SetNodeStackTracesEnabledParams, cdp.Empty]{Method: CommandSetNodeStackTracesEnabled}

// GetNodeStackTracesParams are the parameters of the command
// DOM.getNodeStackTraces.
type GetNodeStackTracesParams struct {
	NodeID cdp.NodeID `json:"nodeId"` // Id of the node to get stack traces for.
}

// GetNodeStackTracesResult is the result of the command
// DOM.getNodeStackTraces.
type GetNodeStackTracesResult struct {
	Creation *runtime.StackTrace `json:"creation,omitempty,omitzero"` // Creation stack trace, if available.
}

// GetNodeStackTraces gets stack traces associated with a Node. As of now,
// only provides stack trace for Node creation.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-getNodeStackTraces
var GetNodeStackTraces = cdp.Command[GetNodeStackTracesParams, GetNodeStackTracesResult]{Method: CommandGetNodeStackTraces}

// GetFileInfoParams are the parameters of the command DOM.getFileInfo.
type GetFileInfoParams struct {
	ObjectID runtime.RemoteObjectID `json:"objectId"` // JavaScript object id of the node wrapper.
}

// GetFileInfoResult is the result of the command DOM.getFileInfo.
type GetFileInfoResult struct {
	Path string `json:"path,omitempty,omitzero"`
}

// GetFileInfo returns file information for the given File wrapper.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-getFileInfo
var GetFileInfo = cdp.Command[GetFileInfoParams, GetFileInfoResult]{Method: CommandGetFileInfo}

// GetDetachedDomNodesResult is the result of the command
// DOM.getDetachedDomNodes.
type GetDetachedDomNodesResult struct {
	DetachedNodes []*DetachedElementInfo `json:"detachedNodes,omitempty,omitzero"` // The list of detached nodes
}

// GetDetachedDomNodes returns list of detached nodes.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-getDetachedDomNodes
var GetDetachedDomNodes = cdp.Command[cdp.Empty, GetDetachedDomNodesResult]{Method: CommandGetDetachedDomNodes}

// SetInspectedNodeParams are the parameters of the command
// DOM.setInspectedNode.
type SetInspectedNodeParams struct {
	NodeID cdp.NodeID `json:"nodeId"` // DOM node id to be accessible by means of $x command line API.
}

// SetInspectedNode enables console to refer to the node with given id via $x
// (see Command Line API for more details $x functions).
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-setInspectedNode
var SetInspectedNode = cdp.Command[SetInspectedNodeParams, cdp.Empty]{Method: CommandSetInspectedNode}

// SetNodeNameParams are the parameters of the command DOM.setNodeName.
type SetNodeNameParams struct {
	NodeID cdp.NodeID `json:"nodeId"` // Id of the node to set name for.
	Name   string     `json:"name"`   // New node's name.
}

// SetNodeNameResult is the result of the command DOM.setNodeName.
type SetNodeNameResult struct {
	NodeID cdp.NodeID `json:"nodeId,omitempty,omitzero"` // New node's id.
}

// SetNodeName sets node name for a node with given id.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-setNodeName
var SetNodeName = cdp.Command[SetNodeNameParams, SetNodeNameResult]{Method: CommandSetNodeName}

// SetNodeValueParams are the parameters of the command DOM.setNodeValue.
type SetNodeValueParams struct {
	NodeID cdp.NodeID `json:"nodeId"` // Id of the node to set value for.
	Value  string     `json:"value"`  // New node's value.
}

// SetNodeValue sets node value for a node with given id.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-setNodeValue
var SetNodeValue = cdp.Command[SetNodeValueParams, cdp.Empty]{Method: CommandSetNodeValue}

// SetOuterHTMLParams are the parameters of the command DOM.setOuterHTML.
type SetOuterHTMLParams struct {
	NodeID    cdp.NodeID `json:"nodeId"`    // Id of the node to set markup for.
	OuterHTML string     `json:"outerHTML"` // Outer HTML markup to set.
}

// SetOuterHTML sets node HTML markup, returns new node id.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-setOuterHTML
var SetOuterHTML = cdp.Command[SetOuterHTMLParams, cdp.Empty]{Method: CommandSetOuterHTML}

// Undo undoes the last performed action.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-undo
var Undo = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandUndo}

// GetFrameOwnerParams are the parameters of the command DOM.getFrameOwner.
type GetFrameOwnerParams struct {
	FrameID cdp.FrameID `json:"frameId"`
}

// GetFrameOwnerResult is the result of the command DOM.getFrameOwner.
type GetFrameOwnerResult struct {
	BackendNodeID cdp.BackendNodeID `json:"backendNodeId,omitempty,omitzero"` // Resulting node.
	NodeID        cdp.NodeID        `json:"nodeId,omitempty,omitzero"`        // Id of the node at given coordinates, only when enabled and requested document.
}

// GetFrameOwner returns iframe node that owns iframe with the given domain.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-getFrameOwner
var GetFrameOwner = cdp.Command[GetFrameOwnerParams, GetFrameOwnerResult]{Method: CommandGetFrameOwner}

// GetContainerForNodeParams are the parameters of the command
// DOM.getContainerForNode.
type GetContainerForNodeParams struct {
	NodeID             cdp.NodeID   `json:"nodeId"`
	ContainerName      string       `json:"containerName,omitempty,omitzero"`
	PhysicalAxes       PhysicalAxes `json:"physicalAxes,omitempty,omitzero"`
	LogicalAxes        LogicalAxes  `json:"logicalAxes,omitempty,omitzero"`
	QueriesScrollState *bool        `json:"queriesScrollState,omitempty,omitzero"`
	QueriesAnchored    *bool        `json:"queriesAnchored,omitempty,omitzero"`
}

// GetContainerForNodeResult is the result of the command
// DOM.getContainerForNode.
type GetContainerForNodeResult struct {
	NodeID cdp.NodeID `json:"nodeId,omitempty,omitzero"` // The container node for the given node, or null if not found.
}

// GetContainerForNode returns the query container of the given node based on
// container query conditions: containerName, physical and logical axes, and
// whether it queries scroll-state or anchored elements. If no axes are provided
// and queriesScrollState is false, the style container is returned, which is
// the direct parent or the closest element with a matching container-name.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-getContainerForNode
var GetContainerForNode = cdp.Command[GetContainerForNodeParams, GetContainerForNodeResult]{Method: CommandGetContainerForNode}

// GetQueryingDescendantsForContainerParams are the parameters of the command
// DOM.getQueryingDescendantsForContainer.
type GetQueryingDescendantsForContainerParams struct {
	NodeID cdp.NodeID `json:"nodeId"` // Id of the container node to find querying descendants from.
}

// GetQueryingDescendantsForContainerResult is the result of the command
// DOM.getQueryingDescendantsForContainer.
type GetQueryingDescendantsForContainerResult struct {
	NodeIDs []cdp.NodeID `json:"nodeIds,omitempty,omitzero"` // Descendant nodes with container queries against the given container.
}

// GetQueryingDescendantsForContainer returns the descendants of a container
// query container that have container queries against this container.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-getQueryingDescendantsForContainer
var GetQueryingDescendantsForContainer = cdp.Command[GetQueryingDescendantsForContainerParams, GetQueryingDescendantsForContainerResult]{Method: CommandGetQueryingDescendantsForContainer}

// GetAnchorElementParams are the parameters of the command
// DOM.getAnchorElement.
type GetAnchorElementParams struct {
	NodeID          cdp.NodeID `json:"nodeId"`                             // Id of the positioned element from which to find the anchor.
	AnchorSpecifier string     `json:"anchorSpecifier,omitempty,omitzero"` // An optional anchor specifier, as defined in https://www.w3.org/TR/css-anchor-position-1/#anchor-specifier. If not provided, it will return the implicit anchor element for the given positioned element.
}

// GetAnchorElementResult is the result of the command DOM.getAnchorElement.
type GetAnchorElementResult struct {
	NodeID cdp.NodeID `json:"nodeId,omitempty,omitzero"` // The anchor element of the given anchor query.
}

// GetAnchorElement returns the target anchor element of the given anchor
// query according to https://www.w3.org/TR/css-anchor-position-1/#target.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-getAnchorElement
var GetAnchorElement = cdp.Command[GetAnchorElementParams, GetAnchorElementResult]{Method: CommandGetAnchorElement}

// ForceShowPopoverParams are the parameters of the command
// DOM.forceShowPopover.
type ForceShowPopoverParams struct {
	NodeID        cdp.NodeID        `json:"nodeId"`                           // Id of the popover HTMLElement
	Enable        bool              `json:"enable"`                           // If true, opens the popover and keeps it open. If false, closes the popover if it was previously force-opened.
	InvokerNodeID cdp.BackendNodeID `json:"invokerNodeId,omitempty,omitzero"` // Optional ID of the element invoking this popover, used to establish the implicit anchor. If not provided, it will fall back to the first invoker in the document, preferring elements with a popovertarget attribute over those with a commandfor attribute. Note that if there are multiple invokers, this is just an estimate.
}

// ForceShowPopoverResult is the result of the command DOM.forceShowPopover.
type ForceShowPopoverResult struct {
	NodeIDs []cdp.NodeID `json:"nodeIds,omitempty,omitzero"` // List of popovers that were closed in order to respect popover stacking order.
}

// ForceShowPopover when enabling, this API force-opens the popover
// identified by nodeId and keeps it open until disabled.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-forceShowPopover
var ForceShowPopover = cdp.Command[ForceShowPopoverParams, ForceShowPopoverResult]{Method: CommandForceShowPopover}

// GetImplicitAnchorCandidatesParams are the parameters of the command
// DOM.getImplicitAnchorCandidates.
type GetImplicitAnchorCandidatesParams struct {
	NodeID cdp.NodeID `json:"nodeId"` // Id of the popover HTMLElement.
}

// GetImplicitAnchorCandidatesResult is the result of the command
// DOM.getImplicitAnchorCandidates.
type GetImplicitAnchorCandidatesResult struct {
	BackendNodeIDs []cdp.BackendNodeID `json:"backendNodeIds,omitempty,omitzero"` // Candidate elements that can invoke this popover.
}

// GetImplicitAnchorCandidates returns candidate nodes that are configured as
// triggers for the given popover.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-getImplicitAnchorCandidates
var GetImplicitAnchorCandidates = cdp.Command[GetImplicitAnchorCandidatesParams, GetImplicitAnchorCandidatesResult]{Method: CommandGetImplicitAnchorCandidates}

// ForceShowInterestParams are the parameters of the command
// DOM.forceShowInterest.
type ForceShowInterestParams struct {
	NodeID cdp.NodeID `json:"nodeId"` // Id of the interest invoker HTMLElement.
	Enable bool       `json:"enable"` // If true, opens and holds interest. If false, releases forced interest.
}

// ForceShowInterest when enabling, this API forces an element to gain
// interest in its target, keeping interest active until disabled.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-forceShowInterest
var ForceShowInterest = cdp.Command[ForceShowInterestParams, cdp.Empty]{Method: CommandForceShowInterest}

// SetTextMarkerParams are the parameters of the command DOM.setTextMarker.
type SetTextMarkerParams struct {
	NodeID        cdp.NodeID             `json:"nodeId,omitempty,omitzero"`        // Identifier of the node.
	BackendNodeID cdp.BackendNodeID      `json:"backendNodeId,omitempty,omitzero"` // Identifier of the backend node.
	ObjectID      runtime.RemoteObjectID `json:"objectId,omitempty,omitzero"`      // JavaScript object id of the node wrapper.
	Type          SetTextMarkerType      `json:"type"`                             // The type of marker to set on the given range of text.
	Start         int64                  `json:"start"`                            // Start offset into the element's rendered text in UTF-16 code units. For a text control, an offset into the control's value. Offsets count text in DOM order and do not enter shadow trees. To mark text inside a shadow tree, pass the element inside the shadow tree.
	End           int64                  `json:"end"`                              // End offset (exclusive) in the same units and space as start.
}

// SetTextMarker sets a spelling or grammar error marker on the given range
// of text. See
// https://github.com/Igalia/explainers/blob/main/force-spelling-grammar-markers/README.md
// Note: exactly one between nodeId, backendNodeId and objectId should be passed
// to identify the node.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-setTextMarker
var SetTextMarker = cdp.Command[SetTextMarkerParams, cdp.Empty]{Method: CommandSetTextMarker}

// ClearTextMarkers clears the spelling and grammar error text markers
// overlapping the ranges set by setTextMarker in this session. These markers
// are also removed when the DOM domain is disabled or the session ends.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-clearTextMarkers
var ClearTextMarkers = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandClearTextMarkers}

// AttributeModified fired when Element's attribute is modified.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#event-attributeModified
var AttributeModified = cdp.Event[EventAttributeModified]{Method: "DOM.attributeModified"}

// AdoptedStyleSheetsModified fired when Element's adoptedStyleSheets are
// modified.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#event-adoptedStyleSheetsModified
var AdoptedStyleSheetsModified = cdp.Event[EventAdoptedStyleSheetsModified]{Method: "DOM.adoptedStyleSheetsModified"}

// AttributeRemoved fired when Element's attribute is removed.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#event-attributeRemoved
var AttributeRemoved = cdp.Event[EventAttributeRemoved]{Method: "DOM.attributeRemoved"}

// CharacterDataModified mirrors DOMCharacterDataModified event.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#event-characterDataModified
var CharacterDataModified = cdp.Event[EventCharacterDataModified]{Method: "DOM.characterDataModified"}

// ChildNodeCountUpdated fired when Container's child node count has changed.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#event-childNodeCountUpdated
var ChildNodeCountUpdated = cdp.Event[EventChildNodeCountUpdated]{Method: "DOM.childNodeCountUpdated"}

// ChildNodeInserted mirrors DOMNodeInserted event.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#event-childNodeInserted
var ChildNodeInserted = cdp.Event[EventChildNodeInserted]{Method: "DOM.childNodeInserted"}

// ChildNodeRemoved mirrors DOMNodeRemoved event.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#event-childNodeRemoved
var ChildNodeRemoved = cdp.Event[EventChildNodeRemoved]{Method: "DOM.childNodeRemoved"}

// DistributedNodesUpdated called when distribution is changed.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#event-distributedNodesUpdated
var DistributedNodesUpdated = cdp.Event[EventDistributedNodesUpdated]{Method: "DOM.distributedNodesUpdated"}

// DocumentUpdated fired when Document has been totally updated. Node ids are
// no longer valid.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#event-documentUpdated
var DocumentUpdated = cdp.Event[EventDocumentUpdated]{Method: "DOM.documentUpdated"}

// InlineStyleInvalidated fired when Element's inline style is modified via a
// CSS property modification.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#event-inlineStyleInvalidated
var InlineStyleInvalidated = cdp.Event[EventInlineStyleInvalidated]{Method: "DOM.inlineStyleInvalidated"}

// PseudoElementAdded called when a pseudo element is added to an element.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#event-pseudoElementAdded
var PseudoElementAdded = cdp.Event[EventPseudoElementAdded]{Method: "DOM.pseudoElementAdded"}

// TopLayerElementsUpdated called when top layer elements are changed.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#event-topLayerElementsUpdated
var TopLayerElementsUpdated = cdp.Event[EventTopLayerElementsUpdated]{Method: "DOM.topLayerElementsUpdated"}

// ScrollableFlagUpdated fired when a node's scrollability state changes.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#event-scrollableFlagUpdated
var ScrollableFlagUpdated = cdp.Event[EventScrollableFlagUpdated]{Method: "DOM.scrollableFlagUpdated"}

// AdRelatedStateUpdated fired when a node's ad related state changes.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#event-adRelatedStateUpdated
var AdRelatedStateUpdated = cdp.Event[EventAdRelatedStateUpdated]{Method: "DOM.adRelatedStateUpdated"}

// AffectedByStartingStylesFlagUpdated fired when a node's starting styles
// changes.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#event-affectedByStartingStylesFlagUpdated
var AffectedByStartingStylesFlagUpdated = cdp.Event[EventAffectedByStartingStylesFlagUpdated]{Method: "DOM.affectedByStartingStylesFlagUpdated"}

// PseudoElementRemoved called when a pseudo element is removed from an
// element.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#event-pseudoElementRemoved
var PseudoElementRemoved = cdp.Event[EventPseudoElementRemoved]{Method: "DOM.pseudoElementRemoved"}

// SetChildNodes fired when backend wants to provide client with the missing
// DOM structure. This happens upon most of the calls requesting node ids.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#event-setChildNodes
var SetChildNodes = cdp.Event[EventSetChildNodes]{Method: "DOM.setChildNodes"}

// ShadowRootPopped called when shadow root is popped from the element.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#event-shadowRootPopped
var ShadowRootPopped = cdp.Event[EventShadowRootPopped]{Method: "DOM.shadowRootPopped"}

// ShadowRootPushed called when shadow root is pushed into the element.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#event-shadowRootPushed
var ShadowRootPushed = cdp.Event[EventShadowRootPushed]{Method: "DOM.shadowRootPushed"}

// Command names.
const (
	CommandCollectClassNamesFromSubtree       = "DOM.collectClassNamesFromSubtree"
	CommandCopyTo                             = "DOM.copyTo"
	CommandDescribeNode                       = "DOM.describeNode"
	CommandScrollIntoViewIfNeeded             = "DOM.scrollIntoViewIfNeeded"
	CommandDisable                            = "DOM.disable"
	CommandDiscardSearchResults               = "DOM.discardSearchResults"
	CommandEnable                             = "DOM.enable"
	CommandFocus                              = "DOM.focus"
	CommandGetAttributes                      = "DOM.getAttributes"
	CommandGetBoxModel                        = "DOM.getBoxModel"
	CommandGetContentQuads                    = "DOM.getContentQuads"
	CommandGetDocument                        = "DOM.getDocument"
	CommandGetNodesForSubtreeByStyle          = "DOM.getNodesForSubtreeByStyle"
	CommandGetNodeForLocation                 = "DOM.getNodeForLocation"
	CommandGetOuterHTML                       = "DOM.getOuterHTML"
	CommandGetRelayoutBoundary                = "DOM.getRelayoutBoundary"
	CommandGetSearchResults                   = "DOM.getSearchResults"
	CommandMarkUndoableState                  = "DOM.markUndoableState"
	CommandMoveTo                             = "DOM.moveTo"
	CommandPerformSearch                      = "DOM.performSearch"
	CommandPushNodeByPathToFrontend           = "DOM.pushNodeByPathToFrontend"
	CommandPushNodesByBackendIDsToFrontend    = "DOM.pushNodesByBackendIdsToFrontend"
	CommandQuerySelector                      = "DOM.querySelector"
	CommandQuerySelectorAll                   = "DOM.querySelectorAll"
	CommandGetTopLayerElements                = "DOM.getTopLayerElements"
	CommandGetElementByRelation               = "DOM.getElementByRelation"
	CommandRedo                               = "DOM.redo"
	CommandRemoveAttribute                    = "DOM.removeAttribute"
	CommandRemoveNode                         = "DOM.removeNode"
	CommandRequestChildNodes                  = "DOM.requestChildNodes"
	CommandRequestNode                        = "DOM.requestNode"
	CommandResolveNode                        = "DOM.resolveNode"
	CommandSetAttributeValue                  = "DOM.setAttributeValue"
	CommandSetAttributesAsText                = "DOM.setAttributesAsText"
	CommandSetFileInputFiles                  = "DOM.setFileInputFiles"
	CommandSetNodeStackTracesEnabled          = "DOM.setNodeStackTracesEnabled"
	CommandGetNodeStackTraces                 = "DOM.getNodeStackTraces"
	CommandGetFileInfo                        = "DOM.getFileInfo"
	CommandGetDetachedDomNodes                = "DOM.getDetachedDomNodes"
	CommandSetInspectedNode                   = "DOM.setInspectedNode"
	CommandSetNodeName                        = "DOM.setNodeName"
	CommandSetNodeValue                       = "DOM.setNodeValue"
	CommandSetOuterHTML                       = "DOM.setOuterHTML"
	CommandUndo                               = "DOM.undo"
	CommandGetFrameOwner                      = "DOM.getFrameOwner"
	CommandGetContainerForNode                = "DOM.getContainerForNode"
	CommandGetQueryingDescendantsForContainer = "DOM.getQueryingDescendantsForContainer"
	CommandGetAnchorElement                   = "DOM.getAnchorElement"
	CommandForceShowPopover                   = "DOM.forceShowPopover"
	CommandGetImplicitAnchorCandidates        = "DOM.getImplicitAnchorCandidates"
	CommandForceShowInterest                  = "DOM.forceShowInterest"
	CommandSetTextMarker                      = "DOM.setTextMarker"
	CommandClearTextMarkers                   = "DOM.clearTextMarkers"
)
