package tracing

// Code generated by pdlgen. DO NOT EDIT.

// MemoryDumpConfig configuration for memory dump. Used only when
// "memory-infra" category is enabled.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Tracing#type-MemoryDumpConfig
type MemoryDumpConfig struct{}

// TraceConfig [no description].
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Tracing#type-TraceConfig
type TraceConfig struct {
	RecordMode           TraceConfigRecordMode `json:"recordMode,omitempty,omitzero"`          // Controls how the trace buffer stores data. The default is recordUntilFull.
	TraceBufferSizeInKb  float64               `json:"traceBufferSizeInKb,omitempty,omitzero"` // Size of the trace buffer in kilobytes. If not specified or zero is passed, a default value of 200 MB would be used.
	EnableSampling       bool                  `json:"enableSampling"`                         // Turns on JavaScript stack sampling.
	EnableSystrace       bool                  `json:"enableSystrace"`                         // Turns on system tracing.
	EnableArgumentFilter bool                  `json:"enableArgumentFilter"`                   // Turns on argument filter.
	IncludedCategories   []string              `json:"includedCategories,omitempty,omitzero"`  // Included category filters.
	ExcludedCategories   []string              `json:"excludedCategories,omitempty,omitzero"`  // Excluded category filters.
	SyntheticDelays      []string              `json:"syntheticDelays,omitempty,omitzero"`     // Configuration to synthesize the delays in tracing.
	MemoryDumpConfig     *MemoryDumpConfig     `json:"memoryDumpConfig,omitempty,omitzero"`    // Configuration for memory dump triggers. Used only when "memory-infra" category is enabled.
}

// StreamFormat data format of a trace. Can be either the legacy JSON format
// or the protocol buffer format. Note that the JSON format will be deprecated
// soon.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Tracing#type-StreamFormat
type StreamFormat string

// String returns the StreamFormat as string value.
func (t StreamFormat) String() string {
	return string(t)
}

// StreamFormat values.
const (
	StreamFormatJSON  StreamFormat = "json"
	StreamFormatProto StreamFormat = "proto"
)

// StreamCompression compression type to use for traces returned via streams.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Tracing#type-StreamCompression
type StreamCompression string

// String returns the StreamCompression as string value.
func (t StreamCompression) String() string {
	return string(t)
}

// StreamCompression values.
const (
	StreamCompressionNone StreamCompression = "none"
	StreamCompressionGzip StreamCompression = "gzip"
)

// MemoryDumpLevelOfDetail details exposed when memory request explicitly
// declared. Keep consistent with memory_dump_request_args.h and
// memory_instrumentation.mojom.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Tracing#type-MemoryDumpLevelOfDetail
type MemoryDumpLevelOfDetail string

// String returns the MemoryDumpLevelOfDetail as string value.
func (t MemoryDumpLevelOfDetail) String() string {
	return string(t)
}

// MemoryDumpLevelOfDetail values.
const (
	MemoryDumpLevelOfDetailBackground MemoryDumpLevelOfDetail = "background"
	MemoryDumpLevelOfDetailLight      MemoryDumpLevelOfDetail = "light"
	MemoryDumpLevelOfDetailDetailed   MemoryDumpLevelOfDetail = "detailed"
)

// Backend backend type to use for tracing. chrome uses the Chrome-integrated
// tracing service and is supported on all platforms. system is only supported
// on Chrome OS and uses the Perfetto system tracing service. auto chooses
// system when the perfettoConfig provided to Tracing.start specifies at least
// one non-Chrome data source; otherwise uses chrome.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Tracing#type-TracingBackend
type Backend string

// String returns the Backend as string value.
func (t Backend) String() string {
	return string(t)
}

// Backend values.
const (
	BackendAuto   Backend = "auto"
	BackendChrome Backend = "chrome"
	BackendSystem Backend = "system"
)

// TraceConfigRecordMode controls how the trace buffer stores data. The
// default is recordUntilFull.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Tracing#type-TraceConfig
type TraceConfigRecordMode string

// String returns the TraceConfigRecordMode as string value.
func (t TraceConfigRecordMode) String() string {
	return string(t)
}

// TraceConfigRecordMode values.
const (
	TraceConfigRecordModeRecordUntilFull        TraceConfigRecordMode = "recordUntilFull"
	TraceConfigRecordModeRecordContinuously     TraceConfigRecordMode = "recordContinuously"
	TraceConfigRecordModeRecordAsMuchAsPossible TraceConfigRecordMode = "recordAsMuchAsPossible"
	TraceConfigRecordModeEchoToConsole          TraceConfigRecordMode = "echoToConsole"
)

// StartTransferMode whether to report trace events as series of
// dataCollected events or to save trace to a stream (defaults to ReportEvents).
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Tracing#method-start
type StartTransferMode string

// String returns the StartTransferMode as string value.
func (t StartTransferMode) String() string {
	return string(t)
}

// StartTransferMode values.
const (
	StartTransferModeReportEvents   StartTransferMode = "ReportEvents"
	StartTransferModeReturnAsStream StartTransferMode = "ReturnAsStream"
)
