// Code generated by pdlgen. DO NOT EDIT.

// Package crashreportcontext provides the Chrome DevTools Protocol
// commands, types, and events for the CrashReportContext domain.
//
// This domain exposes the current state of the CrashReportContext API.
//
// Generated by the pdlgen command.
package crashreportcontext

import (
	"github.com/chromedp/cdproto/cdp"
)

// GetEntriesResult is the result of the command
// CrashReportContext.getEntries.
type GetEntriesResult struct {
	Entries []*Entry `json:"entries,omitempty,omitzero"`
}

// GetEntries returns all entries in the CrashReportContext across all frames
// in the page.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/CrashReportContext#method-getEntries
var GetEntries = cdp.Command[cdp.Empty, GetEntriesResult]{Method: CommandGetEntries}

// Command names.
const (
	CommandGetEntries = "CrashReportContext.getEntries"
)
