// Code generated by pdlgen. DO NOT EDIT.

// Package deviceorientation provides the Chrome DevTools Protocol
// commands, types, and events for the DeviceOrientation domain.
//
// Generated by the pdlgen command.
package deviceorientation

import (
	"github.com/chromedp/cdproto/cdp"
)

// ClearDeviceOrientationOverride clears the overridden Device Orientation.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DeviceOrientation#method-clearDeviceOrientationOverride
var ClearDeviceOrientationOverride = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandClearDeviceOrientationOverride}

// SetDeviceOrientationOverrideParams are the parameters of the command
// DeviceOrientation.setDeviceOrientationOverride.
type SetDeviceOrientationOverrideParams struct {
	Alpha float64 `json:"alpha"` // Mock alpha
	Beta  float64 `json:"beta"`  // Mock beta
	Gamma float64 `json:"gamma"` // Mock gamma
}

// SetDeviceOrientationOverride overrides the Device Orientation.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DeviceOrientation#method-setDeviceOrientationOverride
var SetDeviceOrientationOverride = cdp.Command[SetDeviceOrientationOverrideParams, cdp.Empty]{Method: CommandSetDeviceOrientationOverride}

// Command names.
const (
	CommandClearDeviceOrientationOverride = "DeviceOrientation.clearDeviceOrientationOverride"
	CommandSetDeviceOrientationOverride   = "DeviceOrientation.setDeviceOrientationOverride"
)
