// Code generated by pdlgen. DO NOT EDIT.

// Package inspector provides the Chrome DevTools Protocol
// commands, types, and events for the Inspector domain.
//
// Generated by the pdlgen command.
package inspector

import (
	"github.com/chromedp/cdproto/cdp"
)

// Disable disables inspector domain notifications.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Inspector#method-disable
var Disable = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandDisable}

// Enable enables inspector domain notifications.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Inspector#method-enable
var Enable = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandEnable}

// Detached fired when remote debugging connection is about to be terminated.
// Contains detach reason.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Inspector#event-detached
var Detached = cdp.Event[EventDetached]{Method: "Inspector.detached"}

// TargetCrashed fired when debugging target has crashed.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Inspector#event-targetCrashed
var TargetCrashed = cdp.Event[EventTargetCrashed]{Method: "Inspector.targetCrashed"}

// TargetReloadedAfterCrash fired when debugging target has reloaded after
// crash.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Inspector#event-targetReloadedAfterCrash
var TargetReloadedAfterCrash = cdp.Event[EventTargetReloadedAfterCrash]{Method: "Inspector.targetReloadedAfterCrash"}

// WorkerScriptLoaded fired on worker targets when main worker script and any
// imported scripts have been evaluated.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Inspector#event-workerScriptLoaded
var WorkerScriptLoaded = cdp.Event[EventWorkerScriptLoaded]{Method: "Inspector.workerScriptLoaded"}

// Command names.
const (
	CommandDisable = "Inspector.disable"
	CommandEnable  = "Inspector.enable"
)
