// Package har provides the Chrome DevTools Protocol
// commands, types, and events for the HAR domain.
//
// HTTP Archive Format.
//
// Generated by the pdlgen command.
package har

// Code generated by pdlgen. DO NOT EDIT.
