package audits

// Code generated by pdlgen. DO NOT EDIT.

// EventIssueAdded [no description].
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Audits#event-issueAdded
type EventIssueAdded struct {
	Issue *InspectorIssue `json:"issue"`
}
