// Code generated by pdlgen. DO NOT EDIT.

// Package debugger provides the Chrome DevTools Protocol
// commands, types, and events for the Debugger domain.
//
// Debugger domain exposes JavaScript debugging capabilities. It allows
// setting and removing breakpoints, stepping through execution, exploring stack
// traces, etc.
//
// Generated by the pdlgen command.
package debugger

import (
	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/runtime"
)

// ContinueToLocationParams are the parameters of the command
// Debugger.continueToLocation.
type ContinueToLocationParams struct {
	Location         *Location                          `json:"location"` // Location to continue to.
	TargetCallFrames ContinueToLocationTargetCallFrames `json:"targetCallFrames,omitempty,omitzero"`
}

// ContinueToLocation continues execution until specific location is reached.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-continueToLocation
var ContinueToLocation = cdp.Command[ContinueToLocationParams, cdp.Empty]{Method: CommandContinueToLocation}

// Disable disables debugger for given page.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-disable
var Disable = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandDisable}

// EnableParams are the parameters of the command Debugger.enable.
type EnableParams struct {
	MaxScriptsCacheSize float64 `json:"maxScriptsCacheSize,omitempty,omitzero"` // The maximum size in bytes of collected scripts (not referenced by other heap objects) the debugger can hold. Puts no limit if parameter is omitted.
}

// EnableResult is the result of the command Debugger.enable.
type EnableResult struct {
	DebuggerID cdp.UniqueDebuggerID `json:"debuggerId,omitempty,omitzero"` // Unique identifier of the debugger.
}

// Enable enables debugger for the given page. Clients should not assume that
// the debugging has been enabled until the result for this command is received.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-enable
var Enable = cdp.Command[EnableParams, EnableResult]{Method: CommandEnable}

// EvaluateOnCallFrameParams are the parameters of the command
// Debugger.evaluateOnCallFrame.
type EvaluateOnCallFrameParams struct {
	CallFrameID           CallFrameID       `json:"callFrameId"`                              // Call frame identifier to evaluate on.
	Expression            string            `json:"expression"`                               // Expression to evaluate.
	ObjectGroup           string            `json:"objectGroup,omitempty,omitzero"`           // String object group name to put result into (allows rapid releasing resulting object handles using releaseObjectGroup).
	IncludeCommandLineAPI *bool             `json:"includeCommandLineAPI,omitempty,omitzero"` // Specifies whether command line API should be available to the evaluated expression, defaults to false.
	Silent                *bool             `json:"silent,omitempty,omitzero"`                // In silent mode exceptions thrown during evaluation are not reported and do not pause execution. Overrides setPauseOnException state.
	ReturnByValue         *bool             `json:"returnByValue,omitempty,omitzero"`         // Whether the result is expected to be a JSON object that should be sent by value.
	GeneratePreview       *bool             `json:"generatePreview,omitempty,omitzero"`       // Whether preview should be generated for the result.
	ThrowOnSideEffect     *bool             `json:"throwOnSideEffect,omitempty,omitzero"`     // Whether to throw an exception if side effect cannot be ruled out during evaluation.
	Timeout               runtime.TimeDelta `json:"timeout,omitempty,omitzero"`               // Terminate execution after timing out (number of milliseconds).
	ScopeNumber           int64             `json:"scopeNumber,omitempty,omitzero"`           // Specifies the scope number to evaluate the expression in (default: 0, innermost scope).
}

// EvaluateOnCallFrameResult is the result of the command
// Debugger.evaluateOnCallFrame.
type EvaluateOnCallFrameResult struct {
	Result           *runtime.RemoteObject     `json:"result,omitempty,omitzero"`           // Object wrapper for the evaluation result.
	ExceptionDetails *runtime.ExceptionDetails `json:"exceptionDetails,omitempty,omitzero"` // Exception details.
}

// EvaluateOnCallFrame evaluates expression on a given call frame.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-evaluateOnCallFrame
var EvaluateOnCallFrame = cdp.Command[EvaluateOnCallFrameParams, EvaluateOnCallFrameResult]{Method: CommandEvaluateOnCallFrame}

// GetPossibleBreakpointsParams are the parameters of the command
// Debugger.getPossibleBreakpoints.
type GetPossibleBreakpointsParams struct {
	Start              *Location `json:"start"`                                 // Start of range to search possible breakpoint locations in.
	End                *Location `json:"end,omitempty,omitzero"`                // End of range to search possible breakpoint locations in (excluding). When not specified, end of scripts is used as end of range.
	RestrictToFunction *bool     `json:"restrictToFunction,omitempty,omitzero"` // Only consider locations which are in the same (non-nested) function as start.
}

// GetPossibleBreakpointsResult is the result of the command
// Debugger.getPossibleBreakpoints.
type GetPossibleBreakpointsResult struct {
	Locations []*BreakLocation `json:"locations,omitempty,omitzero"` // List of the possible breakpoint locations.
}

// GetPossibleBreakpoints returns possible locations for breakpoint. scriptId
// in start and end range locations should be the same.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-getPossibleBreakpoints
var GetPossibleBreakpoints = cdp.Command[GetPossibleBreakpointsParams, GetPossibleBreakpointsResult]{Method: CommandGetPossibleBreakpoints}

// GetScriptSourceParams are the parameters of the command
// Debugger.getScriptSource.
type GetScriptSourceParams struct {
	ScriptID cdp.ScriptID `json:"scriptId"` // Id of the script to get source for.
}

// GetScriptSourceResult is the result of the command
// Debugger.getScriptSource.
type GetScriptSourceResult struct {
	ScriptSource string `json:"scriptSource,omitempty,omitzero"` // Script source (empty in case of Wasm bytecode).
	Bytecode     []byte `json:"bytecode,omitempty,omitzero"`     // Wasm bytecode.
}

// GetScriptSource returns source for the script with given id.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-getScriptSource
var GetScriptSource = cdp.Command[GetScriptSourceParams, GetScriptSourceResult]{Method: CommandGetScriptSource}

// DisassembleWasmModuleParams are the parameters of the command
// Debugger.disassembleWasmModule.
type DisassembleWasmModuleParams struct {
	ScriptID cdp.ScriptID `json:"scriptId"` // Id of the script to disassemble
}

// DisassembleWasmModuleResult is the result of the command
// Debugger.disassembleWasmModule.
type DisassembleWasmModuleResult struct {
	StreamID            string                `json:"streamId,omitempty,omitzero"`            // For large modules, return a stream from which additional chunks of disassembly can be read successively.
	TotalNumberOfLines  int64                 `json:"totalNumberOfLines,omitempty,omitzero"`  // The total number of lines in the disassembly text.
	FunctionBodyOffsets []int64               `json:"functionBodyOffsets,omitempty,omitzero"` // The offsets of all function bodies, in the format [start1, end1, start2, end2, ...] where all ends are exclusive.
	Chunk               *WasmDisassemblyChunk `json:"chunk,omitempty,omitzero"`               // The first chunk of disassembly.
}

// DisassembleWasmModule [no description].
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-disassembleWasmModule
var DisassembleWasmModule = cdp.Command[DisassembleWasmModuleParams, DisassembleWasmModuleResult]{Method: CommandDisassembleWasmModule}

// NextWasmDisassemblyChunkParams are the parameters of the command
// Debugger.nextWasmDisassemblyChunk.
type NextWasmDisassemblyChunkParams struct {
	StreamID string `json:"streamId"`
}

// NextWasmDisassemblyChunkResult is the result of the command
// Debugger.nextWasmDisassemblyChunk.
type NextWasmDisassemblyChunkResult struct {
	Chunk *WasmDisassemblyChunk `json:"chunk,omitempty,omitzero"` // The next chunk of disassembly.
}

// NextWasmDisassemblyChunk disassemble the next chunk of lines for the
// module corresponding to the stream. If disassembly is complete, this API will
// invalidate the streamId and return an empty chunk. Any subsequent calls for
// the now invalid stream will return errors.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-nextWasmDisassemblyChunk
var NextWasmDisassemblyChunk = cdp.Command[NextWasmDisassemblyChunkParams, NextWasmDisassemblyChunkResult]{Method: CommandNextWasmDisassemblyChunk}

// GetStackTraceParams are the parameters of the command
// Debugger.getStackTrace.
type GetStackTraceParams struct {
	StackTraceID *runtime.StackTraceID `json:"stackTraceId"`
}

// GetStackTraceResult is the result of the command Debugger.getStackTrace.
type GetStackTraceResult struct {
	StackTrace *runtime.StackTrace `json:"stackTrace,omitempty,omitzero"`
}

// GetStackTrace returns stack trace with given stackTraceId.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-getStackTrace
var GetStackTrace = cdp.Command[GetStackTraceParams, GetStackTraceResult]{Method: CommandGetStackTrace}

// Pause stops on the next JavaScript statement.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-pause
var Pause = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandPause}

// RemoveBreakpointParams are the parameters of the command
// Debugger.removeBreakpoint.
type RemoveBreakpointParams struct {
	BreakpointID BreakpointID `json:"breakpointId"`
}

// RemoveBreakpoint removes JavaScript breakpoint.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-removeBreakpoint
var RemoveBreakpoint = cdp.Command[RemoveBreakpointParams, cdp.Empty]{Method: CommandRemoveBreakpoint}

// RestartFrameParams are the parameters of the command
// Debugger.restartFrame.
type RestartFrameParams struct {
	CallFrameID CallFrameID      `json:"callFrameId"`             // Call frame identifier to evaluate on.
	Mode        RestartFrameMode `json:"mode,omitempty,omitzero"` // The mode parameter must be present and set to 'StepInto', otherwise restartFrame will error out.
}

// RestartFrame restarts particular call frame from the beginning. The old,
// deprecated behavior of restartFrame is to stay paused and allow further CDP
// commands after a restart was scheduled. This can cause problems with
// restarting, so we now continue execution immediately after it has been
// scheduled until we reach the beginning of the restarted frame. To stay
// back-wards compatible, restartFrame now expects a mode parameter to be
// present. If the mode parameter is missing, restartFrame errors out. The
// various return values are deprecated and callFrames is always empty. Use the
// call frames from the Debugger#paused events instead, that fires once V8
// pauses at the beginning of the restarted function.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-restartFrame
var RestartFrame = cdp.Command[RestartFrameParams, cdp.Empty]{Method: CommandRestartFrame}

// ResumeParams are the parameters of the command Debugger.resume.
type ResumeParams struct {
	TerminateOnResume *bool `json:"terminateOnResume,omitempty,omitzero"` // Set to true to terminate execution upon resuming execution. In contrast to Runtime.terminateExecution, this will allows to execute further JavaScript (i.e. via evaluation) until execution of the paused code is actually resumed, at which point termination is triggered. If execution is currently not paused, this parameter has no effect.
}

// Resume resumes JavaScript execution.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-resume
var Resume = cdp.Command[ResumeParams, cdp.Empty]{Method: CommandResume}

// SearchInContentParams are the parameters of the command
// Debugger.searchInContent.
type SearchInContentParams struct {
	ScriptID      cdp.ScriptID `json:"scriptId"`                         // Id of the script to search in.
	Query         string       `json:"query"`                            // String to search for.
	CaseSensitive *bool        `json:"caseSensitive,omitempty,omitzero"` // If true, search is case sensitive.
	IsRegex       *bool        `json:"isRegex,omitempty,omitzero"`       // If true, treats string parameter as regex.
}

// SearchInContentResult is the result of the command
// Debugger.searchInContent.
type SearchInContentResult struct {
	Result []*SearchMatch `json:"result,omitempty,omitzero"` // List of search matches.
}

// SearchInContent searches for given string in script content.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-searchInContent
var SearchInContent = cdp.Command[SearchInContentParams, SearchInContentResult]{Method: CommandSearchInContent}

// SetAsyncCallStackDepthParams are the parameters of the command
// Debugger.setAsyncCallStackDepth.
type SetAsyncCallStackDepthParams struct {
	MaxDepth int64 `json:"maxDepth"` // Maximum depth of async call stacks. Setting to 0 will effectively disable collecting async call stacks (default).
}

// SetAsyncCallStackDepth enables or disables async call stacks tracking.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-setAsyncCallStackDepth
var SetAsyncCallStackDepth = cdp.Command[SetAsyncCallStackDepthParams, cdp.Empty]{Method: CommandSetAsyncCallStackDepth}

// SetBlackboxExecutionContextsParams are the parameters of the command
// Debugger.setBlackboxExecutionContexts.
type SetBlackboxExecutionContextsParams struct {
	UniqueIDs []string `json:"uniqueIds"` // Array of execution context unique ids for the debugger to ignore.
}

// SetBlackboxExecutionContexts replace previous blackbox execution contexts
// with passed ones. Forces backend to skip stepping/pausing in scripts in these
// execution contexts. VM will try to leave blackboxed script by performing
// 'step in' several times, finally resorting to 'step out' if unsuccessful.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-setBlackboxExecutionContexts
var SetBlackboxExecutionContexts = cdp.Command[SetBlackboxExecutionContextsParams, cdp.Empty]{Method: CommandSetBlackboxExecutionContexts}

// SetBlackboxPatternsParams are the parameters of the command
// Debugger.setBlackboxPatterns.
type SetBlackboxPatternsParams struct {
	Patterns      []string `json:"patterns"`                         // Array of regexps that will be used to check script url for blackbox state.
	SkipAnonymous *bool    `json:"skipAnonymous,omitempty,omitzero"` // If true, also ignore scripts with no source url.
}

// SetBlackboxPatterns replace previous blackbox patterns with passed ones.
// Forces backend to skip stepping/pausing in scripts with url matching one of
// the patterns. VM will try to leave blackboxed script by performing 'step in'
// several times, finally resorting to 'step out' if unsuccessful.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-setBlackboxPatterns
var SetBlackboxPatterns = cdp.Command[SetBlackboxPatternsParams, cdp.Empty]{Method: CommandSetBlackboxPatterns}

// SetBlackboxedRangesParams are the parameters of the command
// Debugger.setBlackboxedRanges.
type SetBlackboxedRangesParams struct {
	ScriptID  cdp.ScriptID      `json:"scriptId"` // Id of the script.
	Positions []*ScriptPosition `json:"positions"`
}

// SetBlackboxedRanges makes backend skip steps in the script in blackboxed
// ranges. VM will try leave blacklisted scripts by performing 'step in' several
// times, finally resorting to 'step out' if unsuccessful. Positions array
// contains positions where blackbox state is changed. First interval isn't
// blackboxed. Array should be sorted.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-setBlackboxedRanges
var SetBlackboxedRanges = cdp.Command[SetBlackboxedRangesParams, cdp.Empty]{Method: CommandSetBlackboxedRanges}

// SetBreakpointParams are the parameters of the command
// Debugger.setBreakpoint.
type SetBreakpointParams struct {
	Location  *Location `json:"location"`                     // Location to set breakpoint in.
	Condition string    `json:"condition,omitempty,omitzero"` // Expression to use as a breakpoint condition. When specified, debugger will only stop on the breakpoint if this expression evaluates to true.
}

// SetBreakpointResult is the result of the command Debugger.setBreakpoint.
type SetBreakpointResult struct {
	BreakpointID   BreakpointID `json:"breakpointId,omitempty,omitzero"`   // Id of the created breakpoint for further reference.
	ActualLocation *Location    `json:"actualLocation,omitempty,omitzero"` // Location this breakpoint resolved into.
}

// SetBreakpoint sets JavaScript breakpoint at a given location.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-setBreakpoint
var SetBreakpoint = cdp.Command[SetBreakpointParams, SetBreakpointResult]{Method: CommandSetBreakpoint}

// SetInstrumentationBreakpointParams are the parameters of the command
// Debugger.setInstrumentationBreakpoint.
type SetInstrumentationBreakpointParams struct {
	Instrumentation SetInstrumentationBreakpointInstrumentation `json:"instrumentation"` // Instrumentation name.
}

// SetInstrumentationBreakpointResult is the result of the command
// Debugger.setInstrumentationBreakpoint.
type SetInstrumentationBreakpointResult struct {
	BreakpointID BreakpointID `json:"breakpointId,omitempty,omitzero"` // Id of the created breakpoint for further reference.
}

// SetInstrumentationBreakpoint sets instrumentation breakpoint.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-setInstrumentationBreakpoint
var SetInstrumentationBreakpoint = cdp.Command[SetInstrumentationBreakpointParams, SetInstrumentationBreakpointResult]{Method: CommandSetInstrumentationBreakpoint}

// SetBreakpointByURLParams are the parameters of the command
// Debugger.setBreakpointByUrl.
type SetBreakpointByURLParams struct {
	LineNumber   int64  `json:"lineNumber"`                      // Line number to set breakpoint at.
	URL          string `json:"url,omitempty,omitzero"`          // URL of the resources to set breakpoint on.
	URLRegex     string `json:"urlRegex,omitempty,omitzero"`     // Regex pattern for the URLs of the resources to set breakpoints on. Either url or urlRegex must be specified.
	ScriptHash   string `json:"scriptHash,omitempty,omitzero"`   // Script hash of the resources to set breakpoint on.
	ColumnNumber *int64 `json:"columnNumber,omitempty,omitzero"` // Offset in the line to set breakpoint at.
	Condition    string `json:"condition,omitempty,omitzero"`    // Expression to use as a breakpoint condition. When specified, debugger will only stop on the breakpoint if this expression evaluates to true.
}

// SetBreakpointByURLResult is the result of the command
// Debugger.setBreakpointByUrl.
type SetBreakpointByURLResult struct {
	BreakpointID BreakpointID `json:"breakpointId,omitempty,omitzero"` // Id of the created breakpoint for further reference.
	Locations    []*Location  `json:"locations,omitempty,omitzero"`    // List of the locations this breakpoint resolved into upon addition.
}

// SetBreakpointByURL sets JavaScript breakpoint at given location specified
// either by URL or URL regex. Once this command is issued, all existing parsed
// scripts will have breakpoints resolved and returned in locations property.
// Further matching script parsing will result in subsequent breakpointResolved
// events issued. This logical breakpoint will survive page reloads.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-setBreakpointByUrl
var SetBreakpointByURL = cdp.Command[SetBreakpointByURLParams, SetBreakpointByURLResult]{Method: CommandSetBreakpointByURL}

// SetBreakpointOnFunctionCallParams are the parameters of the command
// Debugger.setBreakpointOnFunctionCall.
type SetBreakpointOnFunctionCallParams struct {
	ObjectID  runtime.RemoteObjectID `json:"objectId"`                     // Function object id.
	Condition string                 `json:"condition,omitempty,omitzero"` // Expression to use as a breakpoint condition. When specified, debugger will stop on the breakpoint if this expression evaluates to true.
}

// SetBreakpointOnFunctionCallResult is the result of the command
// Debugger.setBreakpointOnFunctionCall.
type SetBreakpointOnFunctionCallResult struct {
	BreakpointID BreakpointID `json:"breakpointId,omitempty,omitzero"` // Id of the created breakpoint for further reference.
}

// SetBreakpointOnFunctionCall sets JavaScript breakpoint before each call to
// the given function. If another function was created from the same source as a
// given one, calling it will also trigger the breakpoint.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-setBreakpointOnFunctionCall
var SetBreakpointOnFunctionCall = cdp.Command[SetBreakpointOnFunctionCallParams, SetBreakpointOnFunctionCallResult]{Method: CommandSetBreakpointOnFunctionCall}

// SetBreakpointsActiveParams are the parameters of the command
// Debugger.setBreakpointsActive.
type SetBreakpointsActiveParams struct {
	Active bool `json:"active"` // New value for breakpoints active state.
}

// SetBreakpointsActive activates / deactivates all breakpoints on the page.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-setBreakpointsActive
var SetBreakpointsActive = cdp.Command[SetBreakpointsActiveParams, cdp.Empty]{Method: CommandSetBreakpointsActive}

// SetPauseOnExceptionsParams are the parameters of the command
// Debugger.setPauseOnExceptions.
type SetPauseOnExceptionsParams struct {
	State SetPauseOnExceptionsState `json:"state"` // Pause on exceptions mode.
}

// SetPauseOnExceptions defines pause on exceptions state. Can be set to stop
// on all exceptions, uncaught exceptions, or caught exceptions, no exceptions.
// Initial pause on exceptions state is none.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-setPauseOnExceptions
var SetPauseOnExceptions = cdp.Command[SetPauseOnExceptionsParams, cdp.Empty]{Method: CommandSetPauseOnExceptions}

// SetReturnValueParams are the parameters of the command
// Debugger.setReturnValue.
type SetReturnValueParams struct {
	NewValue *runtime.CallArgument `json:"newValue"` // New return value.
}

// SetReturnValue changes return value in top frame. Available only at return
// break position.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-setReturnValue
var SetReturnValue = cdp.Command[SetReturnValueParams, cdp.Empty]{Method: CommandSetReturnValue}

// SetSkipAllPausesParams are the parameters of the command
// Debugger.setSkipAllPauses.
type SetSkipAllPausesParams struct {
	Skip bool `json:"skip"` // New value for skip pauses state.
}

// SetSkipAllPauses makes page not interrupt on any pauses (breakpoint,
// exception, dom exception etc).
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-setSkipAllPauses
var SetSkipAllPauses = cdp.Command[SetSkipAllPausesParams, cdp.Empty]{Method: CommandSetSkipAllPauses}

// SetVariableValueParams are the parameters of the command
// Debugger.setVariableValue.
type SetVariableValueParams struct {
	ScopeNumber  int64                 `json:"scopeNumber"`  // 0-based number of scope as was listed in scope chain. Only 'local', 'closure' and 'catch' scope types are allowed. Other scopes could be manipulated manually.
	VariableName string                `json:"variableName"` // Variable name.
	NewValue     *runtime.CallArgument `json:"newValue"`     // New variable value.
	CallFrameID  CallFrameID           `json:"callFrameId"`  // Id of callframe that holds variable.
}

// SetVariableValue changes value of variable in a callframe. Object-based
// scopes are not supported and must be mutated manually.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-setVariableValue
var SetVariableValue = cdp.Command[SetVariableValueParams, cdp.Empty]{Method: CommandSetVariableValue}

// StepIntoParams are the parameters of the command Debugger.stepInto.
type StepIntoParams struct {
	BreakOnAsyncCall *bool            `json:"breakOnAsyncCall,omitempty,omitzero"` // Debugger will pause on the execution of the first async task which was scheduled before next pause.
	SkipList         []*LocationRange `json:"skipList,omitempty,omitzero"`         // The skipList specifies location ranges that should be skipped on step into.
}

// StepInto steps into the function call.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-stepInto
var StepInto = cdp.Command[StepIntoParams, cdp.Empty]{Method: CommandStepInto}

// StepOut steps out of the function call.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-stepOut
var StepOut = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandStepOut}

// StepOverParams are the parameters of the command Debugger.stepOver.
type StepOverParams struct {
	SkipList []*LocationRange `json:"skipList,omitempty,omitzero"` // The skipList specifies location ranges that should be skipped on step over.
}

// StepOver steps over the statement.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-stepOver
var StepOver = cdp.Command[StepOverParams, cdp.Empty]{Method: CommandStepOver}

// Paused fired when the virtual machine stopped on breakpoint or exception
// or any other stop criteria.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#event-paused
var Paused = cdp.Event[EventPaused]{Method: "Debugger.paused"}

// Resumed fired when the virtual machine resumed execution.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#event-resumed
var Resumed = cdp.Event[EventResumed]{Method: "Debugger.resumed"}

// ScriptFailedToParse fired when virtual machine fails to parse the script.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#event-scriptFailedToParse
var ScriptFailedToParse = cdp.Event[EventScriptFailedToParse]{Method: "Debugger.scriptFailedToParse"}

// ScriptParsed fired when virtual machine parses script. This event is also
// fired for all known and uncollected scripts upon enabling debugger.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#event-scriptParsed
var ScriptParsed = cdp.Event[EventScriptParsed]{Method: "Debugger.scriptParsed"}

// Command names.
const (
	CommandContinueToLocation           = "Debugger.continueToLocation"
	CommandDisable                      = "Debugger.disable"
	CommandEnable                       = "Debugger.enable"
	CommandEvaluateOnCallFrame          = "Debugger.evaluateOnCallFrame"
	CommandGetPossibleBreakpoints       = "Debugger.getPossibleBreakpoints"
	CommandGetScriptSource              = "Debugger.getScriptSource"
	CommandDisassembleWasmModule        = "Debugger.disassembleWasmModule"
	CommandNextWasmDisassemblyChunk     = "Debugger.nextWasmDisassemblyChunk"
	CommandGetStackTrace                = "Debugger.getStackTrace"
	CommandPause                        = "Debugger.pause"
	CommandRemoveBreakpoint             = "Debugger.removeBreakpoint"
	CommandRestartFrame                 = "Debugger.restartFrame"
	CommandResume                       = "Debugger.resume"
	CommandSearchInContent              = "Debugger.searchInContent"
	CommandSetAsyncCallStackDepth       = "Debugger.setAsyncCallStackDepth"
	CommandSetBlackboxExecutionContexts = "Debugger.setBlackboxExecutionContexts"
	CommandSetBlackboxPatterns          = "Debugger.setBlackboxPatterns"
	CommandSetBlackboxedRanges          = "Debugger.setBlackboxedRanges"
	CommandSetBreakpoint                = "Debugger.setBreakpoint"
	CommandSetInstrumentationBreakpoint = "Debugger.setInstrumentationBreakpoint"
	CommandSetBreakpointByURL           = "Debugger.setBreakpointByUrl"
	CommandSetBreakpointOnFunctionCall  = "Debugger.setBreakpointOnFunctionCall"
	CommandSetBreakpointsActive         = "Debugger.setBreakpointsActive"
	CommandSetPauseOnExceptions         = "Debugger.setPauseOnExceptions"
	CommandSetReturnValue               = "Debugger.setReturnValue"
	CommandSetSkipAllPauses             = "Debugger.setSkipAllPauses"
	CommandSetVariableValue             = "Debugger.setVariableValue"
	CommandStepInto                     = "Debugger.stepInto"
	CommandStepOut                      = "Debugger.stepOut"
	CommandStepOver                     = "Debugger.stepOver"
)
