// Code generated by pdlgen. DO NOT EDIT.

// Package domsnapshot provides the Chrome DevTools Protocol
// commands, types, and events for the DOMSnapshot domain.
//
// This domain facilitates obtaining document snapshots with DOM, layout, and
// style information.
//
// Generated by the pdlgen command.
package domsnapshot

import (
	"github.com/chromedp/cdproto/cdp"
)

// Disable disables DOM snapshot agent for the given page.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOMSnapshot#method-disable
var Disable = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandDisable}

// Enable enables DOM snapshot agent for the given page.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOMSnapshot#method-enable
var Enable = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandEnable}

// CaptureSnapshotParams are the parameters of the command
// DOMSnapshot.captureSnapshot.
type CaptureSnapshotParams struct {
	ComputedStyles                 []string `json:"computedStyles"`                                    // Whitelist of computed styles to return.
	IncludePaintOrder              *bool    `json:"includePaintOrder,omitempty,omitzero"`              // Whether to include layout object paint orders into the snapshot.
	IncludeDOMRects                *bool    `json:"includeDOMRects,omitempty,omitzero"`                // Whether to include DOM rectangles (offsetRects, clientRects, scrollRects) into the snapshot
	IncludeBlendedBackgroundColors *bool    `json:"includeBlendedBackgroundColors,omitempty,omitzero"` // Whether to include blended background colors in the snapshot (default: false). Blended background color is achieved by blending background colors of all elements that overlap with the current element.
	IncludeTextColorOpacities      *bool    `json:"includeTextColorOpacities,omitempty,omitzero"`      // Whether to include text color opacity in the snapshot (default: false). An element might have the opacity property set that affects the text color of the element. The final text color opacity is computed based on the opacity of all overlapping elements.
}

// CaptureSnapshotResult is the result of the command
// DOMSnapshot.captureSnapshot.
type CaptureSnapshotResult struct {
	Documents []*DocumentSnapshot `json:"documents,omitempty,omitzero"` // The nodes in the DOM tree. The DOMNode at index 0 corresponds to the root document.
	Strings   []string            `json:"strings,omitempty,omitzero"`   // Shared string table that all string properties refer to with indexes.
}

// CaptureSnapshot returns a document snapshot, including the full DOM tree
// of the root node (including iframes, template contents, and imported
// documents) in a flattened array, as well as layout and white-listed computed
// style information for the nodes. Shadow DOM in the returned DOM tree is
// flattened.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOMSnapshot#method-captureSnapshot
var CaptureSnapshot = cdp.Command[CaptureSnapshotParams, CaptureSnapshotResult]{Method: CommandCaptureSnapshot}

// Command names.
const (
	CommandDisable         = "DOMSnapshot.disable"
	CommandEnable          = "DOMSnapshot.enable"
	CommandCaptureSnapshot = "DOMSnapshot.captureSnapshot"
)
