// Code generated by pdlgen. DO NOT EDIT.

// Package accessibility provides the Chrome DevTools Protocol
// commands, types, and events for the Accessibility domain.
//
// Generated by the pdlgen command.
package accessibility

import (
	"github.com/chromedp/cdproto/cdp"
	"github.com/chromedp/cdproto/runtime"
)

// Disable disables the accessibility domain.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Accessibility#method-disable
var Disable = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandDisable}

// Enable enables the accessibility domain which causes AXNodeIds to remain
// consistent between method calls. This turns on accessibility for the page,
// which can impact performance until accessibility is disabled.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Accessibility#method-enable
var Enable = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandEnable}

// GetPartialAXTreeParams are the parameters of the command
// Accessibility.getPartialAXTree.
type GetPartialAXTreeParams struct {
	NodeID         cdp.NodeID             `json:"nodeId,omitempty,omitzero"`         // Identifier of the node to get the partial accessibility tree for.
	BackendNodeID  cdp.BackendNodeID      `json:"backendNodeId,omitempty,omitzero"`  // Identifier of the backend node to get the partial accessibility tree for.
	ObjectID       runtime.RemoteObjectID `json:"objectId,omitempty,omitzero"`       // JavaScript object id of the node wrapper to get the partial accessibility tree for.
	FetchRelatives *bool                  `json:"fetchRelatives,omitempty,omitzero"` // Whether to fetch this node's ancestors, siblings and children. Defaults to true.
}

// GetPartialAXTreeResult is the result of the command
// Accessibility.getPartialAXTree.
type GetPartialAXTreeResult struct {
	Nodes []*Node `json:"nodes,omitempty,omitzero"` // The Accessibility.AXNode for this DOM node, if it exists, plus its ancestors, siblings and children, if requested.
}

// GetPartialAXTree fetches the accessibility node and partial accessibility
// tree for this DOM node, if it exists.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Accessibility#method-getPartialAXTree
var GetPartialAXTree = cdp.Command[GetPartialAXTreeParams, GetPartialAXTreeResult]{Method: CommandGetPartialAXTree}

// GetFullAXTreeParams are the parameters of the command
// Accessibility.getFullAXTree.
type GetFullAXTreeParams struct {
	Depth   int64       `json:"depth,omitempty,omitzero"`   // The maximum depth at which descendants of the root node should be retrieved. If omitted, the full tree is returned.
	FrameID cdp.FrameID `json:"frameId,omitempty,omitzero"` // The frame for whose document the AX tree should be retrieved. If omitted, the root frame is used.
}

// GetFullAXTreeResult is the result of the command
// Accessibility.getFullAXTree.
type GetFullAXTreeResult struct {
	Nodes []*Node `json:"nodes,omitempty,omitzero"`
}

// GetFullAXTree fetches the entire accessibility tree for the root Document.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Accessibility#method-getFullAXTree
var GetFullAXTree = cdp.Command[GetFullAXTreeParams, GetFullAXTreeResult]{Method: CommandGetFullAXTree}

// GetRootAXNodeParams are the parameters of the command
// Accessibility.getRootAXNode.
type GetRootAXNodeParams struct {
	FrameID cdp.FrameID `json:"frameId,omitempty,omitzero"` // The frame in whose document the node resides. If omitted, the root frame is used.
}

// GetRootAXNodeResult is the result of the command
// Accessibility.getRootAXNode.
type GetRootAXNodeResult struct {
	Node *Node `json:"node,omitempty,omitzero"`
}

// GetRootAXNode fetches the root node. Requires enable() to have been called
// previously.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Accessibility#method-getRootAXNode
var GetRootAXNode = cdp.Command[GetRootAXNodeParams, GetRootAXNodeResult]{Method: CommandGetRootAXNode}

// GetAXNodeAndAncestorsParams are the parameters of the command
// Accessibility.getAXNodeAndAncestors.
type GetAXNodeAndAncestorsParams struct {
	NodeID        cdp.NodeID             `json:"nodeId,omitempty,omitzero"`        // Identifier of the node to get.
	BackendNodeID cdp.BackendNodeID      `json:"backendNodeId,omitempty,omitzero"` // Identifier of the backend node to get.
	ObjectID      runtime.RemoteObjectID `json:"objectId,omitempty,omitzero"`      // JavaScript object id of the node wrapper to get.
}

// GetAXNodeAndAncestorsResult is the result of the command
// Accessibility.getAXNodeAndAncestors.
type GetAXNodeAndAncestorsResult struct {
	Nodes []*Node `json:"nodes,omitempty,omitzero"`
}

// GetAXNodeAndAncestors fetches a node and all ancestors up to and including
// the root. Requires enable() to have been called previously.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Accessibility#method-getAXNodeAndAncestors
var GetAXNodeAndAncestors = cdp.Command[GetAXNodeAndAncestorsParams, GetAXNodeAndAncestorsResult]{Method: CommandGetAXNodeAndAncestors}

// GetChildAXNodesParams are the parameters of the command
// Accessibility.getChildAXNodes.
type GetChildAXNodesParams struct {
	ID      NodeID      `json:"id"`
	FrameID cdp.FrameID `json:"frameId,omitempty,omitzero"` // The frame in whose document the node resides. If omitted, the root frame is used.
}

// GetChildAXNodesResult is the result of the command
// Accessibility.getChildAXNodes.
type GetChildAXNodesResult struct {
	Nodes []*Node `json:"nodes,omitempty,omitzero"`
}

// GetChildAXNodes fetches a particular accessibility node by AXNodeId.
// Requires enable() to have been called previously.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Accessibility#method-getChildAXNodes
var GetChildAXNodes = cdp.Command[GetChildAXNodesParams, GetChildAXNodesResult]{Method: CommandGetChildAXNodes}

// QueryAXTreeParams are the parameters of the command
// Accessibility.queryAXTree.
type QueryAXTreeParams struct {
	NodeID         cdp.NodeID             `json:"nodeId,omitempty,omitzero"`         // Identifier of the node for the root to query.
	BackendNodeID  cdp.BackendNodeID      `json:"backendNodeId,omitempty,omitzero"`  // Identifier of the backend node for the root to query.
	ObjectID       runtime.RemoteObjectID `json:"objectId,omitempty,omitzero"`       // JavaScript object id of the node wrapper for the root to query.
	AccessibleName string                 `json:"accessibleName,omitempty,omitzero"` // Find nodes with this computed name.
	Role           string                 `json:"role,omitempty,omitzero"`           // Find nodes with this computed role.
}

// QueryAXTreeResult is the result of the command Accessibility.queryAXTree.
type QueryAXTreeResult struct {
	Nodes []*Node `json:"nodes,omitempty,omitzero"` // A list of Accessibility.AXNode matching the specified attributes, including nodes that are ignored for accessibility.
}

// QueryAXTree query a DOM node's accessibility subtree for accessible name
// and role. This command computes the name and role for all nodes in the
// subtree, including those that are ignored for accessibility, and returns
// those that match the specified name and role. If no DOM node is specified, or
// the DOM node does not exist, the command returns an error. If neither
// accessibleName or role is specified, it returns all the accessibility nodes
// in the subtree.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Accessibility#method-queryAXTree
var QueryAXTree = cdp.Command[QueryAXTreeParams, QueryAXTreeResult]{Method: CommandQueryAXTree}

// LoadComplete the loadComplete event mirrors the load complete event sent
// by the browser to assistive technology when the web page has finished
// loading.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Accessibility#event-loadComplete
var LoadComplete = cdp.Event[EventLoadComplete]{Method: "Accessibility.loadComplete"}

// NodesUpdated the nodesUpdated event is sent every time a previously
// requested node has changed the in tree.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Accessibility#event-nodesUpdated
var NodesUpdated = cdp.Event[EventNodesUpdated]{Method: "Accessibility.nodesUpdated"}

// Command names.
const (
	CommandDisable               = "Accessibility.disable"
	CommandEnable                = "Accessibility.enable"
	CommandGetPartialAXTree      = "Accessibility.getPartialAXTree"
	CommandGetFullAXTree         = "Accessibility.getFullAXTree"
	CommandGetRootAXNode         = "Accessibility.getRootAXNode"
	CommandGetAXNodeAndAncestors = "Accessibility.getAXNodeAndAncestors"
	CommandGetChildAXNodes       = "Accessibility.getChildAXNodes"
	CommandQueryAXTree           = "Accessibility.queryAXTree"
)
