// Code generated by pdlgen. DO NOT EDIT.

// Package page provides the Chrome DevTools Protocol
// commands, types, and events for the Page domain.
//
// Actions and events related to the inspected page belong to the page
// domain.
//
// Generated by the pdlgen command.
package page

import (
	"encoding/base64"
	"fmt"

	"github.com/chromedp/cdproto/cdp"
	jsonv2 "github.com/chromedp/cdproto/cdp/jsonv2"
	"github.com/chromedp/cdproto/debugger"
	"github.com/chromedp/cdproto/dom"
	"github.com/chromedp/cdproto/io"
	"github.com/chromedp/cdproto/runtime"
)

// AddScriptToEvaluateOnNewDocumentParams are the parameters of the command
// Page.addScriptToEvaluateOnNewDocument.
type AddScriptToEvaluateOnNewDocumentParams struct {
	Source                string `json:"source"`
	WorldName             string `json:"worldName,omitempty,omitzero"`             // If specified, creates an isolated world with the given name and evaluates given script in it. This world name will be used as the ExecutionContextDescription::name when the corresponding event is emitted.
	IncludeCommandLineAPI *bool  `json:"includeCommandLineAPI,omitempty,omitzero"` // Specifies whether command line API should be available to the script, defaults to false.
	RunImmediately        *bool  `json:"runImmediately,omitempty,omitzero"`        // If true, runs the script immediately on existing execution contexts or worlds. Default: false.
}

// AddScriptToEvaluateOnNewDocumentResult is the result of the command
// Page.addScriptToEvaluateOnNewDocument.
type AddScriptToEvaluateOnNewDocumentResult struct {
	Identifier ScriptIdentifier `json:"identifier,omitempty,omitzero"` // Identifier of the added script.
}

// AddScriptToEvaluateOnNewDocument evaluates given script in every frame
// upon creation (before loading frame's scripts).
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-addScriptToEvaluateOnNewDocument
var AddScriptToEvaluateOnNewDocument = cdp.Command[AddScriptToEvaluateOnNewDocumentParams, AddScriptToEvaluateOnNewDocumentResult]{Method: CommandAddScriptToEvaluateOnNewDocument}

// BringToFront brings page to front (activates tab).
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-bringToFront
var BringToFront = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandBringToFront}

// CaptureScreenshotParams are the parameters of the command
// Page.captureScreenshot.
type CaptureScreenshotParams struct {
	Format                CaptureScreenshotFormat `json:"format,omitempty,omitzero"`                // Image compression format (defaults to png).
	Quality               *int64                  `json:"quality,omitempty,omitzero"`               // Compression quality from range [0..100] (jpeg only).
	Clip                  *Viewport               `json:"clip,omitempty,omitzero"`                  // Capture the screenshot of a given region only.
	FromSurface           *bool                   `json:"fromSurface,omitempty,omitzero"`           // Capture the screenshot from the surface, rather than the view. Defaults to true.
	CaptureBeyondViewport *bool                   `json:"captureBeyondViewport,omitempty,omitzero"` // Capture the screenshot beyond the viewport. Defaults to false.
	OptimizeForSpeed      *bool                   `json:"optimizeForSpeed,omitempty,omitzero"`      // Optimize image encoding for speed, not for resulting size (defaults to false)
}

// CaptureScreenshotResult is the result of the command
// Page.captureScreenshot.
type CaptureScreenshotResult struct {
	Data []byte `json:"data,omitempty,omitzero"` // Base64-encoded image data.
}

// CaptureScreenshot capture page screenshot.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-captureScreenshot
var CaptureScreenshot = cdp.Command[CaptureScreenshotParams, CaptureScreenshotResult]{Method: CommandCaptureScreenshot}

// CaptureSnapshotParams are the parameters of the command
// Page.captureSnapshot.
type CaptureSnapshotParams struct {
	Format CaptureSnapshotFormat `json:"format,omitempty,omitzero"` // Format (defaults to mhtml).
}

// CaptureSnapshotResult is the result of the command Page.captureSnapshot.
type CaptureSnapshotResult struct {
	Data string `json:"data,omitempty,omitzero"` // Serialized page data.
}

// CaptureSnapshot returns a snapshot of the page as a string. For MHTML
// format, the serialization includes iframes, shadow DOM, external resources,
// and element-inline styles.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-captureSnapshot
var CaptureSnapshot = cdp.Command[CaptureSnapshotParams, CaptureSnapshotResult]{Method: CommandCaptureSnapshot}

// CreateIsolatedWorldParams are the parameters of the command
// Page.createIsolatedWorld.
type CreateIsolatedWorldParams struct {
	FrameID               cdp.FrameID `json:"frameId"`                                  // Id of the frame in which the isolated world should be created.
	WorldName             string      `json:"worldName,omitempty,omitzero"`             // An optional name which is reported in the Execution Context.
	GrantUniveralAccess   *bool       `json:"grantUniveralAccess,omitempty,omitzero"`   // Whether or not universal access should be granted to the isolated world. This is a powerful option, use with caution.
	ContentSecurityPolicy string      `json:"contentSecurityPolicy,omitempty,omitzero"` // An optional content security policy to set for the isolated world. If omitted, any existing CSP for the world will be cleared. Note that clearing or updating the CSP does not immediately affect the active context in the same document because LocalDOMWindow caches the ContentSecurityPolicy object. The change takes effect on subsequent navigations when a new window context is created.
}

// CreateIsolatedWorldResult is the result of the command
// Page.createIsolatedWorld.
type CreateIsolatedWorldResult struct {
	ExecutionContextID runtime.ExecutionContextID `json:"executionContextId,omitempty,omitzero"` // Execution context of the isolated world.
}

// CreateIsolatedWorld creates an isolated world for the given frame.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-createIsolatedWorld
var CreateIsolatedWorld = cdp.Command[CreateIsolatedWorldParams, CreateIsolatedWorldResult]{Method: CommandCreateIsolatedWorld}

// Disable disables page domain notifications.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-disable
var Disable = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandDisable}

// EnableParams are the parameters of the command Page.enable.
type EnableParams struct {
	EnableFileChooserOpenedEvent *bool `json:"enableFileChooserOpenedEvent,omitempty,omitzero"` // If true, the Page.fileChooserOpened event will be emitted regardless of the state set by Page.setInterceptFileChooserDialog command (default: false).
}

// Enable enables page domain notifications.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-enable
var Enable = cdp.Command[EnableParams, cdp.Empty]{Method: CommandEnable}

// GetAppManifestParams are the parameters of the command
// Page.getAppManifest.
type GetAppManifestParams struct {
	ManifestID string `json:"manifestId,omitempty,omitzero"`
}

// GetAppManifestResult is the result of the command Page.getAppManifest.
type GetAppManifestResult struct {
	URL      string              `json:"url,omitempty,omitzero"` // Manifest location.
	Errors   []*AppManifestError `json:"errors,omitempty,omitzero"`
	Data     string              `json:"data,omitempty,omitzero"` // Manifest content.
	Manifest *WebAppManifest     `json:"manifest,omitempty,omitzero"`
}

// GetAppManifest gets the processed manifest for this current document. This
// API always waits for the manifest to be loaded. If manifestId is provided,
// and it does not match the manifest of the current document, this API errors
// out. If there is not a loaded page, this API errors out immediately.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-getAppManifest
var GetAppManifest = cdp.Command[GetAppManifestParams, GetAppManifestResult]{Method: CommandGetAppManifest}

// GetInstallabilityErrorsResult is the result of the command
// Page.getInstallabilityErrors.
type GetInstallabilityErrorsResult struct {
	InstallabilityErrors []*InstallabilityError `json:"installabilityErrors,omitempty,omitzero"`
}

// GetInstallabilityErrors [no description].
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-getInstallabilityErrors
var GetInstallabilityErrors = cdp.Command[cdp.Empty, GetInstallabilityErrorsResult]{Method: CommandGetInstallabilityErrors}

// GetAppIDResult is the result of the command Page.getAppId.
type GetAppIDResult struct {
	AppID         string `json:"appId,omitempty,omitzero"`         // App id, either from manifest's id attribute or computed from start_url
	RecommendedID string `json:"recommendedId,omitempty,omitzero"` // Recommendation for manifest's id attribute to match current id computed from start_url
	BundleID      string `json:"bundleId,omitempty,omitzero"`      // The bundle ID for an Isolated Web App (IWA)
	ParentAppName string `json:"parentAppName,omitempty,omitzero"` // The name of the parent app if this app is a Sub-App
}

// GetAppID returns the unique (PWA) app id, along with IWA bundle ID and
// parent app info. Only returns values if the feature flag
// 'WebAppEnableManifestId' is enabled.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-getAppId
var GetAppID = cdp.Command[cdp.Empty, GetAppIDResult]{Method: CommandGetAppID}

// GetSubAppsResult is the result of the command Page.getSubApps.
type GetSubAppsResult struct {
	SubApps []*SubApp `json:"subApps,omitempty,omitzero"`
}

// GetSubApps returns the list of installed child Sub-Apps for the inspected
// parent app.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-getSubApps
var GetSubApps = cdp.Command[cdp.Empty, GetSubAppsResult]{Method: CommandGetSubApps}

// GetSiblingSubAppsResult is the result of the command
// Page.getSiblingSubApps.
type GetSiblingSubAppsResult struct {
	SubApps []*SubApp `json:"subApps,omitempty,omitzero"`
}

// GetSiblingSubApps returns the list of sibling Sub-Apps sharing the same
// parent app if the inspected context is a Sub-App.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-getSiblingSubApps
var GetSiblingSubApps = cdp.Command[cdp.Empty, GetSiblingSubAppsResult]{Method: CommandGetSiblingSubApps}

// GetAdScriptAncestryParams are the parameters of the command
// Page.getAdScriptAncestry.
type GetAdScriptAncestryParams struct {
	FrameID cdp.FrameID `json:"frameId"`
}

// GetAdScriptAncestryResult is the result of the command
// Page.getAdScriptAncestry.
type GetAdScriptAncestryResult struct {
	AdScriptAncestry *cdp.AdAncestry `json:"adScriptAncestry,omitempty,omitzero"` // The ancestry chain of ad script identifiers leading to this frame's creation, along with the root script's filterlist rule. The ancestry chain is ordered from the most immediate script (in the frame creation stack) to more distant ancestors (that created the immediately preceding script). Only sent if frame is labelled as an ad and ids are available.
}

// GetAdScriptAncestry [no description].
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-getAdScriptAncestry
var GetAdScriptAncestry = cdp.Command[GetAdScriptAncestryParams, GetAdScriptAncestryResult]{Method: CommandGetAdScriptAncestry}

// GetFrameTreeResult is the result of the command Page.getFrameTree.
type GetFrameTreeResult struct {
	FrameTree *FrameTree `json:"frameTree,omitempty,omitzero"` // Present frame tree structure.
}

// GetFrameTree returns present frame tree structure.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-getFrameTree
var GetFrameTree = cdp.Command[cdp.Empty, GetFrameTreeResult]{Method: CommandGetFrameTree}

// GetLayoutMetricsResult is the result of the command Page.getLayoutMetrics.
type GetLayoutMetricsResult struct {
	CSSLayoutViewport *LayoutViewport `json:"cssLayoutViewport,omitempty,omitzero"` // Metrics relating to the layout viewport in CSS pixels.
	CSSVisualViewport *VisualViewport `json:"cssVisualViewport,omitempty,omitzero"` // Metrics relating to the visual viewport in CSS pixels.
	CSSContentSize    *dom.Rect       `json:"cssContentSize,omitempty,omitzero"`    // Size of scrollable area in CSS pixels.
}

// GetLayoutMetrics returns metrics relating to the layouting of the page,
// such as viewport bounds/scale.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-getLayoutMetrics
var GetLayoutMetrics = cdp.Command[cdp.Empty, GetLayoutMetricsResult]{Method: CommandGetLayoutMetrics}

// GetNavigationHistoryResult is the result of the command
// Page.getNavigationHistory.
type GetNavigationHistoryResult struct {
	CurrentIndex int64              `json:"currentIndex,omitempty,omitzero"` // Index of the current navigation history entry.
	Entries      []*NavigationEntry `json:"entries,omitempty,omitzero"`      // Array of navigation history entries.
}

// GetNavigationHistory returns navigation history for the current page.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-getNavigationHistory
var GetNavigationHistory = cdp.Command[cdp.Empty, GetNavigationHistoryResult]{Method: CommandGetNavigationHistory}

// ResetNavigationHistory resets navigation history for the current page.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-resetNavigationHistory
var ResetNavigationHistory = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandResetNavigationHistory}

// GetResourceContentParams are the parameters of the command
// Page.getResourceContent.
type GetResourceContentParams struct {
	FrameID cdp.FrameID `json:"frameId"` // Frame id to get resource for.
	URL     string      `json:"url"`     // URL of the resource to get content for.
}

// GetResourceContentResult is the result of the command
// Page.getResourceContent.
type GetResourceContentResult struct {
	Content       []byte `json:"content,omitempty,omitzero"` // Resource content.
	Base64encoded bool   `json:"base64Encoded"`              // True, if content was served as base64.
}

// UnmarshalJSON decodes the value. The browser sends content as text, or as
// base64 when r.Base64encoded, and Content holds the decoded bytes.
func (r *GetResourceContentResult) UnmarshalJSON(buf []byte) error {
	type plain GetResourceContentResult
	aux := struct {
		*plain
		Content string `json:"content"`
	}{plain: (*plain)(r)}
	if err := jsonv2.Unmarshal(buf, &aux); err != nil {
		return err
	}
	if r.Base64encoded {
		b, err := base64.StdEncoding.DecodeString(aux.Content)
		if err != nil {
			return fmt.Errorf("decoding content: %w", err)
		}
		r.Content = b
		return nil
	}
	r.Content = []byte(aux.Content)
	return nil
}

// GetResourceContent returns content of the given resource.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-getResourceContent
var GetResourceContent = cdp.Command[GetResourceContentParams, GetResourceContentResult]{Method: CommandGetResourceContent}

// GetResourceTreeResult is the result of the command Page.getResourceTree.
type GetResourceTreeResult struct {
	FrameTree *FrameResourceTree `json:"frameTree,omitempty,omitzero"` // Present frame / resource tree structure.
}

// GetResourceTree returns present frame / resource tree structure.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-getResourceTree
var GetResourceTree = cdp.Command[cdp.Empty, GetResourceTreeResult]{Method: CommandGetResourceTree}

// HandleJavaScriptDialogParams are the parameters of the command
// Page.handleJavaScriptDialog.
type HandleJavaScriptDialogParams struct {
	Accept     bool   `json:"accept"`                        // Whether to accept or dismiss the dialog.
	PromptText string `json:"promptText,omitempty,omitzero"` // The text to enter into the dialog prompt before accepting. Used only if this is a prompt dialog.
}

// HandleJavaScriptDialog accepts or dismisses a JavaScript initiated dialog
// (alert, confirm, prompt, or onbeforeunload).
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-handleJavaScriptDialog
var HandleJavaScriptDialog = cdp.Command[HandleJavaScriptDialogParams, cdp.Empty]{Method: CommandHandleJavaScriptDialog}

// NavigateParams are the parameters of the command Page.navigate.
type NavigateParams struct {
	URL            string         `json:"url"`                               // URL to navigate the page to.
	Referrer       string         `json:"referrer,omitempty,omitzero"`       // Referrer URL.
	TransitionType TransitionType `json:"transitionType,omitempty,omitzero"` // Intended transition type.
	FrameID        cdp.FrameID    `json:"frameId,omitempty,omitzero"`        // Frame id to navigate, if not specified navigates the top frame.
	ReferrerPolicy ReferrerPolicy `json:"referrerPolicy,omitempty,omitzero"` // Referrer-policy used for the navigation.
}

// NavigateResult is the result of the command Page.navigate.
type NavigateResult struct {
	FrameID    cdp.FrameID  `json:"frameId,omitempty,omitzero"`   // Frame id that has navigated (or failed to navigate)
	LoaderID   cdp.LoaderID `json:"loaderId,omitempty,omitzero"`  // Loader identifier. This is omitted in case of same-document navigation, as the previously committed loaderId would not change.
	ErrorText  string       `json:"errorText,omitempty,omitzero"` // User friendly error message, present if and only if navigation has failed.
	IsDownload bool         `json:"isDownload"`                   // Whether the navigation resulted in a download.
}

// Navigate navigates current page to the given URL.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-navigate
var Navigate = cdp.Command[NavigateParams, NavigateResult]{Method: CommandNavigate}

// NavigateToHistoryEntryParams are the parameters of the command
// Page.navigateToHistoryEntry.
type NavigateToHistoryEntryParams struct {
	EntryID int64 `json:"entryId"` // Unique id of the entry to navigate to.
}

// NavigateToHistoryEntry navigates current page to the given history entry.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-navigateToHistoryEntry
var NavigateToHistoryEntry = cdp.Command[NavigateToHistoryEntryParams, cdp.Empty]{Method: CommandNavigateToHistoryEntry}

// PrintToPDFParams are the parameters of the command Page.printToPDF.
type PrintToPDFParams struct {
	Landscape               *bool                  `json:"landscape,omitempty,omitzero"`               // Paper orientation. Defaults to false.
	DisplayHeaderFooter     *bool                  `json:"displayHeaderFooter,omitempty,omitzero"`     // Display header and footer. Defaults to false.
	PrintBackground         *bool                  `json:"printBackground,omitempty,omitzero"`         // Print background graphics. Defaults to false.
	Scale                   float64                `json:"scale,omitempty,omitzero"`                   // Scale of the webpage rendering. Defaults to 1.
	PaperWidth              float64                `json:"paperWidth,omitempty,omitzero"`              // Paper width in inches. Defaults to 8.5 inches.
	PaperHeight             float64                `json:"paperHeight,omitempty,omitzero"`             // Paper height in inches. Defaults to 11 inches.
	MarginTop               *float64               `json:"marginTop,omitempty,omitzero"`               // Top margin in inches. Defaults to 1cm (~0.4 inches).
	MarginBottom            *float64               `json:"marginBottom,omitempty,omitzero"`            // Bottom margin in inches. Defaults to 1cm (~0.4 inches).
	MarginLeft              *float64               `json:"marginLeft,omitempty,omitzero"`              // Left margin in inches. Defaults to 1cm (~0.4 inches).
	MarginRight             *float64               `json:"marginRight,omitempty,omitzero"`             // Right margin in inches. Defaults to 1cm (~0.4 inches).
	PageRanges              string                 `json:"pageRanges,omitempty,omitzero"`              // Paper ranges to print, one based, e.g., '1-5, 8, 11-13'. Pages are printed in the document order, not in the order specified, and no more than once. Defaults to empty string, which implies the entire document is printed. The page numbers are quietly capped to actual page count of the document, and ranges beyond the end of the document are ignored. If this results in no pages to print, an error is reported. It is an error to specify a range with start greater than end.
	HeaderTemplate          string                 `json:"headerTemplate,omitempty,omitzero"`          // HTML template for the print header. Should be valid HTML markup with following classes used to inject printing values into them: - date: formatted print date - title: document title - url: document location - pageNumber: current page number - totalPages: total pages in the document  For example, <span class=title></span> would generate span containing the title.
	FooterTemplate          string                 `json:"footerTemplate,omitempty,omitzero"`          // HTML template for the print footer. Should use the same format as the headerTemplate.
	PreferCSSPageSize       *bool                  `json:"preferCSSPageSize,omitempty,omitzero"`       // Whether or not to prefer page size as defined by css. Defaults to false, in which case the content will be scaled to fit the paper size.
	TransferMode            PrintToPDFTransferMode `json:"transferMode,omitempty,omitzero"`            // return as stream
	GenerateTaggedPDF       *bool                  `json:"generateTaggedPDF,omitempty,omitzero"`       // Whether or not to generate tagged (accessible) PDF. Defaults to embedder choice.
	GenerateDocumentOutline *bool                  `json:"generateDocumentOutline,omitempty,omitzero"` // Whether or not to embed the document outline into the PDF.
}

// PrintToPDFResult is the result of the command Page.printToPDF.
type PrintToPDFResult struct {
	Data   []byte          `json:"data,omitempty,omitzero"`   // Base64-encoded pdf data. Empty if |returnAsStream| is specified.
	Stream io.StreamHandle `json:"stream,omitempty,omitzero"` // A handle of the stream that holds resulting PDF data.
}

// PrintToPDF print page as PDF.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-printToPDF
var PrintToPDF = cdp.Command[PrintToPDFParams, PrintToPDFResult]{Method: CommandPrintToPDF}

// ReloadParams are the parameters of the command Page.reload.
type ReloadParams struct {
	IgnoreCache            *bool        `json:"ignoreCache,omitempty,omitzero"`            // If true, browser cache is ignored (as if the user pressed Shift+refresh).
	ScriptToEvaluateOnLoad string       `json:"scriptToEvaluateOnLoad,omitempty,omitzero"` // If set, the script will be injected into all frames of the inspected page after reload. Argument will be ignored if reloading dataURL origin.
	LoaderID               cdp.LoaderID `json:"loaderId,omitempty,omitzero"`               // If set, an error will be thrown if the target page's main frame's loader id does not match the provided id. This prevents accidentally reloading an unintended target in case there's a racing navigation.
}

// Reload reloads given page optionally ignoring the cache.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-reload
var Reload = cdp.Command[ReloadParams, cdp.Empty]{Method: CommandReload}

// RemoveScriptToEvaluateOnNewDocumentParams are the parameters of the
// command Page.removeScriptToEvaluateOnNewDocument.
type RemoveScriptToEvaluateOnNewDocumentParams struct {
	Identifier ScriptIdentifier `json:"identifier"`
}

// RemoveScriptToEvaluateOnNewDocument removes given script from the list.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-removeScriptToEvaluateOnNewDocument
var RemoveScriptToEvaluateOnNewDocument = cdp.Command[RemoveScriptToEvaluateOnNewDocumentParams, cdp.Empty]{Method: CommandRemoveScriptToEvaluateOnNewDocument}

// ScreencastFrameAckParams are the parameters of the command
// Page.screencastFrameAck.
type ScreencastFrameAckParams struct {
	SessionID int64 `json:"sessionId"` // Frame number.
}

// ScreencastFrameAck acknowledges that a screencast frame has been received
// by the frontend.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-screencastFrameAck
var ScreencastFrameAck = cdp.Command[ScreencastFrameAckParams, cdp.Empty]{Method: CommandScreencastFrameAck}

// SearchInResourceParams are the parameters of the command
// Page.searchInResource.
type SearchInResourceParams struct {
	FrameID       cdp.FrameID `json:"frameId"`                          // Frame id for resource to search in.
	URL           string      `json:"url"`                              // URL of the resource to search in.
	Query         string      `json:"query"`                            // String to search for.
	CaseSensitive *bool       `json:"caseSensitive,omitempty,omitzero"` // If true, search is case sensitive.
	IsRegex       *bool       `json:"isRegex,omitempty,omitzero"`       // If true, treats string parameter as regex.
}

// SearchInResourceResult is the result of the command Page.searchInResource.
type SearchInResourceResult struct {
	Result []*debugger.SearchMatch `json:"result,omitempty,omitzero"` // List of search matches.
}

// SearchInResource searches for given string in resource content.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-searchInResource
var SearchInResource = cdp.Command[SearchInResourceParams, SearchInResourceResult]{Method: CommandSearchInResource}

// SetAdBlockingEnabledParams are the parameters of the command
// Page.setAdBlockingEnabled.
type SetAdBlockingEnabledParams struct {
	Enabled bool `json:"enabled"` // Whether to block ads.
}

// SetAdBlockingEnabled enable Chrome's experimental ad filter on all sites.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-setAdBlockingEnabled
var SetAdBlockingEnabled = cdp.Command[SetAdBlockingEnabledParams, cdp.Empty]{Method: CommandSetAdBlockingEnabled}

// SetBypassCSPParams are the parameters of the command Page.setBypassCSP.
type SetBypassCSPParams struct {
	Enabled bool `json:"enabled"` // Whether to bypass page CSP.
}

// SetBypassCSP enable page Content Security Policy by-passing.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-setBypassCSP
var SetBypassCSP = cdp.Command[SetBypassCSPParams, cdp.Empty]{Method: CommandSetBypassCSP}

// GetPermissionsPolicyStateParams are the parameters of the command
// Page.getPermissionsPolicyState.
type GetPermissionsPolicyStateParams struct {
	FrameID cdp.FrameID `json:"frameId"`
}

// GetPermissionsPolicyStateResult is the result of the command
// Page.getPermissionsPolicyState.
type GetPermissionsPolicyStateResult struct {
	States []*PermissionsPolicyFeatureState `json:"states,omitempty,omitzero"`
}

// GetPermissionsPolicyState get Permissions Policy state on given frame.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-getPermissionsPolicyState
var GetPermissionsPolicyState = cdp.Command[GetPermissionsPolicyStateParams, GetPermissionsPolicyStateResult]{Method: CommandGetPermissionsPolicyState}

// GetOriginTrialsParams are the parameters of the command
// Page.getOriginTrials.
type GetOriginTrialsParams struct {
	FrameID cdp.FrameID `json:"frameId"`
}

// GetOriginTrialsResult is the result of the command Page.getOriginTrials.
type GetOriginTrialsResult struct {
	OriginTrials []*cdp.OriginTrial `json:"originTrials,omitempty,omitzero"`
}

// GetOriginTrials get Origin Trials on given frame.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-getOriginTrials
var GetOriginTrials = cdp.Command[GetOriginTrialsParams, GetOriginTrialsResult]{Method: CommandGetOriginTrials}

// SetFontFamiliesParams are the parameters of the command
// Page.setFontFamilies.
type SetFontFamiliesParams struct {
	FontFamilies *FontFamilies         `json:"fontFamilies"`                  // Specifies font families to set. If a font family is not specified, it won't be changed.
	ForScripts   []*ScriptFontFamilies `json:"forScripts,omitempty,omitzero"` // Specifies font families to set for individual scripts.
}

// SetFontFamilies set generic font families.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-setFontFamilies
var SetFontFamilies = cdp.Command[SetFontFamiliesParams, cdp.Empty]{Method: CommandSetFontFamilies}

// SetFontSizesParams are the parameters of the command Page.setFontSizes.
type SetFontSizesParams struct {
	FontSizes *FontSizes `json:"fontSizes"` // Specifies font sizes to set. If a font size is not specified, it won't be changed.
}

// SetFontSizes set default font sizes.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-setFontSizes
var SetFontSizes = cdp.Command[SetFontSizesParams, cdp.Empty]{Method: CommandSetFontSizes}

// SetDocumentContentParams are the parameters of the command
// Page.setDocumentContent.
type SetDocumentContentParams struct {
	FrameID cdp.FrameID `json:"frameId"` // Frame id to set HTML for.
	HTML    string      `json:"html"`    // HTML content to set.
}

// SetDocumentContent sets given markup as the document's HTML.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-setDocumentContent
var SetDocumentContent = cdp.Command[SetDocumentContentParams, cdp.Empty]{Method: CommandSetDocumentContent}

// SetLifecycleEventsEnabledParams are the parameters of the command
// Page.setLifecycleEventsEnabled.
type SetLifecycleEventsEnabledParams struct {
	Enabled bool `json:"enabled"` // If true, starts emitting lifecycle events.
}

// SetLifecycleEventsEnabled controls whether page will emit lifecycle
// events.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-setLifecycleEventsEnabled
var SetLifecycleEventsEnabled = cdp.Command[SetLifecycleEventsEnabledParams, cdp.Empty]{Method: CommandSetLifecycleEventsEnabled}

// StartScreencastParams are the parameters of the command
// Page.startScreencast.
type StartScreencastParams struct {
	Format            StartScreencastFormat `json:"format,omitempty,omitzero"`            // Image compression format.
	Quality           *int64                `json:"quality,omitempty,omitzero"`           // Compression quality from range [0..100].
	MaxWidth          int64                 `json:"maxWidth,omitempty,omitzero"`          // Maximum screenshot width.
	MaxHeight         int64                 `json:"maxHeight,omitempty,omitzero"`         // Maximum screenshot height.
	EveryNthFrame     int64                 `json:"everyNthFrame,omitempty,omitzero"`     // Send every n-th frame. Must be a positive integer.
	MaxFramesInFlight int64                 `json:"maxFramesInFlight,omitempty,omitzero"` // Maximum number of frames sent until screencastFrameAck is required. Defaults to 3. Must be a positive integer.
	SendLastFrame     *bool                 `json:"sendLastFrame,omitempty,omitzero"`     // By default, after screencastFrameAck arrives, the next produced frame is sent. Passing this flag enables storing the last produced frame in memory, which is immediately sent upon screencastFrameAck. This way, overall performance is traded for a better latency.
}

// StartScreencast starts sending each frame using the screencastFrame event.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-startScreencast
var StartScreencast = cdp.Command[StartScreencastParams, cdp.Empty]{Method: CommandStartScreencast}

// StartScreenRecordingParams are the parameters of the command
// Page.startScreenRecording.
type StartScreenRecordingParams struct {
	Audio     *bool `json:"audio,omitempty,omitzero"`
	MaxWidth  int64 `json:"maxWidth,omitempty,omitzero"`  // Maximum frame width in pixels.
	MaxHeight int64 `json:"maxHeight,omitempty,omitzero"` // Maximum frame height in pixels.
	FrameRate int64 `json:"frameRate,omitempty,omitzero"` // Maximum frame rate in frames per second.
}

// StartScreenRecordingResult is the result of the command
// Page.startScreenRecording.
type StartScreenRecordingResult struct {
	Stream io.StreamHandle `json:"stream,omitempty,omitzero"` // A handle of the stream that holds resulting screencast data.
}

// StartScreenRecording starts screencast video recording.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-startScreenRecording
var StartScreenRecording = cdp.Command[StartScreenRecordingParams, StartScreenRecordingResult]{Method: CommandStartScreenRecording}

// StopScreenRecordingResult is the result of the command
// Page.stopScreenRecording.
type StopScreenRecordingResult struct {
	Stream io.StreamHandle `json:"stream,omitempty,omitzero"` // A handle of the stream that holds resulting screencast data.
}

// StopScreenRecording stops screencast video recording.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-stopScreenRecording
var StopScreenRecording = cdp.Command[cdp.Empty, StopScreenRecordingResult]{Method: CommandStopScreenRecording}

// StopLoading force the page stop all navigations and pending resource
// fetches.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-stopLoading
var StopLoading = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandStopLoading}

// Crash crashes renderer on the IO thread, generates minidumps.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-crash
var Crash = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandCrash}

// Close tries to close page, running its beforeunload hooks, if any.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-close
var Close = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandClose}

// SetWebLifecycleStateParams are the parameters of the command
// Page.setWebLifecycleState.
type SetWebLifecycleStateParams struct {
	State SetWebLifecycleStateState `json:"state"` // Target lifecycle state
}

// SetWebLifecycleState tries to update the web lifecycle state of the page.
// It will transition the page to the given state according to:
// https://github.com/WICG/web-lifecycle/.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-setWebLifecycleState
var SetWebLifecycleState = cdp.Command[SetWebLifecycleStateParams, cdp.Empty]{Method: CommandSetWebLifecycleState}

// StopScreencast stops sending each frame in the screencastFrame.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-stopScreencast
var StopScreencast = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandStopScreencast}

// ProduceCompilationCacheParams are the parameters of the command
// Page.produceCompilationCache.
type ProduceCompilationCacheParams struct {
	Scripts []*CompilationCacheParams `json:"scripts"`
}

// ProduceCompilationCache requests backend to produce compilation cache for
// the specified scripts. scripts are appended to the list of scripts for which
// the cache would be produced. The list may be reset during page navigation.
// When script with a matching URL is encountered, the cache is optionally
// produced upon backend discretion, based on internal heuristics. See also:
// Page.compilationCacheProduced.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-produceCompilationCache
var ProduceCompilationCache = cdp.Command[ProduceCompilationCacheParams, cdp.Empty]{Method: CommandProduceCompilationCache}

// AddCompilationCacheParams are the parameters of the command
// Page.addCompilationCache.
type AddCompilationCacheParams struct {
	URL  string `json:"url"`
	Data []byte `json:"data"` // Base64-encoded data
}

// AddCompilationCache seeds compilation cache for given url. Compilation
// cache does not survive cross-process navigation.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-addCompilationCache
var AddCompilationCache = cdp.Command[AddCompilationCacheParams, cdp.Empty]{Method: CommandAddCompilationCache}

// ClearCompilationCache clears seeded compilation cache.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-clearCompilationCache
var ClearCompilationCache = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandClearCompilationCache}

// SetSPCTransactionModeParams are the parameters of the command
// Page.setSPCTransactionMode.
type SetSPCTransactionModeParams struct {
	Mode SetSPCTransactionModeMode `json:"mode"`
}

// SetSPCTransactionMode sets the Secure Payment Confirmation transaction
// mode.
// https://w3c.github.io/secure-payment-confirmation/#sctn-automation-set-spc-transaction-mode.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-setSPCTransactionMode
var SetSPCTransactionMode = cdp.Command[SetSPCTransactionModeParams, cdp.Empty]{Method: CommandSetSPCTransactionMode}

// SetRPHRegistrationModeParams are the parameters of the command
// Page.setRPHRegistrationMode.
type SetRPHRegistrationModeParams struct {
	Mode SetRPHRegistrationModeMode `json:"mode"`
}

// SetRPHRegistrationMode extensions for Custom Handlers API:
// https://html.spec.whatwg.org/multipage/system-state.html#rph-automation.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-setRPHRegistrationMode
var SetRPHRegistrationMode = cdp.Command[SetRPHRegistrationModeParams, cdp.Empty]{Method: CommandSetRPHRegistrationMode}

// GenerateTestReportParams are the parameters of the command
// Page.generateTestReport.
type GenerateTestReportParams struct {
	Message string `json:"message"`                  // Message to be displayed in the report.
	Group   string `json:"group,omitempty,omitzero"` // Specifies the endpoint group to deliver the report to.
}

// GenerateTestReport generates a report for testing.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-generateTestReport
var GenerateTestReport = cdp.Command[GenerateTestReportParams, cdp.Empty]{Method: CommandGenerateTestReport}

// WaitForDebugger pauses page execution. Can be resumed using generic
// Runtime.runIfWaitingForDebugger.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-waitForDebugger
var WaitForDebugger = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandWaitForDebugger}

// SetInterceptFileChooserDialogParams are the parameters of the command
// Page.setInterceptFileChooserDialog.
type SetInterceptFileChooserDialogParams struct {
	Enabled bool  `json:"enabled"`
	Cancel  *bool `json:"cancel,omitempty,omitzero"` // If true, cancels the dialog by emitting relevant events (if any) in addition to not showing it if the interception is enabled (default: false).
}

// SetInterceptFileChooserDialog intercept file chooser requests and transfer
// control to protocol clients. When file chooser interception is enabled,
// native file chooser dialog is not shown. Instead, a protocol event
// Page.fileChooserOpened is emitted.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-setInterceptFileChooserDialog
var SetInterceptFileChooserDialog = cdp.Command[SetInterceptFileChooserDialogParams, cdp.Empty]{Method: CommandSetInterceptFileChooserDialog}

// SetPrerenderingAllowedParams are the parameters of the command
// Page.setPrerenderingAllowed.
type SetPrerenderingAllowedParams struct {
	IsAllowed bool `json:"isAllowed"`
}

// SetPrerenderingAllowed enable/disable prerendering manually. This command
// is a short-term solution for https://crbug.com/1440085. See
// https://docs.google.com/document/d/12HVmFxYj5Jc-eJr5OmWsa2bqTJsbgGLKI6ZIyx0_wpA
// for more details. TODO(https://crbug.com/1440085): Remove this once Puppeteer
// supports tab targets.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-setPrerenderingAllowed
var SetPrerenderingAllowed = cdp.Command[SetPrerenderingAllowedParams, cdp.Empty]{Method: CommandSetPrerenderingAllowed}

// GetAnnotatedPageContentParams are the parameters of the command
// Page.getAnnotatedPageContent.
type GetAnnotatedPageContentParams struct {
	IncludeActionableInformation *bool `json:"includeActionableInformation,omitempty,omitzero"` // Whether to include actionable information. Defaults to true.
}

// GetAnnotatedPageContentResult is the result of the command
// Page.getAnnotatedPageContent.
type GetAnnotatedPageContentResult struct {
	Content []byte `json:"content,omitempty,omitzero"` // The annotated page content as a base64 encoded protobuf. The format is defined by the AnnotatedPageContent message in components/optimization_guide/proto/features/common_quality_data.proto
}

// GetAnnotatedPageContent get the annotated page content for the main frame.
// This is an experimental command that is subject to change.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-getAnnotatedPageContent
var GetAnnotatedPageContent = cdp.Command[GetAnnotatedPageContentParams, GetAnnotatedPageContentResult]{Method: CommandGetAnnotatedPageContent}

// DomContentEventFired [no description].
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#event-domContentEventFired
var DomContentEventFired = cdp.Event[EventDomContentEventFired]{Method: "Page.domContentEventFired"}

// FileChooserOpened emitted only when page.interceptFileChooser is enabled.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#event-fileChooserOpened
var FileChooserOpened = cdp.Event[EventFileChooserOpened]{Method: "Page.fileChooserOpened"}

// FrameAttached fired when frame has been attached to its parent.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#event-frameAttached
var FrameAttached = cdp.Event[EventFrameAttached]{Method: "Page.frameAttached"}

// FrameDetached fired when frame has been detached from its parent.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#event-frameDetached
var FrameDetached = cdp.Event[EventFrameDetached]{Method: "Page.frameDetached"}

// FrameSubtreeWillBeDetached fired before frame subtree is detached. Emitted
// before any frame of the subtree is actually detached.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#event-frameSubtreeWillBeDetached
var FrameSubtreeWillBeDetached = cdp.Event[EventFrameSubtreeWillBeDetached]{Method: "Page.frameSubtreeWillBeDetached"}

// FrameNavigated fired once navigation of the frame has completed. Frame is
// now associated with the new loader.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#event-frameNavigated
var FrameNavigated = cdp.Event[EventFrameNavigated]{Method: "Page.frameNavigated"}

// DocumentOpened fired when opening document to write to.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#event-documentOpened
var DocumentOpened = cdp.Event[EventDocumentOpened]{Method: "Page.documentOpened"}

// FrameResized [no description].
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#event-frameResized
var FrameResized = cdp.Event[EventFrameResized]{Method: "Page.frameResized"}

// FrameStartedNavigating fired when a navigation starts. This event is fired
// for both renderer-initiated and browser-initiated navigations. For
// renderer-initiated navigations, the event is fired after
// frameRequestedNavigation. Navigation may still be cancelled after the event
// is issued. Multiple events can be fired for a single navigation, for example,
// when a same-document navigation becomes a cross-document navigation (such as
// in the case of a frameset).
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#event-frameStartedNavigating
var FrameStartedNavigating = cdp.Event[EventFrameStartedNavigating]{Method: "Page.frameStartedNavigating"}

// FrameRequestedNavigation fired when a renderer-initiated navigation is
// requested. Navigation may still be cancelled after the event is issued.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#event-frameRequestedNavigation
var FrameRequestedNavigation = cdp.Event[EventFrameRequestedNavigation]{Method: "Page.frameRequestedNavigation"}

// FrameStartedLoading fired when frame has started loading.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#event-frameStartedLoading
var FrameStartedLoading = cdp.Event[EventFrameStartedLoading]{Method: "Page.frameStartedLoading"}

// FrameStoppedLoading fired when frame has stopped loading.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#event-frameStoppedLoading
var FrameStoppedLoading = cdp.Event[EventFrameStoppedLoading]{Method: "Page.frameStoppedLoading"}

// InterstitialHidden fired when interstitial page was hidden.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#event-interstitialHidden
var InterstitialHidden = cdp.Event[EventInterstitialHidden]{Method: "Page.interstitialHidden"}

// InterstitialShown fired when interstitial page was shown.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#event-interstitialShown
var InterstitialShown = cdp.Event[EventInterstitialShown]{Method: "Page.interstitialShown"}

// JavascriptDialogClosed fired when a JavaScript initiated dialog (alert,
// confirm, prompt, or onbeforeunload) has been closed.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#event-javascriptDialogClosed
var JavascriptDialogClosed = cdp.Event[EventJavascriptDialogClosed]{Method: "Page.javascriptDialogClosed"}

// JavascriptDialogOpening fired when a JavaScript initiated dialog (alert,
// confirm, prompt, or onbeforeunload) is about to open.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#event-javascriptDialogOpening
var JavascriptDialogOpening = cdp.Event[EventJavascriptDialogOpening]{Method: "Page.javascriptDialogOpening"}

// LifecycleEvent fired for lifecycle events (navigation, load, paint, etc)
// in the current target (including local frames).
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#event-lifecycleEvent
var LifecycleEvent = cdp.Event[EventLifecycleEvent]{Method: "Page.lifecycleEvent"}

// BackForwardCacheNotUsed fired for failed bfcache history navigations if
// BackForwardCache feature is enabled. Do not assume any ordering with the
// Page.frameNavigated event. This event is fired only for main-frame history
// navigation where the document changes (non-same-document navigations), when
// bfcache navigation fails.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#event-backForwardCacheNotUsed
var BackForwardCacheNotUsed = cdp.Event[EventBackForwardCacheNotUsed]{Method: "Page.backForwardCacheNotUsed"}

// LoadEventFired [no description].
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#event-loadEventFired
var LoadEventFired = cdp.Event[EventLoadEventFired]{Method: "Page.loadEventFired"}

// NavigatedWithinDocument fired when same-document navigation happens, e.g.
// due to history API usage or anchor navigation.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#event-navigatedWithinDocument
var NavigatedWithinDocument = cdp.Event[EventNavigatedWithinDocument]{Method: "Page.navigatedWithinDocument"}

// ScreencastFrame compressed image data requested by the startScreencast.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#event-screencastFrame
var ScreencastFrame = cdp.Event[EventScreencastFrame]{Method: "Page.screencastFrame"}

// ScreencastVisibilityChanged fired when the page with currently enabled
// screencast was shown or hidden .
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#event-screencastVisibilityChanged
var ScreencastVisibilityChanged = cdp.Event[EventScreencastVisibilityChanged]{Method: "Page.screencastVisibilityChanged"}

// WindowOpen fired when a new window is going to be opened, via
// window.open(), link click, form submission, etc.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#event-windowOpen
var WindowOpen = cdp.Event[EventWindowOpen]{Method: "Page.windowOpen"}

// CompilationCacheProduced issued for every compilation cache generated.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Page#event-compilationCacheProduced
var CompilationCacheProduced = cdp.Event[EventCompilationCacheProduced]{Method: "Page.compilationCacheProduced"}

// Command names.
const (
	CommandAddScriptToEvaluateOnNewDocument    = "Page.addScriptToEvaluateOnNewDocument"
	CommandBringToFront                        = "Page.bringToFront"
	CommandCaptureScreenshot                   = "Page.captureScreenshot"
	CommandCaptureSnapshot                     = "Page.captureSnapshot"
	CommandCreateIsolatedWorld                 = "Page.createIsolatedWorld"
	CommandDisable                             = "Page.disable"
	CommandEnable                              = "Page.enable"
	CommandGetAppManifest                      = "Page.getAppManifest"
	CommandGetInstallabilityErrors             = "Page.getInstallabilityErrors"
	CommandGetAppID                            = "Page.getAppId"
	CommandGetSubApps                          = "Page.getSubApps"
	CommandGetSiblingSubApps                   = "Page.getSiblingSubApps"
	CommandGetAdScriptAncestry                 = "Page.getAdScriptAncestry"
	CommandGetFrameTree                        = "Page.getFrameTree"
	CommandGetLayoutMetrics                    = "Page.getLayoutMetrics"
	CommandGetNavigationHistory                = "Page.getNavigationHistory"
	CommandResetNavigationHistory              = "Page.resetNavigationHistory"
	CommandGetResourceContent                  = "Page.getResourceContent"
	CommandGetResourceTree                     = "Page.getResourceTree"
	CommandHandleJavaScriptDialog              = "Page.handleJavaScriptDialog"
	CommandNavigate                            = "Page.navigate"
	CommandNavigateToHistoryEntry              = "Page.navigateToHistoryEntry"
	CommandPrintToPDF                          = "Page.printToPDF"
	CommandReload                              = "Page.reload"
	CommandRemoveScriptToEvaluateOnNewDocument = "Page.removeScriptToEvaluateOnNewDocument"
	CommandScreencastFrameAck                  = "Page.screencastFrameAck"
	CommandSearchInResource                    = "Page.searchInResource"
	CommandSetAdBlockingEnabled                = "Page.setAdBlockingEnabled"
	CommandSetBypassCSP                        = "Page.setBypassCSP"
	CommandGetPermissionsPolicyState           = "Page.getPermissionsPolicyState"
	CommandGetOriginTrials                     = "Page.getOriginTrials"
	CommandSetFontFamilies                     = "Page.setFontFamilies"
	CommandSetFontSizes                        = "Page.setFontSizes"
	CommandSetDocumentContent                  = "Page.setDocumentContent"
	CommandSetLifecycleEventsEnabled           = "Page.setLifecycleEventsEnabled"
	CommandStartScreencast                     = "Page.startScreencast"
	CommandStartScreenRecording                = "Page.startScreenRecording"
	CommandStopScreenRecording                 = "Page.stopScreenRecording"
	CommandStopLoading                         = "Page.stopLoading"
	CommandCrash                               = "Page.crash"
	CommandClose                               = "Page.close"
	CommandSetWebLifecycleState                = "Page.setWebLifecycleState"
	CommandStopScreencast                      = "Page.stopScreencast"
	CommandProduceCompilationCache             = "Page.produceCompilationCache"
	CommandAddCompilationCache                 = "Page.addCompilationCache"
	CommandClearCompilationCache               = "Page.clearCompilationCache"
	CommandSetSPCTransactionMode               = "Page.setSPCTransactionMode"
	CommandSetRPHRegistrationMode              = "Page.setRPHRegistrationMode"
	CommandGenerateTestReport                  = "Page.generateTestReport"
	CommandWaitForDebugger                     = "Page.waitForDebugger"
	CommandSetInterceptFileChooserDialog       = "Page.setInterceptFileChooserDialog"
	CommandSetPrerenderingAllowed              = "Page.setPrerenderingAllowed"
	CommandGetAnnotatedPageContent             = "Page.getAnnotatedPageContent"
)
