// Code generated by pdlgen. DO NOT EDIT.

// Package preload provides the Chrome DevTools Protocol
// commands, types, and events for the Preload domain.
//
// Generated by the pdlgen command.
package preload

import (
	"github.com/chromedp/cdproto/cdp"
)

// Enable [no description].
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Preload#method-enable
var Enable = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandEnable}

// Disable [no description].
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Preload#method-disable
var Disable = cdp.Command[cdp.Empty, cdp.Empty]{Method: CommandDisable}

// RuleSetUpdated upsert. Currently, it is only emitted when a rule set
// added.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Preload#event-ruleSetUpdated
var RuleSetUpdated = cdp.Event[EventRuleSetUpdated]{Method: "Preload.ruleSetUpdated"}

// RuleSetRemoved [no description].
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Preload#event-ruleSetRemoved
var RuleSetRemoved = cdp.Event[EventRuleSetRemoved]{Method: "Preload.ruleSetRemoved"}

// PreloadEnabledStateUpdated fired when a preload enabled state is updated.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Preload#event-preloadEnabledStateUpdated
var PreloadEnabledStateUpdated = cdp.Event[EventPreloadEnabledStateUpdated]{Method: "Preload.preloadEnabledStateUpdated"}

// PrefetchStatusUpdated fired when a prefetch attempt is updated.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Preload#event-prefetchStatusUpdated
var PrefetchStatusUpdated = cdp.Event[EventPrefetchStatusUpdated]{Method: "Preload.prefetchStatusUpdated"}

// PrerenderStatusUpdated fired when a prerender attempt is updated.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Preload#event-prerenderStatusUpdated
var PrerenderStatusUpdated = cdp.Event[EventPrerenderStatusUpdated]{Method: "Preload.prerenderStatusUpdated"}

// PreloadingAttemptSourcesUpdated send a list of sources for all preloading
// attempts in a document.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/Preload#event-preloadingAttemptSourcesUpdated
var PreloadingAttemptSourcesUpdated = cdp.Event[EventPreloadingAttemptSourcesUpdated]{Method: "Preload.preloadingAttemptSourcesUpdated"}

// Command names.
const (
	CommandEnable  = "Preload.enable"
	CommandDisable = "Preload.disable"
)
